// Code generated by agnos. DO NOT EDIT.

package add_arg

import (
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/api"
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/internal/commandprops"
)

// NewCommand builds this command's declaration — a 1:1 image of its
// command.yaml — on the empty base of Deps.OpinionatedAgnosCli.NewCommand, and
// closes Handle over the sandbox as the handler behind it. It is
// called once by sandbox/internal/cli/generated.new.go, and what it returns
// is one entry of Cli.Commands: the declaration alone, which the lib's dispatch
// copies before binding a command line onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewCommand(sandbox *api.Sandbox) *api.Command {
	self := sandbox.Deps.OpinionatedAgnosCli.NewCommand(sandbox.Deps.ArgvDeps)

	self.Name = "add_arg"
	self.Identifiers = []string{"add-arg"}
	self.Priority = 100
	self.Segments = 0
	self.Strict = true
	self.Pattern = "add-arg <Name>"
	self.Category = "Cli"
	self.Summary = "Add an arg to a command's command.yaml"
	self.Description = "Inserts one arg — the segments --start to --end of the command line — into sandbox/internal/commands/<command>/command.yaml (at --position, else at the end) and runs build. An arg given no --start reads the first segment no arg reads yet; with --trigger it is part of what the command matches on."
	self.Examples = []string{"add-arg file --type string --required --description \"the file to process\" --command exec", "add-arg count --type integer --default 1 --position 0 --command exec"}
	self.Hidden = false

	self.Args = []api.CommandArg{
		{
			Id:          "Verb",
			Start:       0,
			End:         0,
			Type:        api.ArgString,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Description: "",
			Trigger:     api.Trigger{Set: true, Type: api.TriggerEqual, Value: "add-arg", Negate: false, IgnoreCase: false},
		},
		{
			Id:          "Name",
			Start:       1,
			End:         1,
			Type:        api.ArgString,
			Required:    true,
			Default:     "",
			HasDefault:  false,
			Description: "the arg name; its exported Go form is the Input field the handler reads (file-name -> input.FileName)",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
		},
	}

	self.Flags = []api.CommandFlag{
		{
			Id:          "Command",
			Keys:        []string{"--command", "-c"},
			Type:        api.FlagString,
			Required:    true,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "the command (a verb or its package name) that receives the arg",
		},
		{
			Id:          "Start",
			Keys:        []string{"--start"},
			Type:        api.FlagString,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "the first segment the arg reads (defaults to the first no arg reads yet)",
		},
		{
			Id:          "End",
			Keys:        []string{"--end"},
			Type:        api.FlagString,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "the last segment the arg reads, -1 for the last one (defaults to --start)",
		},
		{
			Id:          "Type",
			Keys:        []string{"--type", "-t"},
			Type:        api.FlagString,
			Required:    false,
			Default:     "string",
			HasDefault:  true,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "what one segment converts to: string (the default), integer, number or uuid; anything but string reads one segment, and one that does not convert makes the command a non-match",
		},
		{
			Id:          "Description",
			Keys:        []string{"--description", "-d"},
			Type:        api.FlagString,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "the one-line help text of the arg",
		},
		{
			Id:          "Default",
			Keys:        []string{"--default"},
			Type:        api.FlagString,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "the literal bound when the arg is absent (cannot be combined with --required)",
		},
		{
			Id:          "Required",
			Keys:        []string{"--required", "-r"},
			Type:        api.FlagBoolean,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "a command line matching the command without the arg is a usage error",
		},
		{
			Id:          "Position",
			Keys:        []string{"--position"},
			Type:        api.FlagInteger,
			Required:    false,
			Default:     "-1",
			HasDefault:  true,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "zero-based index to insert the arg at (defaults to the end)",
		},
		{
			Id:          "Trigger",
			Keys:        []string{"--trigger"},
			Type:        api.FlagString,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "what the segments, joined by a space, have to read as for the command to run; without it the arg is a plain capture",
		},
		{
			Id:          "TriggerType",
			Keys:        []string{"--trigger-type"},
			Type:        api.FlagString,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "how the trigger is compared: equal, prefix (word by word), text-prefix, suffix, regex or one-of (defaults to equal)",
		},
		{
			Id:          "TriggerNegate",
			Keys:        []string{"--trigger-negate"},
			Type:        api.FlagBoolean,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "invert the trigger: the command runs when the segments do not match it",
		},
		{
			Id:          "TriggerIgnoreCase",
			Keys:        []string{"--trigger-ignore-case"},
			Type:        api.FlagBoolean,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "compare the trigger without regard to case",
		},
	}

	self.Handle = func(props *commandprops.CommandProps, input *Input, response *api.CommandResponse) error {
		return Handle(sandbox, props, input, response)
	}

	return self
}
