package add_flag

import (
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/api"
)

// NewCommand builds this command's declaration — the whole of what its
// entries.yaml says — and closes CommandHandler over the sandbox as the
// handler behind it. It is called once, by sandbox/internal/cli/new.go, and
// what it returns is one entry of Cli.Commands: the declaration alone, which
// the dispatch copies with api.BindCommand before binding a command line onto
// it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewCommand(sandbox *api.Sandbox) api.Command {
	command := api.NewCommand()

	command.Name = "add_flag"
	command.Identifiers = []string{"add-flag"}
	command.Category = "Cli System"
	command.Help = "Add a flag to a command's entries.yaml"
	command.LongDescription = "Appends one flag declaration to sandbox/internal/commands/<command>/entries.yaml\nand runs build so the command's new.go declares it. Without --identifier the\nflag answers to --<name>. Refuses a name or identifier the command already\nuses."
	command.Examples = []string{"add-flag output --identifier --out --identifier -o --type string --required --command exec", "add-flag verbose --type boolean --description \"print every step\" --command exec", "add-flag retries --type int --min 0 --max 5 --default 1 --command exec"}
	command.Hidden = false

	command.Flags = []api.CommandFlag{
		{
			Id:          "identifier",
			Type:        "string",
			Required:    false,
			Array:       true,
			Description: "a cli identifier for the flag, e.g. --out or -o (repeatable; defaults to --<name>)",
			Examples:    []string{"--identifier --out --identifier -o"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--identifier", "-i"},
		},
		{
			Id:          "command",
			Type:        "string",
			Required:    true,
			Array:       false,
			Description: "the command (identifier or package name) that receives the field",
			Examples:    []string{"--command exec"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--command", "-c"},
		},
		{
			Id:          "type",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the value type: string, boolean, int or float (defaults to string)",
			Examples:    []string{"--type int"},
			Default:     "string",
			HasDefault:  true,
			Identifiers: []string{"--type", "-t"},
		},
		{
			Id:          "description",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "help text shown for the field",
			Examples:    []string{"--description \"where the output is written\""},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--description", "-d"},
		},
		{
			Id:          "example",
			Type:        "string",
			Required:    false,
			Array:       true,
			Description: "an usage example for the field (repeatable)",
			Examples:    []string{"--example \"exec --out result.txt\""},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--example", "-e"},
		},
		{
			Id:          "default",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the literal assigned when the field is absent (cannot be combined with --required)",
			Examples:    []string{"--default ."},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--default"},
		},
		{
			Id:          "required",
			Type:        "boolean",
			Required:    false,
			Array:       false,
			Description: "fail with a usage error when the field is not provided (not for booleans or fields with --default)",
			Examples:    []string{"--required"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--required", "-r"},
		},
		{
			Id:          "array",
			Type:        "boolean",
			Required:    false,
			Array:       false,
			Description: "collect every occurrence into a []T field instead of a single value",
			Examples:    []string{"--array"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--array"},
		},
		{
			Id:          "min",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "smallest accepted value (int/float only)",
			Examples:    []string{"--type int --min 1"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--min"},
		},
		{
			Id:          "max",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "largest accepted value (int/float only)",
			Examples:    []string{"--type int --max 10"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--max"},
		},
		{
			Id:          "position",
			Type:        "int",
			Required:    false,
			Array:       false,
			Description: "zero-based index to insert the field at (defaults to the end)",
			Examples:    []string{"--position 0"},
			Default:     "-1",
			HasDefault:  true,
			Identifiers: []string{"--position"},
		},
		{
			Id:          "path",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the dir holding the project (defaults to the current directory)",
			Examples:    []string{"add-flag out --command exec --path ./my-project"},
			Default:     ".",
			HasDefault:  true,
			Identifiers: []string{"--path"},
		},
		{
			Id:          "quiet",
			Type:        "boolean",
			Required:    false,
			Array:       false,
			Description: "Quiets the cli output",
			Examples:    []string{},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--quiet", "-q"},
		},
	}

	command.Args = []api.CommandArg{
		{
			Id:          "name",
			Type:        "string",
			Required:    true,
			Array:       false,
			Description: "the flag name (the id the handler reads it back by, e.g. command.GetString(\"out-file\"))",
			Examples:    []string{"add-flag output --command exec"},
			Default:     "",
			HasDefault:  false,
		},
	}

	command.Handler = func(bound *api.Command) int {
		return CommandHandler(sandbox, bound)
	}

	return *command
}
