package remove_doc

import (
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/api"
)

// NewCommand builds this command's declaration — the whole of what its
// entries.yaml says — and closes CommandHandler over the sandbox as the
// handler behind it. It is called once, by sandbox/internal/cli/new.go, and
// what it returns is one entry of Cli.Commands: the declaration alone, which
// the dispatch copies with api.BindCommand before binding a command line onto
// it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewCommand(sandbox *api.Sandbox) api.Command {
	command := api.NewCommand()

	command.Name = "remove_doc"
	command.Identifiers = []string{"remove-doc"}
	command.Category = "Documentation"
	command.Help = "Delete a doc directory from docs/"
	command.LongDescription = "Deletes docs/<name>/ (doc.md, props.yaml, its assets and every sub-doc\nnested under it) and runs build so the indexes that listed it are rewritten\nwithout it. A theme left with no docs simply stops rendering a section in\nREADME.md; it is not an error, so themes.yaml can keep it."
	command.Examples = []string{"remove-doc HandleReports", "remove-doc PublicApi/api.AddDoc --path ./my-project"}
	command.Hidden = false

	command.Flags = []api.CommandFlag{
		{
			Id:          "path",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the dir holding the project (defaults to the current directory)",
			Examples:    []string{"remove-doc HandleReports --path ./my-project"},
			Default:     ".",
			HasDefault:  true,
			Identifiers: []string{"--path"},
		},
		{
			Id:          "quiet",
			Type:        "boolean",
			Required:    false,
			Array:       false,
			Description: "Quiets the cli output",
			Examples:    []string{"remove-doc HandleReports -q"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--quiet", "-q"},
		},
	}

	command.Args = []api.CommandArg{
		{
			Id:          "name",
			Type:        "string",
			Required:    true,
			Array:       false,
			Description: "the doc directory under docs/, nested with / for a sub-doc (e.g. PublicApi/api.AddDoc)",
			Examples:    []string{"remove-doc HandleReports"},
			Default:     "",
			HasDefault:  false,
		},
	}

	command.Handler = func(bound *api.Command) int {
		return CommandHandler(sandbox, bound)
	}

	return *command
}
