package help

import (
	"fmt"
	"slices"
	"strings"

	"github.com/MateusMoutinhoOrg/Agnos-Cli/sandbox/deps"
	"github.com/MateusMoutinhoOrg/Agnos-Cli/sandbox/deps/argvdeps"
	"github.com/MateusMoutinhoOrg/Agnos-Cli/sandbox/internal/config"
)

// This file is generated by `agnos build` from every
// sandbox/internal/commands/<name>/entries.yaml. The command metadata is
// baked into helpCommands below; the rendering code is fixed.

const (
	exitOk    = 0
	exitUsage = 1
)

// ─── ANSI escape sequences ──────────────────────────────────────────────────

const (
	bold    = "\033[1m"
	dim     = "\033[2m"
	italic  = "\033[3m"
	reset   = "\033[0m"
	cyan    = "\033[36m"
	green   = "\033[32m"
	yellow  = "\033[33m"
	magenta = "\033[35m"
	white   = "\033[97m"
	gray    = "\033[90m"
	red     = "\033[31m"
)

// ─── Baked command metadata ─────────────────────────────────────────────────

type helpField struct {
	Identifiers []string // empty for a positional argument
	Name        string   // set for a positional argument
	Description string
	Examples    []string
	Type        string
	Default     string
	Required    bool
}

type helpCommand struct {
	Identifiers     []string
	Category        string
	Description     string
	LongDescription string
	Examples        []string
	Hidden          bool
	Flags           []helpField
	Args            []helpField
}

var helpCommands = []helpCommand{
	{
		Identifiers:     []string{ "add-command" },
		Category:        "Cli System",
		Description:     "Scaffold a new command package in the project",
		LongDescription: "Creates sandbox/internal/commands/<name>/ with a hand-written\nentries.yaml and a stub handler.go, then runs build so entries.go\nand the dispatch layer are generated for it. Refuses to overwrite\nan existing command.\n",
		Examples:        []string{ "add-command my-feature", "add-command my-feature --path ./my-project",  },
		Hidden:          false,
		Flags: []helpField{
			{Identifiers: []string{ "--help" }, Description: "one-line help text for the new command", Examples: []string{ "add-command my-feature --help \"does the thing\" --category Misc",  }, Type: "string", Default: "", Required: true},
			{Identifiers: []string{ "--category" }, Description: "the category the new command is grouped under in help output", Examples: []string{ "add-command my-feature --help \"does the thing\" --category Misc",  }, Type: "string", Default: "", Required: true},
			{Identifiers: []string{ "--path" }, Description: "the dir holding the project (defaults to the current directory)", Examples: []string{ "add-command my-feature --path ./my-project",  }, Type: "string", Default: ".", Required: false},
			{Identifiers: []string{ "--quiet", "-q" }, Description: "Quiets the cli output", Examples: []string{ "add-command my-feature -q",  }, Type: "boolean", Default: "", Required: false},
		},
		Args: []helpField{
			{Name: "name", Description: "the name of the new command (e.g. my-feature)", Examples: []string{ "add-command my-feature",  }, Type: "string", Default: "", Required: true},
		},
	},
	{
		Identifiers:     []string{ "build" },
		Category:        "Core Commands",
		Description:     "Build the project in a directory",
		LongDescription: "Builds the project in the given directory, compiling\nthe source code into the output artifacts. If no\npath is provided, the current directory is used.\n",
		Examples:        []string{ "build", "build --path ./my-project", "build -q",  },
		Hidden:          false,
		Flags: []helpField{
			{Identifiers: []string{ "--path" }, Description: "the dir holding the project (defaults to the current directory)", Examples: []string{ "build --path ./my-project",  }, Type: "string", Default: ".", Required: false},
			{Identifiers: []string{ "--quiet", "-q" }, Description: "Quiets the cli output", Examples: []string{ "build -q",  }, Type: "boolean", Default: "", Required: false},
			{Identifiers: []string{ "--unsafe" }, Description: "Skips the verify schema gate before building", Examples: []string{ "build --unsafe",  }, Type: "boolean", Default: "", Required: false},
		},
		Args: []helpField{
		},
	},
	{
		Identifiers:     []string{ "cli-init" },
		Category:        "Cli System",
		Description:     "Initializes the CLI layer for the project",
		LongDescription: "Installs the std and argv deps the CLI layer depends on, renders the\n\"cli\" asset group into the project, and calls build.\n",
		Examples:        []string{ "cli-init", "cli-init --path ./my-project",  },
		Hidden:          false,
		Flags: []helpField{
			{Identifiers: []string{ "--path" }, Description: "the dir holding the project (defaults to the current directory)", Examples: []string{ "cli-init --path ./my-project",  }, Type: "string", Default: ".", Required: false},
			{Identifiers: []string{ "--quiet", "-q" }, Description: "Quiets the cli output", Examples: []string{ "cli-init -q",  }, Type: "boolean", Default: "", Required: false},
		},
		Args: []helpField{
		},
	},
	{
		Identifiers:     []string{ "cli-purge" },
		Category:        "Cli System",
		Description:     "Removes the CLI layer from the project",
		LongDescription: "Removes every file the \"cli\" asset group installs and calls build.\n",
		Examples:        []string{ "cli-purge", "cli-purge --path ./my-project",  },
		Hidden:          false,
		Flags: []helpField{
			{Identifiers: []string{ "--path" }, Description: "the dir holding the project (defaults to the current directory)", Examples: []string{ "cli-purge --path ./my-project",  }, Type: "string", Default: ".", Required: false},
			{Identifiers: []string{ "--quiet", "-q" }, Description: "Quiets the cli output", Examples: []string{ "cli-purge -q",  }, Type: "boolean", Default: "", Required: false},
		},
		Args: []helpField{
		},
	},
	{
		Identifiers:     []string{ "dep-install" },
		Category:        "Dependencies",
		Description:     "Installs an embedded dep into the project",
		LongDescription: "Renders every file under assets/deplist/<dep> into the project\nat the path it holds inside that dep, then calls build.\n",
		Examples:        []string{ "dep-install embed", "dep-install embed --path ./my-project",  },
		Hidden:          false,
		Flags: []helpField{
			{Identifiers: []string{ "--path" }, Description: "the dir holding the project (defaults to the current directory)", Examples: []string{ "dep-install --path ./my-project",  }, Type: "string", Default: ".", Required: false},
			{Identifiers: []string{ "--quiet", "-q" }, Description: "Quiets the cli output", Examples: []string{ "dep-install embed -q",  }, Type: "boolean", Default: "", Required: false},
		},
		Args: []helpField{
			{Name: "dep", Description: "the dep to install from assets/deplist", Examples: []string{ "dep-install embed",  }, Type: "string", Default: "", Required: true},
		},
	},
	{
		Identifiers:     []string{ "dep-list" },
		Category:        "Dependencies",
		Description:     "Lists the embedded deps available to install",
		LongDescription: "Lists the name of every dep under assets/deplist that dep-install\ncan render into a project.\n",
		Examples:        []string{ "dep-list",  },
		Hidden:          false,
		Flags: []helpField{
			{Identifiers: []string{ "--path" }, Description: "the dir holding the project (defaults to the current directory)", Examples: []string{ "dep-list --path ./my-project",  }, Type: "string", Default: ".", Required: false},
			{Identifiers: []string{ "--quiet", "-q" }, Description: "Quiets the cli output", Examples: []string{ "dep-list -q",  }, Type: "boolean", Default: "", Required: false},
		},
		Args: []helpField{
		},
	},
	{
		Identifiers:     []string{ "dep-remove" },
		Category:        "Dependencies",
		Description:     "Removes an embedded dep from the project",
		LongDescription: "Removes every file that assets/deplist/<dep> installs into the\nproject, then calls build.\n",
		Examples:        []string{ "dep-remove embed", "dep-remove embed --path ./my-project",  },
		Hidden:          false,
		Flags: []helpField{
			{Identifiers: []string{ "--path" }, Description: "the dir holding the project (defaults to the current directory)", Examples: []string{ "dep-remove --path ./my-project",  }, Type: "string", Default: ".", Required: false},
			{Identifiers: []string{ "--quiet", "-q" }, Description: "Quiets the cli output", Examples: []string{ "dep-remove embed -q",  }, Type: "boolean", Default: "", Required: false},
		},
		Args: []helpField{
			{Name: "dep", Description: "the dep to remove from the project", Examples: []string{ "dep-remove embed",  }, Type: "string", Default: "", Required: true},
		},
	},
	{
		Identifiers:     []string{ "deps-init" },
		Category:        "Dependency System",
		Description:     "Initializes the dependency-injection subsystem for the project",
		LongDescription: "Creates the sandbox/deps and adapters directories and calls build.\nRun this once before using dep-install.\n",
		Examples:        []string{ "deps-init", "deps-init --path ./my-project",  },
		Hidden:          false,
		Flags: []helpField{
			{Identifiers: []string{ "--path" }, Description: "the dir holding the project (defaults to the current directory)", Examples: []string{ "deps-init --path ./my-project",  }, Type: "string", Default: ".", Required: false},
			{Identifiers: []string{ "--quiet", "-q" }, Description: "Quiets the cli output", Examples: []string{ "deps-init -q",  }, Type: "boolean", Default: "", Required: false},
		},
		Args: []helpField{
		},
	},
	{
		Identifiers:     []string{ "deps-purge" },
		Category:        "Dependency System",
		Description:     "Removes the dependency-injection subsystem from the project",
		LongDescription: "Removes the sandbox/deps and adapters directories and calls build.\n",
		Examples:        []string{ "deps-purge", "deps-purge --path ./my-project",  },
		Hidden:          false,
		Flags: []helpField{
			{Identifiers: []string{ "--path" }, Description: "the dir holding the project (defaults to the current directory)", Examples: []string{ "deps-purge --path ./my-project",  }, Type: "string", Default: ".", Required: false},
			{Identifiers: []string{ "--quiet", "-q" }, Description: "Quiets the cli output", Examples: []string{ "deps-purge -q",  }, Type: "boolean", Default: "", Required: false},
		},
		Args: []helpField{
		},
	},
	{
		Identifiers:     []string{ "start" },
		Category:        "Core Commands",
		Description:     "Initialize a new project in a directory",
		LongDescription: "Scaffolds a new Agnos project in the given directory, creating\nthe required configuration files and folder structure. If no\npath is provided, the current directory is used.\n",
		Examples:        []string{ "start -p my-project", "start -p my-project --path ./my-project-dir", "start -p my-project -q",  },
		Hidden:          false,
		Flags: []helpField{
			{Identifiers: []string{ "--path" }, Description: "the dir holding the project (defaults to the current directory)", Examples: []string{ "start --path ./my-project",  }, Type: "string", Default: ".", Required: false},
			{Identifiers: []string{ "--project-name", "-p" }, Description: "the name of the project", Examples: []string{ "start -p my-project",  }, Type: "string", Default: "", Required: true},
			{Identifiers: []string{ "--quiet", "-q" }, Description: "Quiets the cli output", Examples: []string{ "start -q",  }, Type: "boolean", Default: "", Required: false},
			{Identifiers: []string{ "--force", "-f" }, Description: "Forces the creation of the project, overwriting existing files", Examples: []string{ "start -f",  }, Type: "boolean", Default: "", Required: false},
			{Identifiers: []string{ "--module", "-m" }, Description: "Module name for go.mod", Examples: []string{ "start -m github.com/user/project",  }, Type: "string", Default: "", Required: false},
		},
		Args: []helpField{
		},
	},
	{
		Identifiers:     []string{ "verify" },
		Category:        "Core Commands",
		Description:     "Checks the project keeps the sandbox/adapter schema",
		LongDescription: "Verifies the structural rules the harness depends on: sandbox/ imports\nstay inside sandbox/, sandbox/ holds only api, binds, deps, internal and\nnew.go, sandbox/api and sandbox/deps import nothing external, every\nsandbox/binds file mirrors a sandbox/api file and declares only functions,\nand adapters/ holds only availables and libs. `agnos build` runs this as a\ngate unless --unsafe is passed.\n",
		Examples:        []string{ "verify",  },
		Hidden:          false,
		Flags: []helpField{
			{Identifiers: []string{ "--path" }, Description: "the dir holding the project (defaults to the current directory)", Examples: []string{ "verify --path ./my-project",  }, Type: "string", Default: ".", Required: false},
			{Identifiers: []string{ "--quiet", "-q" }, Description: "Quiets the cli output", Examples: []string{ "verify -q",  }, Type: "boolean", Default: "", Required: false},
		},
		Args: []helpField{
		},
	},
	{
		Identifiers:     []string{ "version", "--version" },
		Category:        "Info",
		Description:     "Print the installed version",
		LongDescription: "Prints the current version of the installed binary and exits.\n",
		Examples:        []string{ "version",  },
		Hidden:          false,
		Flags: []helpField{
		},
		Args: []helpField{
		},
	},
	{
		Identifiers:     []string{"help", "--help"},
		Category:        "Info",
		Description:     "Display help for a command",
		LongDescription: "When called without arguments, lists every available command\ngrouped by category. When called with a command name, shows\ndetailed usage, arguments, flags, and examples for that command.",
		Examples:        []string{"help", "help start"},
	},
}

// ─── Entry points ───────────────────────────────────────────────────────────

// Run backs the `help` / `--help` verb: with no argument it prints the general
// help screen, with a command name it prints that command's detailed help.
func Run(deps *deps.Deps, verb argvdeps.Parser) int {
	name, err := verb.GetNextStringArg()
	if err != nil {
		PrintGeneralHelp(deps)
		return exitOk
	}

	for i := range helpCommands {
		if slices.Contains(helpCommands[i].Identifiers, name) {
			printCommandHelp(deps, &helpCommands[i])
			return exitOk
		}
	}

	p := deps.Std.Printf
	p("\n")
	p("  %s%s✘%s Unknown command: %s%s%s\n", bold, red, reset, bold+white, name, reset)
	p("  %sRun '%s help' to see available commands.%s\n", dim, config.ProjectName, reset)
	p("\n")
	return exitUsage
}

// ─── General help ──────────────────────────────────────────────────────────

// PrintGeneralHelp lists every command grouped by category. It is also the
// usage screen shown when the binary is run with no arguments.
func PrintGeneralHelp(deps *deps.Deps) {
	p := deps.Std.Printf

	printBanner(deps)

	p("  %s%sUSAGE%s\n", bold, cyan, reset)
	p("  %s│%s\n", gray, reset)
	p("  %s│%s  %s$%s %s %s<command>%s %s[flags]%s %s[args]%s\n",
		gray, reset, dim, reset, config.ProjectName,
		green, reset, yellow, reset, dim, reset,
	)
	p("  %s│%s\n", gray, reset)
	p("\n")

	categoryOrder := []string{}
	categorized := map[string][]helpCommand{}
	for _, cmd := range helpCommands {
		if cmd.Hidden {
			continue
		}
		cat := cmd.Category
		if cat == "" {
			cat = "Other"
		}
		if _, exists := categorized[cat]; !exists {
			categoryOrder = append(categoryOrder, cat)
		}
		categorized[cat] = append(categorized[cat], cmd)
	}

	maxNameLen := 0
	for _, cmd := range helpCommands {
		if cmd.Hidden || len(cmd.Identifiers) == 0 {
			continue
		}
		if n := len(cmd.Identifiers[0]); n > maxNameLen {
			maxNameLen = n
		}
	}

	for _, cat := range categoryOrder {
		p("  %s%s%s%s\n", bold, cyan, strings.ToUpper(cat), reset)
		p("  %s│%s\n", gray, reset)
		for _, cmd := range categorized[cat] {
			if len(cmd.Identifiers) == 0 {
				continue
			}
			name := cmd.Identifiers[0]

			aliasTag := ""
			if len(cmd.Identifiers) > 1 {
				aliasTag = fmt.Sprintf("  %s[%s]%s", dim, strings.Join(cmd.Identifiers[1:], ", "), reset)
			}

			dotsNeeded := (maxNameLen + 20) - len(name)
			if dotsNeeded < 4 {
				dotsNeeded = 4
			}
			dots := " " + strings.Repeat("·", dotsNeeded-2) + " "

			p("  %s│%s  %s%s%s%s%s%s%s%s\n",
				gray, reset, green+bold, name, reset, gray, dots, reset, cmd.Description, aliasTag,
			)
		}
		p("  %s│%s\n", gray, reset)
		p("\n")
	}

	p("  %s%s─── %sTip%s%s ──────────────────────────────%s\n",
		dim, gray, italic, reset+dim+gray, gray, reset,
	)
	p("  %sRun %s%s help <command>%s%s for detailed info on any command.%s\n",
		dim, reset+cyan, config.ProjectName, reset, dim, reset,
	)
	p("\n")
}

// ─── Per-command help ──────────────────────────────────────────────────────

func printCommandHelp(deps *deps.Deps, cmd *helpCommand) {
	p := deps.Std.Printf

	name := cmd.Identifiers[0]

	titleLine := fmt.Sprintf("%s %s", config.ProjectName, name)
	innerW := len(titleLine) + 4
	if w := len(cmd.Description) + 4; w > innerW {
		innerW = w
	}
	if innerW < 42 {
		innerW = 42
	}

	p("\n")
	p("  %s╭%s╮%s\n", cyan, strings.Repeat("─", innerW), reset)
	p("  %s│%s  %s%s%s%s%s│%s\n",
		cyan, reset, bold+white, titleLine, reset,
		strings.Repeat(" ", innerW-2-len(titleLine)), cyan, reset,
	)
	p("  %s│%s  %s%s%s%s%s│%s\n",
		cyan, reset, dim, cmd.Description, reset,
		strings.Repeat(" ", innerW-2-len(cmd.Description)), cyan, reset,
	)
	p("  %s╰%s╯%s\n", cyan, strings.Repeat("─", innerW), reset)
	p("\n")

	if cmd.LongDescription != "" {
		for _, line := range strings.Split(cmd.LongDescription, "\n") {
			p("  %s%s%s\n", dim, line, reset)
		}
		p("\n")
	}

	printSection(p, "USAGE")
	usage := fmt.Sprintf("  %s$%s %s %s", dim, reset, config.ProjectName, name)
	flagPart := ""
	if len(cmd.Flags) > 0 {
		flagPart = fmt.Sprintf(" %s[flags]%s", yellow, reset)
	}
	argPart := ""
	for _, arg := range cmd.Args {
		if arg.Required {
			argPart += fmt.Sprintf(" %s%s<%s>%s", bold, green, arg.Name, reset)
		} else {
			argPart += fmt.Sprintf(" %s[%s]%s", dim, arg.Name, reset)
		}
	}
	p("  %s│%s%s%s%s\n", gray, reset, usage, flagPart, argPart)
	p("  %s│%s\n", gray, reset)
	p("\n")

	if len(cmd.Identifiers) > 1 {
		printSection(p, "ALIASES")
		for _, alias := range cmd.Identifiers {
			bullet := gray + "◦" + reset
			if alias == name {
				bullet = green + "●" + reset
			}
			p("  %s│%s  %s %s%s%s\n", gray, reset, bullet, cyan, alias, reset)
		}
		p("  %s│%s\n", gray, reset)
		p("\n")
	}

	if len(cmd.Args) > 0 {
		printSection(p, "ARGUMENTS")
		for i, arg := range cmd.Args {
			printField(p, arg.Name, arg.Description, arg.Type, arg.Default, arg.Required, arg.Examples)
			if i < len(cmd.Args)-1 {
				p("  %s│%s\n", gray, reset)
			}
		}
		p("  %s│%s\n", gray, reset)
		p("\n")
	}

	if len(cmd.Flags) > 0 {
		printSection(p, "FLAGS")
		for i, flag := range cmd.Flags {
			label := strings.Join(flag.Identifiers, gray+", "+reset+yellow+bold)
			printField(p, label, flag.Description, flag.Type, flag.Default, flag.Required, flag.Examples)
			if i < len(cmd.Flags)-1 {
				p("  %s│%s\n", gray, reset)
			}
		}
		p("  %s│%s\n", gray, reset)
		p("\n")
	}

	if len(cmd.Examples) > 0 {
		printSection(p, "EXAMPLES")
		for _, ex := range cmd.Examples {
			p("  %s│%s  %s$%s %s %s\n", gray, reset, dim, reset, config.ProjectName, ex)
		}
		p("  %s│%s\n", gray, reset)
		p("\n")
	}
}

// ─── Helpers ───────────────────────────────────────────────────────────────

func printField(p func(string, ...any) (int, error), label, description, kind, def string, required bool, examples []string) {
	reqLabel := dim + "optional" + reset
	if required {
		reqLabel = yellow + bold + "required" + reset
	}

	p("  %s│%s  %s%s%s\n", gray, reset, green+bold, label, reset)
	p("  %s│%s    %s\n", gray, reset, description)
	p("  %s│%s    %s%s%s %s│%s %s\n",
		gray, reset, magenta, typeLabel(kind), reset, gray, reset, reqLabel,
	)
	if def != "" {
		p("  %s│%s    %sdefault:%s %s%s%s\n", gray, reset, dim, reset, white+bold, def, reset)
	}
	for _, ex := range examples {
		p("  %s│%s    %s$ %s%s\n", gray, reset, dim, ex, reset)
	}
}

func printBanner(deps *deps.Deps) {
	p := deps.Std.Printf

	titleLine := fmt.Sprintf("%s  %s", config.ProjectName, config.Version)
	innerW := len(titleLine) + 4
	if innerW < 42 {
		innerW = 42
	}

	p("\n")
	p("  %s╭%s╮%s\n", cyan, strings.Repeat("─", innerW), reset)
	p("  %s│%s  %s%s%s%s%s│%s\n",
		cyan, reset, bold+white, titleLine, reset,
		strings.Repeat(" ", innerW-2-len(titleLine)), cyan, reset,
	)
	p("  %s╰%s╯%s\n", cyan, strings.Repeat("─", innerW), reset)
	p("\n")
}

func printSection(p func(string, ...any) (int, error), title string) {
	p("  %s%s%s\n", bold+cyan, title, reset)
	p("  %s│%s\n", gray, reset)
}

func typeLabel(kind string) string {
	switch kind {
	case "int":
		return "int"
	case "float":
		return "float"
	case "boolean":
		return "bool"
	default:
		return "string"
	}
}
