package set_path

import (
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/api"
)

// NewCommand builds this command's declaration — the whole of what its
// entries.yaml says — and closes CommandHandler over the sandbox as the
// handler behind it. It is called once, by sandbox/internal/generated/cli/new.go, and
// what it returns is one entry of Cli.Commands: the declaration alone, which
// the dispatch copies with api.BindCommand before binding a command line onto
// it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewCommand(sandbox *api.Sandbox) api.Command {
	command := api.NewCommand()

	command.Name = "set_path"
	command.Identifiers = []string{"set-path"}
	command.Category = "Server System"
	command.Help = "Rewrite one entry of a route's paths"
	command.LongDescription = "Rewrites one entry of the route's paths in place and runs build. It is add-path applied to a declaration that already exists: the keys given are written over the ones there, --clear takes one off, and the result goes through the same constructor."
	command.Examples = []string{"set-path tenant --route create-user --end 2", "set-path Route --route logger --trigger-type prefix"}
	command.Hidden = false

	command.Flags = []api.CommandFlag{
		{
			Id:          "route",
			Type:        "string",
			Required:    true,
			Array:       false,
			Description: "the route (identifier or package name) that declares the path",
			Examples:    []string{"set-path tenant --route create-user --end 2"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--route"},
		},
		{
			Id:          "rename",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the id the path takes on",
			Examples:    []string{"set-path tenant --route create-user --rename Org"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--rename"},
		},
		{
			Id:          "start",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the new index of the first segment",
			Examples:    []string{"set-path tenant --route create-user --start 2"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--start"},
		},
		{
			Id:          "end",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the new index of the last segment, -1 for the last one",
			Examples:    []string{"set-path tenant --route create-user --end -1"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--end"},
		},
		{
			Id:          "type",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the new type: string, integer, number or uuid",
			Examples:    []string{"set-path article --route get-article --type integer"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--type"},
		},
		{
			Id:          "trigger",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the new value the slice has to read as",
			Examples:    []string{"set-path Route --route create-user --trigger /users"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--trigger"},
		},
		{
			Id:          "trigger-type",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the new comparison: equal, prefix, text-prefix, suffix or regex — or starts-with, ends-with, exact, matches",
			Examples:    []string{"set-path Route --route logger --trigger-type prefix"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--trigger-type"},
		},
		{
			Id:          "trigger-negate",
			Type:        "boolean",
			Required:    false,
			Array:       false,
			Description: "invert the trigger (take it off with --clear trigger-negate)",
			Examples:    []string{"set-path NotLogin --route admin-guard --trigger-negate"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--trigger-negate"},
		},
		{
			Id:          "trigger-ignore-case",
			Type:        "boolean",
			Required:    false,
			Array:       false,
			Description: "compare the trigger without regard to case (take it off with --clear trigger-ignore-case)",
			Examples:    []string{"set-path Route --route admin --trigger-ignore-case"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--trigger-ignore-case"},
		},
		{
			Id:          "description",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the new help text",
			Examples:    []string{"set-path tenant --route create-user --description 'the tenant id'"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--description"},
		},
		{
			Id:          "clear",
			Type:        "string",
			Required:    false,
			Array:       true,
			Description: "a key to take off: trigger, trigger-negate, trigger-ignore-case, type or description (repeatable)",
			Examples:    []string{"set-path tenant --route create-user --clear trigger"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--clear"},
		},
		{
			Id:          "path",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the dir holding the project (defaults to the current directory)",
			Examples:    []string{"set-path tenant --route create-user --end 2 --path ./my-project"},
			Default:     ".",
			HasDefault:  true,
			Identifiers: []string{"--path"},
		},
		{
			Id:          "quiet",
			Type:        "boolean",
			Required:    false,
			Array:       false,
			Description: "Quiets the cli output",
			Examples:    []string{},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--quiet", "-q"},
		},
	}

	command.Args = []api.CommandArg{
		{
			Id:          "id",
			Type:        "string",
			Required:    true,
			Array:       false,
			Description: "the id of the path to rewrite",
			Examples:    []string{"set-path tenant --route create-user --end 2"},
			Default:     "",
			HasDefault:  false,
		},
	}

	command.Handler = func(bound *api.Command) int {
		return CommandHandler(sandbox, bound)
	}

	return *command
}
