package remove_doc

import (
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/api"
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/internal/smartio"
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/internal/utils"
)

// RemoveDocInternal deletes every file under the doc's directory plus the
// directory itself, sub-docs and assets included. The generated docs/Index/
// is not a doc and is refused: build rewrites it whole. So is a doc one of the
// enabled doc groups renders, since the next build would put it back.
func RemoveDocInternal(sandbox *api.Sandbox, io *smartio.SmartIO, name string) error {
	if err := utils.ValidateDocName(sandbox, name); err != nil {
		return err
	}

	dir := utils.DocDir(sandbox, name)
	if !io.IsDir(dir) {
		return sandbox.Deps.Std.Errorf("doc %s not found", dir)
	}
	if err := refuseGenerated(sandbox, io, dir); err != nil {
		return err
	}

	sandbox.Deps.Std.Log("remove-doc removing %s \n", dir)

	for _, file := range io.ListAllRecursively(dir) {
		io.RemoveDir(file)
	}
	io.RemoveDir(dir)
	return nil
}

// refuseGenerated fails when dir is — or lies inside — a doc an enabled doc
// asset group renders on every build.
func refuseGenerated(sandbox *api.Sandbox, io *smartio.SmartIO, dir string) error {
	extensions_conf, err := utils.LoadExtensionsConf(sandbox, io)
	if err != nil {
		return err
	}
	for _, group := range utils.DocGroups(sandbox, extensions_conf) {
		files, err := sandbox.Deps.Embeddeps.ListFilesRecursively(group)
		if err != nil {
			return err
		}
		for _, file := range files {
			if sandbox.Deps.Stringsdeps.HasPrefix(file, dir+"/") {
				return sandbox.Deps.Std.Errorf("%s is generated by every build (asset group %s), so removing it would not last: turn the %s extension off to stop generating it", dir, group, utils.ExtensionDoc)
			}
		}
	}
	return nil
}
