package add_body_field

// Entries is generated by `agnos build` from this command's entries.yaml.
// It is the typed view of the parsed command line handed to CommandHandler.
// Do not edit by hand — put your logic in handler.go.
// Fields follow entries.yaml: the flags first, then the positional args, each
// in the order it is declared there.
type Entries struct {
	Route                  string
	Type                   string
	Required               bool
	Array                  bool
	Min                    string
	Max                    string
	ExclusiveMin           string
	ExclusiveMax           string
	Format                 string
	Pattern                string
	Enum                   []string
	Const                  string
	Nullable               bool
	MinItems               string
	MaxItems               string
	UniqueItems            bool
	AdditionalProperties   bool
	NoAdditionalProperties bool
	Path                   string
	Quiet                  bool
	Name                   string
}
