// Code generated by agnos. DO NOT EDIT.

package set_command

import (
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/api"
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/internal/commandprops"
)

// NewCommand builds this command's declaration — a 1:1 image of its
// command.yaml — on the empty base of Deps.OpinionatedAgnosCli.NewCommand, and
// closes Handle over the sandbox as the handler behind it. It is
// called once by sandbox/internal/cli/generated.new.go, and what it returns
// is one entry of Cli.Commands: the declaration alone, which the lib's dispatch
// copies before binding a command line onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewCommand(sandbox *api.Sandbox) *api.Command {
	self := sandbox.Deps.OpinionatedAgnosCli.NewCommand(sandbox.Deps.ArgvDeps)

	self.Name = "set_command"
	self.Identifiers = []string{"set-command"}
	self.Priority = 100
	self.Segments = 0
	self.Strict = true
	self.Pattern = "set-command <Name>"
	self.Category = "Cli"
	self.Summary = "Rewrite the command-level keys of a command's command.yaml"
	self.Description = "Overwrites summary, category, description, priority, segments, strict and hidden on one command, appends further verbs (--identifier) and examples, and runs build. Empty options leave the current value alone; --before and --after place the command one rung from another; --clear takes a key off."
	self.Examples = []string{"set-command exec --identifier run --example 'exec file.txt'", "set-command exec --priority 50", "set-command logger --loose"}
	self.Hidden = false

	self.Args = []api.CommandArg{
		{
			Id:          "Verb",
			Start:       0,
			End:         0,
			Type:        api.ArgString,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Description: "",
			Trigger:     api.Trigger{Set: true, Type: api.TriggerEqual, Value: "set-command", Negate: false, IgnoreCase: false},
		},
		{
			Id:          "Name",
			Start:       1,
			End:         1,
			Type:        api.ArgString,
			Required:    true,
			Default:     "",
			HasDefault:  false,
			Description: "the command to update (a verb or its package name)",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
		},
	}

	self.Flags = []api.CommandFlag{
		{
			Id:          "Summary",
			Keys:        []string{"--summary"},
			Type:        api.FlagString,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "new one-line help text",
		},
		{
			Id:          "Category",
			Keys:        []string{"--category"},
			Type:        api.FlagString,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "new category the command is grouped under in help output",
		},
		{
			Id:          "Description",
			Keys:        []string{"--description"},
			Type:        api.FlagString,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "new long description shown by help <command>",
		},
		{
			Id:          "Identifier",
			Keys:        []string{"--identifier", "-i"},
			Type:        api.FlagStringArray,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "an extra verb the command answers to (repeatable)",
		},
		{
			Id:          "Example",
			Keys:        []string{"--example", "-e"},
			Type:        api.FlagStringArray,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "an extra usage example (repeatable)",
		},
		{
			Id:          "Hidden",
			Keys:        []string{"--hidden"},
			Type:        api.FlagBoolean,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "hide the command from help listings",
		},
		{
			Id:          "Visible",
			Keys:        []string{"--visible"},
			Type:        api.FlagBoolean,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "show the command in help listings again",
		},
		{
			Id:          "Priority",
			Keys:        []string{"--priority"},
			Type:        api.FlagInteger,
			Required:    false,
			Default:     "-1",
			HasDefault:  true,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "the rung this command runs on, lowest first",
		},
		{
			Id:          "Before",
			Keys:        []string{"--before"},
			Type:        api.FlagString,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "land one rung below the command named (excludes --priority)",
		},
		{
			Id:          "After",
			Keys:        []string{"--after"},
			Type:        api.FlagString,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "land one rung above the command named (excludes --priority)",
		},
		{
			Id:          "Segments",
			Keys:        []string{"--segments"},
			Type:        api.FlagInteger,
			Required:    false,
			Default:     "-1",
			HasDefault:  true,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "how many segments the command line has to have for the command to run",
		},
		{
			Id:          "Strict",
			Keys:        []string{"--strict"},
			Type:        api.FlagBoolean,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "every token of the line has to be read by the command or a middleware in front of it",
		},
		{
			Id:          "Loose",
			Keys:        []string{"--loose"},
			Type:        api.FlagBoolean,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "turn the command into a middleware: tokens it does not read are the next command's to declare",
		},
		{
			Id:          "Clear",
			Keys:        []string{"--clear"},
			Type:        api.FlagStringArray,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "a key to take off: segments, or examples before --example lists them again (repeatable)",
		},
	}

	self.Handle = func(props *commandprops.CommandProps, input *Input, response *api.CommandResponse) error {
		return Handle(sandbox, props, input, response)
	}

	return self
}
