package database_purge

import (
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/api"
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/internal/generated/cli/command"
)

// NewCommand builds this command's declaration — a 1:1 image of its
// command.yaml — on the generic base of sandbox/internal/generated/cli/command,
// and closes InternalPureHandler over the sandbox as the handler behind it. It
// is called once by sandbox/internal/generated/cli/cli/new.go, and what it
// returns is one entry of Cli.Commands: the declaration alone, which the
// dispatch copies with api.BindCommand before binding a command line onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in InternalPureHandler.go.
func NewCommand(sandbox *api.Sandbox) *api.Command {
	self := command.NewCommand(sandbox)

	self.Name = "database_purge"
	self.Identifiers = []string{"database-purge"}
	self.Priority = 100
	self.Segments = 0
	self.Strict = true
	self.Pattern = "database-purge"
	self.Category = "Database System"
	self.Help = "Remove the database layer and every declared database"
	self.LongDescription = "Removes everything the database asset groups installed, sandbox/internal/databases and docs/Databases whole, and writes sandbox-database: false. The store contract is left in place: database-init installed it, but a dep, once there, is the project's — 'agnos remove-dep database' is what takes it away."
	self.Examples = []string{"database-purge", "database-purge --path ./my-project"}
	self.Hidden = false

	self.Args = []api.CommandArg{
		{
			Id:          "Command",
			Start:       0,
			End:         0,
			Type:        api.StringArg,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Description: "",
			Trigger:     api.Trigger{Exist: true, Type: api.EqualTrigger, Value: "database-purge", Negate: false, IgnoreCase: false},
		},
	}

	self.Flags = []api.CommandFlag{}

	self.InternalPureHandler = func(props *api.CommandProps, entries *Entries, response *api.CommandResponse) error {
		return InternalPureHandler(sandbox, props, entries, response)
	}

	return self
}
