package add_route

import (
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/api"
)

// NewCommand builds this command's declaration — the whole of what its
// entries.yaml says — and closes CommandHandler over the sandbox as the
// handler behind it. It is called once, by sandbox/internal/generated/cli/new.go, and
// what it returns is one entry of Cli.Commands: the declaration alone, which
// the dispatch copies with api.BindCommand before binding a command line onto
// it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewCommand(sandbox *api.Sandbox) api.Command {
	command := api.NewCommand()

	command.Name = "add_route"
	command.Identifiers = []string{"add-route"}
	command.Category = "Server System"
	command.Help = "Declare a new http route"
	command.LongDescription = "Writes sandbox/internal/routeslist/<name>/route.yaml and a stub InternalPureHandler.go, then runs build so the route's new.go (the api.Route that lands in Server.Routes) and entries.go (the Entries its handler is handed) are generated. The paths come from --pattern, or from one path, Route, reading the whole request path against --trigger. A --middleware declines by default and sits in front of the routes on the default rung; --before and --after place a route next to another one. priority and response-type are always written."
	command.Examples = []string{"add-route create-user --trigger /users --method POST --help \"Create a user\" --category Users", "add-route get-article --pattern '/articles/{article:integer}'", "add-route admin-guard --middleware --trigger /admin"}
	command.Hidden = false

	command.Flags = []api.CommandFlag{
		{
			Id:          "trigger",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "what the whole request path is compared against; an equal, prefix or text-prefix trigger is normalized to start with / (defaults to /<name>, or / for a --middleware)",
			Examples:    []string{"--trigger /users"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--trigger"},
		},
		{
			Id:          "trigger-type",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "how the trigger is compared: equal, prefix (the value or anything under it, segment by segment), text-prefix, suffix or regex — or starts-with, ends-with, exact, matches (defaults to equal, or prefix for a --middleware)",
			Examples:    []string{"add-route admin --trigger /admin --trigger-type prefix"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--trigger-type"},
		},
		{
			Id:          "trigger-negate",
			Type:        "boolean",
			Required:    false,
			Array:       false,
			Description: "invert the trigger: the route runs for every path that does not match it",
			Examples:    []string{"add-route not-api --trigger /api --trigger-type prefix --trigger-negate"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--trigger-negate"},
		},
		{
			Id:          "trigger-ignore-case",
			Type:        "boolean",
			Required:    false,
			Array:       false,
			Description: "compare the trigger without regard to case",
			Examples:    []string{"add-route admin --trigger /admin --trigger-type prefix --trigger-ignore-case"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--trigger-ignore-case"},
		},
		{
			Id:          "pattern",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the url shape the route answers, compiled into its paths: literal segments, {name}, {name:integer|number|uuid} and a last {*rest}; without {*rest} the segment count is fixed (excludes --trigger and --trigger-type)",
			Examples:    []string{"add-route get-article --pattern '/articles/{article:integer}'"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--pattern"},
		},
		{
			Id:          "method",
			Type:        "string",
			Required:    false,
			Array:       true,
			Description: "an http method the route answers: GET, POST, PUT, PATCH, DELETE, HEAD, OPTIONS, or ANY for every one (repeatable; defaults to GET, or ANY for a --middleware)",
			Examples:    []string{"--method POST"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--method", "-m"},
		},
		{
			Id:          "middleware",
			Type:        "boolean",
			Required:    false,
			Array:       false,
			Description: "declare a middleware: ANY method, a prefix trigger on / unless --trigger says otherwise, priority 10, and a stub handler that hands the request on",
			Examples:    []string{"add-route admin-guard --middleware --trigger /admin"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--middleware"},
		},
		{
			Id:          "priority",
			Type:        "int",
			Required:    false,
			Array:       false,
			Description: "the rung this route runs on when several match one request, lowest first; a route that answers nothing hands the request on (defaults to 100, or 10 for a --middleware)",
			Examples:    []string{"add-route logger --middleware --priority 0"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--priority"},
		},
		{
			Id:          "before",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "land one rung below the route named, so it runs first (excludes --priority)",
			Examples:    []string{"add-route admin-guard --middleware --trigger /admin --before admin"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--before"},
		},
		{
			Id:          "after",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "land one rung above the route named, so it runs next (excludes --priority)",
			Examples:    []string{"add-route fallback --trigger / --trigger-type prefix --after admin"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--after"},
		},
		{
			Id:          "phase",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "when the route runs: before (the chain, the default) or after, once the request has been answered and without being able to change the answer",
			Examples:    []string{"add-route access-log --middleware --phase after"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--phase"},
		},
		{
			Id:          "response-type",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the Content-Type every response of the route carries (defaults to application/json, or text/plain for a --middleware)",
			Examples:    []string{"--response-type text/plain"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--response-type"},
		},
		{
			Id:          "help",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "one-line description of the route",
			Examples:    []string{"add-route create-user --help 'Create a user'"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--help"},
		},
		{
			Id:          "category",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the heading the route is listed under in docs/Routes (defaults to Routes, or Middleware for a --middleware)",
			Examples:    []string{"add-route create-user --category Users"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--category"},
		},
		{
			Id:          "path",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the dir holding the project (defaults to the current directory)",
			Examples:    []string{"add-route --path ./my-project"},
			Default:     ".",
			HasDefault:  true,
			Identifiers: []string{"--path"},
		},
		{
			Id:          "quiet",
			Type:        "boolean",
			Required:    false,
			Array:       false,
			Description: "Quiets the cli output",
			Examples:    []string{},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--quiet", "-q"},
		},
	}

	command.Args = []api.CommandArg{
		{
			Id:          "name",
			Type:        "string",
			Required:    true,
			Array:       false,
			Description: "the route name (becomes the directory sandbox/internal/routeslist/<name> and its Go package)",
			Examples:    []string{"add-route create-user"},
			Default:     "",
			HasDefault:  false,
		},
	}

	command.Handler = func(bound *api.Command) int {
		return CommandHandler(sandbox, bound)
	}

	return *command
}
