package add_route

import (
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/api"
)

// NewCommand builds this command's declaration — the whole of what its
// entries.yaml says — and closes CommandHandler over the sandbox as the
// handler behind it. It is called once, by sandbox/internal/cli/new.go, and
// what it returns is one entry of Cli.Commands: the declaration alone, which
// the dispatch copies with api.BindCommand before binding a command line onto
// it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewCommand(sandbox *api.Sandbox) api.Command {
	command := api.NewCommand()

	command.Name = "add_route"
	command.Identifiers = []string{"add-route"}
	command.Category = "Server System"
	command.Help = "Declare a new http route"
	command.LongDescription = "Writes sandbox/internal/routes/<name>/route.yaml and a stub handler.go, then runs build so the route's new.go — the api.Route that lands in Server.Routes — is generated. The trigger is normalized to start with /, and defaults to /<name>."
	command.Examples = []string{"add-route create-user --trigger /users --method POST --help \"Create a user\" --category Users"}
	command.Hidden = false

	command.Flags = []api.CommandFlag{
		{
			Id:          "trigger",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the first literal segment of the path, always starting with / (defaults to /<name>)",
			Examples:    []string{"--trigger /users"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--trigger"},
		},
		{
			Id:          "method",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the http method the route answers: GET, POST, PUT, PATCH, DELETE, HEAD or OPTIONS",
			Examples:    []string{"--method POST"},
			Default:     "GET",
			HasDefault:  true,
			Identifiers: []string{"--method", "-m"},
		},
		{
			Id:          "help",
			Type:        "string",
			Required:    true,
			Array:       false,
			Description: "one-line description of the route",
			Examples:    []string{"--help \"Create a user\""},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--help"},
		},
		{
			Id:          "category",
			Type:        "string",
			Required:    true,
			Array:       false,
			Description: "the heading the route is listed under in docs/Routes",
			Examples:    []string{"--category Users"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--category"},
		},
		{
			Id:          "path",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the dir holding the project (defaults to the current directory)",
			Examples:    []string{"add-route --path ./my-project"},
			Default:     ".",
			HasDefault:  true,
			Identifiers: []string{"--path"},
		},
		{
			Id:          "quiet",
			Type:        "boolean",
			Required:    false,
			Array:       false,
			Description: "Quiets the cli output",
			Examples:    []string{},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--quiet", "-q"},
		},
		{
			Id:          "priority",
			Type:        "int",
			Required:    false,
			Array:       false,
			Description: "the rung this route runs on when several match one request: lowest first, and a route that writes no status hands the request on",
			Examples:    []string{"add-route logger --trigger / --starts-with --priority 0 --help 'logs every request' --category Server"},
			Default:     "0",
			HasDefault:  true,
			Identifiers: []string{"--priority"},
		},
		{
			Id:          "starts-with",
			Type:        "boolean",
			Required:    false,
			Array:       false,
			Description: "make the trigger a prefix, so the route answers every path beginning with it rather than that one path",
			Examples:    []string{"add-route logger --trigger / --starts-with --help 'logs every request' --category Server"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--starts-with"},
		},
	}

	command.Args = []api.CommandArg{
		{
			Id:          "name",
			Type:        "string",
			Required:    true,
			Array:       false,
			Description: "the route name (becomes the directory sandbox/internal/routes/<name> and its Go package)",
			Examples:    []string{"add-route create-user"},
			Default:     "",
			HasDefault:  false,
		},
	}

	command.Handler = func(bound *api.Command) int {
		return CommandHandler(sandbox, bound)
	}

	return *command
}
