package explain_route

import (
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/api"
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/internal/commandprops"
)

// NewCommand builds this command's declaration — a 1:1 image of its
// command.yaml — on the empty base of Deps.OpinionatedAgnosCli.NewCommand, and
// closes Handle over the sandbox as the handler behind it. It is
// called once by sandbox/internal/generated/cli/new.go, and what it returns
// is one entry of Cli.Commands: the declaration alone, which the lib's dispatch
// copies before binding a command line onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewCommand(sandbox *api.Sandbox) *api.Command {
	self := sandbox.Deps.OpinionatedAgnosCli.NewCommand(sandbox.Deps.ArgvDeps)

	self.Name = "explain_route"
	self.Identifiers = []string{"explain-route"}
	self.Priority = 100
	self.Segments = 0
	self.Strict = true
	self.Pattern = "explain-route <Method> <RequestPath>"
	self.Category = "Server"
	self.Summary = "Show which routes one request reaches, without a server"
	self.Description = "Walks the chain the way the generated dispatch does and prints, route by route, whether it runs for the request or why it is skipped — the segment count, a path that is missing, will not convert or fails its trigger, the method, a parameter trigger — and a 400 its binding would answer. What a handler does once it runs is its own code, so the last line says what the request ends on when none answers. Writes nothing."
	self.Examples = []string{"explain-route GET /admin/users --header 'x-token=abc'"}
	self.Hidden = false

	self.Args = []api.CommandArg{
		{
			Id:          "Verb",
			Start:       0,
			End:         0,
			Type:        api.ArgString,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Description: "",
			Trigger:     api.Trigger{Set: true, Type: api.TriggerEqual, Value: "explain-route", Negate: false, IgnoreCase: false},
		},
		{
			Id:          "Method",
			Start:       1,
			End:         1,
			Type:        api.ArgString,
			Required:    true,
			Default:     "",
			HasDefault:  false,
			Description: "the http method of the request",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
		},
		{
			Id:          "RequestPath",
			Start:       2,
			End:         2,
			Type:        api.ArgString,
			Required:    true,
			Default:     "",
			HasDefault:  false,
			Description: "the request path, query string included",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
		},
	}

	self.Flags = []api.CommandFlag{
		{
			Id:          "Header",
			Keys:        []string{"--header"},
			Type:        api.FlagStringArray,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "a header the request carries, as key=value (repeatable)",
		},
		{
			Id:          "Cookie",
			Keys:        []string{"--cookie"},
			Type:        api.FlagStringArray,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "a cookie the request carries, as key=value (repeatable)",
		},
	}

	self.Handle = func(props *commandprops.CommandProps, input *Input, response *api.CommandResponse) error {
		return Handle(sandbox, props, input, response)
	}

	return self
}
