package server_init

import (
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/api"
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/internal/commandprops"
)

// NewCommand builds this command's declaration — a 1:1 image of its
// command.yaml — on the empty base of Deps.OpinionatedAgnosCli.NewCommand, and
// closes Handle over the sandbox as the handler behind it. It is
// called once by sandbox/internal/generated/cli/new.go, and what it returns
// is one entry of Cli.Commands: the declaration alone, which the lib's dispatch
// copies before binding a command line onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewCommand(sandbox *api.Sandbox) *api.Command {
	self := sandbox.Deps.OpinionatedAgnosCli.NewCommand(sandbox.Deps.ArgvDeps)

	self.Name = "server_init"
	self.Identifiers = []string{"server-init"}
	self.Priority = 100
	self.Segments = 0
	self.Strict = true
	self.Pattern = "server-init"
	self.Category = "Server"
	self.Summary = "Add the http server layer to the project"
	self.Description = "Installs the deps the server layer needs — the OpinionatedAgnosServer lib, its request chain, among them — renders sandbox/internal/server and the built-in health route, and writes the start-server command. A project with no cli layer is given one first: a server needs a command that starts it."
	self.Examples = []string{"server-init", "server-init --path ./my-project"}
	self.Hidden = false

	self.Args = []api.CommandArg{
		{
			Id:          "Verb",
			Start:       0,
			End:         0,
			Type:        api.ArgString,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Description: "",
			Trigger:     api.Trigger{Set: true, Type: api.TriggerEqual, Value: "server-init", Negate: false, IgnoreCase: false},
		},
	}

	self.Flags = []api.CommandFlag{}

	self.Handle = func(props *commandprops.CommandProps, input *Input, response *api.CommandResponse) error {
		return Handle(sandbox, props, input, response)
	}

	return self
}
