package front_init

import (
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/api"
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/internal/commandprops"
)

// NewCommand builds this command's declaration — a 1:1 image of its
// command.yaml — on the empty base of Deps.OpinatedAgnosCli.NewCommand, and
// closes InternalPureHandler over the sandbox as the handler behind it. It is
// called once by sandbox/internal/generated/cli/cli/new.go, and what it returns
// is one entry of Cli.Commands: the declaration alone, which the lib's dispatch
// copies before binding a command line onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in InternalPureHandler.go.
func NewCommand(sandbox *api.Sandbox) *api.Command {
	self := sandbox.Deps.OpinatedAgnosCli.NewCommand(sandbox.Deps.Argvdeps)

	self.Name = "front_init"
	self.Identifiers = []string{"front-init"}
	self.Priority = 100
	self.Segments = 0
	self.Strict = true
	self.Pattern = "front-init"
	self.Category = "Front System"
	self.Help = "Add the html front layer to the project"
	self.LongDescription = "Installs the deps the front layer needs — the OpinatedAgnosFront lib, its file layer, among them — and writes, once, the frontend route serving every file of assets/frontend and that tree's index.html and 404.html. A project with no server layer is given one first: the front is answered over http."
	self.Examples = []string{"front-init", "front-init --path ./my-project"}
	self.Hidden = false

	self.Args = []api.CommandArg{
		{
			Id:          "Command",
			Start:       0,
			End:         0,
			Type:        api.StringArg,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Description: "",
			Trigger:     api.Trigger{Exist: true, Type: api.EqualTrigger, Value: "front-init", Negate: false, IgnoreCase: false},
		},
	}

	self.Flags = []api.CommandFlag{}

	self.InternalPureHandler = func(props *commandprops.CommandProps, entries *Entries, response *api.CommandResponse) error {
		return InternalPureHandler(sandbox, props, entries, response)
	}

	return self
}
