package server

import (
	api "{{.Module}}/sandbox/api"
{{- range .Routes}}
	routes_{{.Name}} "{{$.Module}}/sandbox/internal/routes/{{.Name}}"
{{- end}}
)

// NewServer builds the http surface of the sandbox: Routes, one entry per
// sandbox/internal/routes/<name>/ built by that package's generated NewRoute —
// in match order, the route fixing the most literal segments first — and Serve,
// the dispatch that reads a request against them. Generated by
// `{{.GeneratorName}} build` — do not edit by hand.
func NewServer(sandbox *api.Sandbox) api.Server {
	server := api.Server{}

	server.Routes = []api.Route{
{{- range .Routes}}
		routes_{{.Name}}.NewRoute(sandbox),
{{- end}}
	}

	server.Serve = func(props api.ServeProps) error {
		return ServerMain(sandbox, props)
	}

	return server
}
