package server

import (
	"{{.Module}}/sandbox/api"
	"{{.Module}}/sandbox/deps"
	"{{.Module}}/sandbox/deps/serverdeps"
	"{{.Module}}/sandbox/internal/routeio"
{{- range .Routes}}
	routes_{{.Name}} "{{$.Module}}/sandbox/internal/routes/{{.Name}}"
{{- end}}
)

// ServerMain is generated by `agnos build` from every
// sandbox/internal/routes/<name>/route.yaml. It opens the port through
// deps.Serverdeps — which routes nothing — and hands every request to
// dispatch, whatever its method or path.
func ServerMain(deps *deps.Deps, props api.ServeProps) error {
	server := deps.Serverdeps.NewServer(serverdeps.ServerProps{
		Addr:           props.Addr,
		ReadTimeoutMs:  props.ReadTimeoutMs,
		WriteTimeoutMs: props.WriteTimeoutMs,
		Handler: func(request serverdeps.Request, response serverdeps.Response) {
			dispatch(deps, request, response)
		},
	})

	deps.Std.Log("server listening on %s \n", props.Addr)
	return server.Listen()
}

// dispatch is the whole routing layer: it slices the path into segments and
// tests every declared route against them, in the order the collector put
// them — the route fixing the most literal segments first, so a route on "/"
// can never swallow one on "/home".
//
// Everything but the body is settled here: a path nothing matches is 404, a
// path matched under another method is 405, and a field that will not bind is
// 400. A RouteHandler never decides any of those.
func dispatch(deps *deps.Deps, request serverdeps.Request, response serverdeps.Response) {
	defer recoverRoute(deps, response)
{{- if .Routes}}

	segments := splitPath(deps, request.GetPath())
	method := request.GetMethod()
	path_matched := false
{{- range .Routes}}

	if match{{.GoName}}(segments) {
		path_matched = true
		if method == "{{.Method}}" {
			handle{{.GoName}}(deps, request, response, segments)
			return
		}
	}
{{- end}}

	if path_matched {
		routeio.WriteError(deps, response, api.StatusMethodNotAllowed, "", "method not allowed")
		return
	}
{{- end}}

	routeio.WriteError(deps, response, api.StatusNotFound, "", "route not found")
}

// ─── request helpers ────────────────────────────────────────────────────────
//
// Every handle function below reads the request through these, so one spelling
// of every binding error is emitted for the whole server.

// splitPath slices a raw request path into the segments a route is matched
// against, dropping the empty ones the leading and trailing slashes leave
// behind. The root path yields no segment at all.
func splitPath(deps *deps.Deps, path string) []string {
	var segments []string
	for _, segment := range deps.Stringsdeps.Split(path, "/") {
		if segment != "" {
			segments = append(segments, segment)
		}
	}
	return segments
}

// recoverRoute turns a panicking handler into one 500, so a single bad route
// cannot take the process down with it.
func recoverRoute(deps *deps.Deps, response serverdeps.Response) {
	failure := recover()
	if failure == nil {
		return
	}
	deps.Std.Error("route panicked: %v\n", failure)
	routeio.WriteError(deps, response, api.StatusFailure, "", "internal error")
}

// parseStringValue is the string arm of the parse* family. Every raw request
// value is already a string, so it only exists to keep the generated dispatch
// uniform across the four field types.
func parseStringValue(deps *deps.Deps, response serverdeps.Response, subject string, name string, raw string) (string, bool) {
	return raw, true
}

// parseIntValue converts a raw request value to an int, answering 400 in the
// server's own words rather than the conversion library's.
func parseIntValue(deps *deps.Deps, response serverdeps.Response, subject string, name string, raw string) (int, bool) {
	value, err := deps.Stringsdeps.Atoi(raw)
	if err != nil {
		routeio.WriteError(deps, response, api.StatusBadRequest, name,
			deps.Std.Sprintf("%s '%s' is not a valid integer", subject, name))
		return 0, false
	}
	return value, true
}

// parseFloatValue converts a raw request value to a float64, answering 400 in
// the server's own words rather than the conversion library's.
func parseFloatValue(deps *deps.Deps, response serverdeps.Response, subject string, name string, raw string) (float64, bool) {
	value, err := deps.Stringsdeps.ParseFloat(raw, 64)
	if err != nil {
		routeio.WriteError(deps, response, api.StatusBadRequest, name,
			deps.Std.Sprintf("%s '%s' is not a valid number", subject, name))
		return 0, false
	}
	return value, true
}

// parseBoolValue converts a raw request value to a bool. Only the four
// spellings below are accepted: anything else is a typo the caller should hear
// about rather than have read as false.
func parseBoolValue(deps *deps.Deps, response serverdeps.Response, subject string, name string, raw string) (bool, bool) {
	switch deps.Stringsdeps.ToLower(raw) {
	case "true", "1":
		return true, true
	case "false", "0":
		return false, true
	}
	routeio.WriteError(deps, response, api.StatusBadRequest, name,
		deps.Std.Sprintf("%s '%s' must be true or false", subject, name))
	return false, false
}
{{range .Routes}}{{$route := .}}
// match{{.GoName}} reports whether a request path binds to {{.Pattern}}: the
// segment count has to be {{if .HasRest}}above the {{.SegmentCount}} it fixes, since its last
// capture takes every segment left{{else}}exact{{end}}, every literal segment has to be the one
// declared, and a capture takes whatever sits in its place.
func match{{.GoName}}(segments []string) bool {
	if len(segments) {{.ArityOp}} {{.SegmentCount}} {
		return false
	}
{{- range .MatchParts}}
{{- if not .IsCapture}}
	if segments[{{.Index}}] != "{{.Literal}}" {
		return false
	}
{{- end}}
{{- end}}
	return true
}

// handle{{.GoName}} binds everything but the body of a {{.Method}} {{.Pattern}}
// request — the captured segments, the declared headers and query parameters,
// the content type and the declared length — and then calls the route's
// handler. Nothing is read from the socket here: the body is the handler's to
// ask for, through Entries.ReadBody.
func handle{{.GoName}}(deps *deps.Deps, request serverdeps.Request, response serverdeps.Response, segments []string) {
	entries := routes_{{.Name}}.Entries{}
	entries.Request = request
{{- range .Bindings}}{{$binding := .}}
{{- if .IsRest}}

	for _, raw := range segments[{{.RestIndex}}:] {
		value, ok := {{.ParseFunc}}(deps, response, "{{.Subject}}", "{{.Key}}", raw)
		if !ok {
			return
		}
		entries.{{.GoField}} = append(entries.{{.GoField}}, value)
	}
{{- else if .IsArray}}

	for _, raw := range request.GetQueryAll("{{.Key}}") {
		value, ok := {{.ParseFunc}}(deps, response, "{{.Subject}}", "{{.Key}}", raw)
		if !ok {
			return
		}
		entries.{{.GoField}} = append(entries.{{.GoField}}, value)
	}
{{- if .Required}}
	if len(entries.{{.GoField}}) == 0 {
		routeio.WriteError(deps, response, api.StatusBadRequest, "{{.Key}}", "required {{.Subject}} '{{.Key}}' is missing")
		return
	}
{{- end}}
{{- else}}
{{- if .NeedsFound}}

	{{.GoField}}_found := false
{{- end}}
{{- range .Sources}}
{{- if eq .Kind "path"}}
	{
		value, ok := {{$binding.ParseFunc}}(deps, response, "{{$binding.Subject}}", "{{$binding.Key}}", segments[{{.Index}}])
		if !ok {
			return
		}
		entries.{{$binding.GoField}} = value
{{- if $binding.NeedsFound}}
		{{$binding.GoField}}_found = true
{{- end}}
	}
{{- else}}
	if raw := {{.Getter}}; raw != ""{{if $binding.MultiSource}} && !{{$binding.GoField}}_found{{end}} {
		value, ok := {{$binding.ParseFunc}}(deps, response, "{{$binding.Subject}}", "{{.Key}}", raw)
		if !ok {
			return
		}
		entries.{{$binding.GoField}} = value
{{- if $binding.NeedsFound}}
		{{$binding.GoField}}_found = true
{{- end}}
	}
{{- end}}
{{- end}}
{{- if .NeedsFallback}}
	if !{{.GoField}}_found {
{{- if .Required}}
		routeio.WriteError(deps, response, api.StatusBadRequest, "{{.Key}}", "required {{.Subject}} '{{.Key}}' is missing")
		return
{{- else}}
		entries.{{.GoField}} = {{.DefaultLiteral}}
{{- end}}
	}
{{- end}}
{{- if .RangeCheck}}
{{.RangeCheck}}
{{- end}}
{{- end}}
{{- end}}
{{- if .HasBody}}
{{- if .Body.ContentType}}

	if content_type := request.GetHeader("Content-Type"); content_type != "" && !deps.Stringsdeps.HasPrefix(content_type, "{{.Body.ContentType}}") {
		routeio.WriteError(deps, response, api.StatusUnsupportedMedia, "", "this route accepts a {{.Body.ContentType}} body")
		return
	}
{{- end}}

	if raw := request.GetHeader("Content-Length"); raw != "" {
		declared, err := deps.Stringsdeps.Atoi(raw)
		if err == nil && declared > {{.Body.MaxBytes}} {
			routeio.WriteError(deps, response, api.StatusPayloadTooLarge, "", "the request body is larger than {{.Body.MaxBytesText}} bytes")
			return
		}
	}
{{- end}}

	if status := routes_{{.Name}}.RouteHandler(deps, &entries, response); status == 0 {
		routeio.WriteError(deps, response, api.StatusFailure, "", "the route handler returned no status")
	}
}
{{end}}
