package set_header

import (
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/api"
)

// NewCommand builds this command's declaration — the whole of what its
// entries.yaml says — and closes CommandHandler over the sandbox as the
// handler behind it. It is called once, by sandbox/internal/cli/new.go, and
// what it returns is one entry of Cli.Commands: the declaration alone, which
// the dispatch copies with api.BindCommand before binding a command line onto
// it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewCommand(sandbox *api.Sandbox) api.Command {
	command := api.NewCommand()

	command.Name = "set_header"
	command.Identifiers = []string{"set-header"}
	command.Category = "Server System"
	command.Help = "Rewrite one declared request header of a route"
	command.LongDescription = "Rewrites one declared header in place and runs build. It is add-header applied to a declaration that already exists: the keys given are written over the ones there, --clear takes one off, and the result goes through the same constructor — so adding a bound that was forgotten never means removing the header and declaring it again."
	command.Examples = []string{"set-header authorization --route create-user --required --description 'the bearer token'"}
	command.Hidden = false

	command.Flags = []api.CommandFlag{
		{
			Id:          "route",
			Type:        "string",
			Required:    true,
			Array:       false,
			Description: "the route (identifier or package name) the header is declared on",
			Examples:    []string{"set-header authorization --route create-user"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--route"},
		},
		{
			Id:          "rename",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the header name it answers to from now on",
			Examples:    []string{"set-header authorization --route create-user --rename x-api-key"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--rename"},
		},
		{
			Id:          "type",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the value type: string, boolean, int or float",
			Examples:    []string{"set-header retries --route create-user --type int"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--type"},
		},
		{
			Id:          "description",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "help text shown for the header",
			Examples:    []string{"set-header authorization --route create-user --description 'the bearer token'"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--description"},
		},
		{
			Id:          "default",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the literal bound when the header is absent",
			Examples:    []string{"set-header accept-language --route create-user --default en"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--default"},
		},
		{
			Id:          "required",
			Type:        "boolean",
			Required:    false,
			Array:       false,
			Description: "refuse a request that does not carry the header",
			Examples:    []string{"set-header authorization --route create-user --required"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--required"},
		},
		{
			Id:          "min",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "smallest accepted value (int/float only)",
			Examples:    []string{"set-header retries --route create-user --type int --min 0"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--min"},
		},
		{
			Id:          "max",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "largest accepted value (int/float only)",
			Examples:    []string{"set-header retries --route create-user --type int --max 5"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--max"},
		},
		{
			Id:          "example",
			Type:        "string",
			Required:    false,
			Array:       true,
			Description: "a value the header takes, for the docs (repeatable; appended)",
			Examples:    []string{"set-header authorization --route create-user --example 'Bearer abc'"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--example"},
		},
		{
			Id:          "clear",
			Type:        "string",
			Required:    false,
			Array:       true,
			Description: "a key to take off again: description, examples, default, required, min or max (repeatable)",
			Examples:    []string{"set-header accept-language --route create-user --clear default"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--clear"},
		},
		{
			Id:          "path",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the dir holding the project (defaults to the current directory)",
			Examples:    []string{},
			Default:     ".",
			HasDefault:  true,
			Identifiers: []string{"--path"},
		},
		{
			Id:          "quiet",
			Type:        "boolean",
			Required:    false,
			Array:       false,
			Description: "Quiets the cli output",
			Examples:    []string{},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--quiet", "-q"},
		},
		{
			Id:          "identifier",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "match only when the request brings exactly this value, putting the field into what the route matches on",
			Examples:    []string{"set-header authorization --route admin --identifier 'Bearer root'"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--identifier"},
		},
		{
			Id:          "starts-with",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "match only when the value the request brings begins with this, putting the field into what the route matches on",
			Examples:    []string{"set-header authorization --route admin --starts-with Bearer"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--starts-with"},
		},
	}

	command.Args = []api.CommandArg{
		{
			Id:          "name",
			Type:        "string",
			Required:    true,
			Array:       false,
			Description: "the header to edit, by the name it is declared under",
			Examples:    []string{"set-header authorization --route create-user --required"},
			Default:     "",
			HasDefault:  false,
		},
	}

	command.Handler = func(bound *api.Command) int {
		return CommandHandler(sandbox, bound)
	}

	return *command
}
