package add_path

import (
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/api"
)

// NewCommand builds this command's declaration — the whole of what its
// entries.yaml says — and closes CommandHandler over the sandbox as the
// handler behind it. It is called once, by sandbox/internal/cli/new.go, and
// what it returns is one entry of Cli.Commands: the declaration alone, which
// the dispatch copies with api.BindCommand before binding a command line onto
// it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewCommand(sandbox *api.Sandbox) api.Command {
	command := api.NewCommand()

	command.Name = "add_path"
	command.Identifiers = []string{"add-path"}
	command.Category = "Server System"
	command.Help = "Add one slice of the request path to a route"
	command.LongDescription = "Inserts one entry into the route's paths and runs build so the route's new.go and entries.go pick it up. A path reads the request segments from --start to --end (both inclusive, -1 the last one) as '/' followed by them joined by '/', binds that text to Entries.<Id>, and — with --trigger — only lets the route run when the text matches."
	command.Examples = []string{"add-path tenant --route create-user --start 1 --end 1", "add-path version --route api --start 0 --end 0 --trigger /v1"}
	command.Hidden = false

	command.Flags = []api.CommandFlag{
		{
			Id:          "route",
			Type:        "string",
			Required:    true,
			Array:       false,
			Description: "the route (identifier or package name) that receives the path",
			Examples:    []string{"add-path tenant --route create-user --start 1 --end 1"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--route"},
		},
		{
			Id:          "start",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the index of the first request segment the slice reads (defaults to 0)",
			Examples:    []string{"add-path tenant --route create-user --start 1"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--start"},
		},
		{
			Id:          "end",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the index of the last request segment the slice reads, -1 for the last one (defaults to -1)",
			Examples:    []string{"add-path tenant --route create-user --start 1 --end 1"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--end"},
		},
		{
			Id:          "type",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "what the slice converts to: string (the default), integer, number or uuid; anything but string reads one segment (--start equal to --end), and a segment that does not convert makes the route a non-match",
			Examples:    []string{"add-path article --route get-article --start 1 --end 1 --type integer"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--type"},
		},
		{
			Id:          "trigger",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "what the slice has to read as for the route to run; without it the path is a plain capture",
			Examples:    []string{"add-path version --route api --start 0 --end 0 --trigger /v1"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--trigger"},
		},
		{
			Id:          "trigger-type",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "how the trigger is compared: equal, prefix (segment by segment), text-prefix, suffix or regex — or starts-with, ends-with, exact, matches (defaults to equal)",
			Examples:    []string{"add-path file --route assets --start 1 --trigger .css --trigger-type suffix"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--trigger-type"},
		},
		{
			Id:          "trigger-negate",
			Type:        "boolean",
			Required:    false,
			Array:       false,
			Description: "invert the trigger: the route runs when the slice does not match it",
			Examples:    []string{"add-path not-login --route admin-guard --trigger /admin/login --trigger-negate"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--trigger-negate"},
		},
		{
			Id:          "trigger-ignore-case",
			Type:        "boolean",
			Required:    false,
			Array:       false,
			Description: "compare the trigger without regard to case",
			Examples:    []string{"add-path version --route api --start 0 --end 0 --trigger /v1 --trigger-ignore-case"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--trigger-ignore-case"},
		},
		{
			Id:          "description",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "help text shown for the path",
			Examples:    []string{"add-path tenant --route create-user --description 'the tenant id'"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--description"},
		},
		{
			Id:          "position",
			Type:        "int",
			Required:    false,
			Array:       false,
			Description: "zero-based index to insert the path at (defaults to the end)",
			Examples:    []string{"add-path tenant --route create-user --position 0"},
			Default:     "-1",
			HasDefault:  true,
			Identifiers: []string{"--position"},
		},
		{
			Id:          "path",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the dir holding the project (defaults to the current directory)",
			Examples:    []string{"add-path tenant --route create-user --path ./my-project"},
			Default:     ".",
			HasDefault:  true,
			Identifiers: []string{"--path"},
		},
		{
			Id:          "quiet",
			Type:        "boolean",
			Required:    false,
			Array:       false,
			Description: "Quiets the cli output",
			Examples:    []string{},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--quiet", "-q"},
		},
	}

	command.Args = []api.CommandArg{
		{
			Id:          "id",
			Type:        "string",
			Required:    true,
			Array:       false,
			Description: "the id of the path, the Entries field its slice binds to (normalized to an exported Go name)",
			Examples:    []string{"add-path tenant --route create-user --start 1 --end 1"},
			Default:     "",
			HasDefault:  false,
		},
	}

	command.Handler = func(bound *api.Command) int {
		return CommandHandler(sandbox, bound)
	}

	return *command
}
