package add_doc

import (
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/api"
)

// NewCommand builds this command's declaration — the whole of what its
// entries.yaml says — and closes CommandHandler over the sandbox as the
// handler behind it. It is called once, by sandbox/binds/cli.go, and what it
// returns is one entry of sandbox.Commands.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewCommand(sandbox *api.Sandbox) *api.Command {
	command := api.NewCommand()

	command.Name = "add_doc"
	command.Identifiers = []string{"add-doc"}
	command.Category = "Documentation"
	command.Help = "Scaffold a new doc directory under docs/"
	command.LongDescription = "Creates docs/<name>/ with a doc.md stub and the props.yaml declaring it,\nthen runs build so README.md's index and the parent's Index.md list it.\nA first-level doc needs at least one --theme of themes.yaml; a nested name\n(docs/<Parent>/<Name>) creates a sub-doc, which takes no theme. Refuses to\noverwrite an existing doc."
	command.Examples = []string{"add-doc HandleReports --theme development --description \"How a report is written and regenerated\"", "add-doc PublicApi/api.AddDoc --description \"The AddDoc action of the sandbox api\""}
	command.Hidden = false

	command.Flags = []api.CommandFlag{
		{
			Id:          "theme",
			Type:        "string",
			Required:    false,
			Array:       true,
			Description: "a theme id of themes.yaml the doc belongs to (repeatable; first-level docs only)",
			Examples:    []string{"--theme development --theme cli-usage"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--theme", "-t"},
		},
		{
			Id:          "description",
			Type:        "string",
			Required:    true,
			Array:       false,
			Description: "the one-line summary every index lists the doc with",
			Examples:    []string{"--description \"How a report is written and regenerated\""},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--description", "-d"},
		},
		{
			Id:          "path",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the dir holding the project (defaults to the current directory)",
			Examples:    []string{"add-doc HandleReports --theme development -d \"...\" --path ./my-project"},
			Default:     ".",
			HasDefault:  true,
			Identifiers: []string{"--path"},
		},
		{
			Id:          "quiet",
			Type:        "boolean",
			Required:    false,
			Array:       false,
			Description: "Quiets the cli output",
			Examples:    []string{"add-doc HandleReports --theme development -d \"...\" -q"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--quiet", "-q"},
		},
	}

	command.Args = []api.CommandArg{
		{
			Id:          "name",
			Type:        "string",
			Required:    true,
			Array:       false,
			Description: "the doc directory under docs/, nested with / for a sub-doc (e.g. PublicApi/api.AddDoc)",
			Examples:    []string{"add-doc HandleReports"},
			Default:     "",
			HasDefault:  false,
		},
	}

	command.Handler = func() int {
		return CommandHandler(sandbox, command)
	}

	return command
}
