package add_doc

import (
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/api"
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/internal/generated/cli/command"
)

// NewCommand builds this command's declaration — a 1:1 image of its
// command.yaml — on the generic base of sandbox/internal/generated/cli/command,
// and closes InternalPureHandler over the sandbox as the handler behind it. It
// is called once by sandbox/internal/generated/cli/cli/new.go, and what it
// returns is one entry of Cli.Commands: the declaration alone, which the
// dispatch copies with api.BindCommand before binding a command line onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in InternalPureHandler.go.
func NewCommand(sandbox *api.Sandbox) *api.Command {
	self := command.NewCommand(sandbox)

	self.Name = "add_doc"
	self.Identifiers = []string{"add-doc"}
	self.Priority = 100
	self.Segments = 0
	self.Strict = true
	self.Pattern = "add-doc <Name>"
	self.Category = "Documentation"
	self.Help = "Scaffold a new doc directory under docs/"
	self.LongDescription = "Creates docs/<name>/ with a doc.md stub and the props.yaml declaring it,\nthen runs build so README.md's index and the parent's Index.md list it.\nA first-level doc needs at least one --theme of themes.yaml; a nested name\n(docs/<Parent>/<Name>) creates a sub-doc, which takes no theme. Refuses to\noverwrite an existing doc."
	self.Examples = []string{"add-doc HandleReports --theme development --description \"How a report is written and regenerated\"", "add-doc PublicApi/api.AddDoc --description \"The AddDoc action of the sandbox api\""}
	self.Hidden = false

	self.Args = []api.CommandArg{
		{
			Id:          "Command",
			Start:       0,
			End:         0,
			Type:        api.StringArg,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Description: "",
			Trigger:     api.Trigger{Exist: true, Type: api.EqualTrigger, Value: "add-doc", Negate: false, IgnoreCase: false},
		},
		{
			Id:          "Name",
			Start:       1,
			End:         1,
			Type:        api.StringArg,
			Required:    true,
			Default:     "",
			HasDefault:  false,
			Description: "the doc directory under docs/, nested with / for a sub-doc (e.g. PublicApi/api.AddDoc)",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
		},
	}

	self.Flags = []api.CommandFlag{
		{
			Id:          "Theme",
			Keys:        []string{"--theme", "-t"},
			Type:        api.StringArrayFlag,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "a theme id of themes.yaml the doc belongs to (repeatable; first-level docs only)",
		},
		{
			Id:          "Description",
			Keys:        []string{"--description", "-d"},
			Type:        api.StringFlag,
			Required:    true,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "the one-line summary every index lists the doc with",
		},
	}

	self.InternalPurehandler = func(props *api.CommandProps, entries *Entries, response *api.CommandResponse) error {
		return InternalPureHandler(sandbox, props, entries, response)
	}

	return self
}
