package add_segment

import (
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/api"
)

// NewCommand builds this command's declaration — the whole of what its
// entries.yaml says — and closes CommandHandler over the sandbox as the
// handler behind it. It is called once, by sandbox/internal/cli/new.go, and
// what it returns is one entry of Cli.Commands: the declaration alone, which
// the dispatch copies with api.BindCommand before binding a command line onto
// it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewCommand(sandbox *api.Sandbox) api.Command {
	command := api.NewCommand()

	command.Name = "add_segment"
	command.Identifiers = []string{"add-segment"}
	command.Category = "Server System"
	command.Help = "Add a segment to a route's path"
	command.LongDescription = "Appends one segment to the route's paths and runs build so the route's new.go picks it up. With --identifier the segment is a literal, normalized to start with /; with a name it is a capture, which is always required and is bound under that name already converted. --array makes that capture take every segment left in the path, which only the last segment of a route may do."
	command.Examples = []string{"add-segment --route create-user --identifier /users", "add-segment tenant --route create-user --description \"the tenant the user belongs to\"", "add-segment page --route list-users --type int --min 1", "add-segment rest --route static --array"}
	command.Hidden = false

	command.Flags = []api.CommandFlag{
		{
			Id:          "route",
			Type:        "string",
			Required:    true,
			Array:       false,
			Description: "the route (identifier or package name) that receives the segment",
			Examples:    []string{"add-segment tenant --route create-user"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--route"},
		},
		{
			Id:          "identifier",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "declare a literal segment instead of a capture, always starting with /",
			Examples:    []string{"add-segment --route create-user --identifier /users"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--identifier"},
		},
		{
			Id:          "type",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the value type of a captured segment: string, boolean, int or float",
			Examples:    []string{"add-segment page --route list-users --type int"},
			Default:     "string",
			HasDefault:  true,
			Identifiers: []string{"--type"},
		},
		{
			Id:          "description",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "help text shown for the captured segment",
			Examples:    []string{"add-segment tenant --route create-user --description \"the tenant the user belongs to\""},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--description"},
		},
		{
			Id:          "example",
			Type:        "string",
			Required:    false,
			Array:       true,
			Description: "an usage example for the segment (repeatable)",
			Examples:    []string{"add-segment tenant --route create-user --example /acme"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--example"},
		},
		{
			Id:          "array",
			Type:        "boolean",
			Required:    false,
			Array:       false,
			Description: "take every segment left in the path into a []T field (the last segment only)",
			Examples:    []string{"add-segment rest --route static --array"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--array"},
		},
		{
			Id:          "min",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "smallest accepted value (int/float only)",
			Examples:    []string{"add-segment page --route list-users --type int --min 1"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--min"},
		},
		{
			Id:          "max",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "largest accepted value (int/float only)",
			Examples:    []string{"add-segment page --route list-users --type int --max 100"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--max"},
		},
		{
			Id:          "position",
			Type:        "int",
			Required:    false,
			Array:       false,
			Description: "zero-based index to insert the segment at (defaults to the end)",
			Examples:    []string{"add-segment tenant --route create-user --position 0"},
			Default:     "-1",
			HasDefault:  true,
			Identifiers: []string{"--position"},
		},
		{
			Id:          "path",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the dir holding the project (defaults to the current directory)",
			Examples:    []string{"add-segment tenant --route create-user --path ./my-project"},
			Default:     ".",
			HasDefault:  true,
			Identifiers: []string{"--path"},
		},
		{
			Id:          "quiet",
			Type:        "boolean",
			Required:    false,
			Array:       false,
			Description: "Quiets the cli output",
			Examples:    []string{},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--quiet", "-q"},
		},
		{
			Id:          "starts-with",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "spell a literal segment the path only has to begin with, so the route answers every path under it",
			Examples:    []string{"add-segment --route logger --starts-with /api"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--starts-with"},
		},
	}

	command.Args = []api.CommandArg{
		{
			Id:          "name",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the captured segment's name (omitted when --identifier declares a literal segment)",
			Examples:    []string{"add-segment tenant --route create-user"},
			Default:     "",
			HasDefault:  false,
		},
	}

	command.Handler = func(bound *api.Command) int {
		return CommandHandler(sandbox, bound)
	}

	return *command
}
