package remove_arg

import (
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/api"
)

// NewCommand builds this command's declaration — the whole of what its
// entries.yaml says — and closes CommandHandler over the sandbox as the
// handler behind it. It is called once, by sandbox/binds/cli.go, and what it
// returns is one entry of sandbox.Commands.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewCommand(sandbox *api.Sandbox) *api.Command {
	command := api.NewCommand()

	command.Name = "remove_arg"
	command.Identifiers = []string{"remove-arg"}
	command.Category = "Cli System"
	command.Help = "Remove a positional arg from a command's entries.yaml"
	command.LongDescription = "Drops one positional arg declaration from\nsandbox/internal/commands/<command>/entries.yaml and runs build so the\ncommand's new.go forgets it. Later args shift up."
	command.Examples = []string{"remove-arg file --command exec"}
	command.Hidden = false

	command.Flags = []api.CommandFlag{
		{
			Id:          "command",
			Type:        "string",
			Required:    true,
			Array:       false,
			Description: "the command (identifier or package name) that owns the arg",
			Examples:    []string{"--command exec"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--command", "-c"},
		},
		{
			Id:          "path",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the dir holding the project (defaults to the current directory)",
			Examples:    []string{"remove-arg file --command exec --path ./my-project"},
			Default:     ".",
			HasDefault:  true,
			Identifiers: []string{"--path"},
		},
		{
			Id:          "quiet",
			Type:        "boolean",
			Required:    false,
			Array:       false,
			Description: "Quiets the cli output",
			Examples:    []string{},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--quiet", "-q"},
		},
	}

	command.Args = []api.CommandArg{
		{
			Id:          "name",
			Type:        "string",
			Required:    true,
			Array:       false,
			Description: "the arg name",
			Examples:    []string{"remove-arg file --command exec"},
			Default:     "",
			HasDefault:  false,
		},
	}

	command.Handler = func() int {
		return CommandHandler(sandbox, command)
	}

	return command
}
