// Code generated by agnos. DO NOT EDIT.

package show_database

import (
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/api"
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/internal/commandprops"
)

// NewCommand builds this command's declaration — a 1:1 image of its
// command.yaml — on the empty base of Deps.OpinionatedAgnosCli.NewCommand, and
// closes Handle over the sandbox as the handler behind it. It is
// called once by sandbox/internal/cli/generated.new.go, and what it returns
// is one entry of Cli.Commands: the declaration alone, which the lib's dispatch
// copies before binding a command line onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewCommand(sandbox *api.Sandbox) *api.Command {
	self := sandbox.Deps.OpinionatedAgnosCli.NewCommand(sandbox.Deps.ArgvDeps)

	self.Name = "show_database"
	self.Identifiers = []string{"show-database"}
	self.Priority = 100
	self.Segments = 0
	self.Strict = true
	self.Pattern = "show-database <Name>"
	self.Category = "Database"
	self.Summary = "Print one database's whole declaration as a tree"
	self.Description = "Reads sandbox/internal/databases/<database>/database.yaml and prints it as a tree: the package it declares and where its keys are written, then every table, the fields it holds, and the signature of every method those fields generate. It is the one command of the database surface that writes nothing and runs no build."
	self.Examples = []string{"show-database app-database"}
	self.Hidden = false

	self.Args = []api.CommandArg{
		{
			Id:          "Verb",
			Start:       0,
			End:         0,
			Type:        api.ArgString,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Description: "",
			Trigger:     api.Trigger{Set: true, Type: api.TriggerEqual, Value: "show-database", Negate: false, IgnoreCase: false},
		},
		{
			Id:          "Name",
			Start:       1,
			End:         1,
			Type:        api.ArgString,
			Required:    true,
			Default:     "",
			HasDefault:  false,
			Description: "the database (identifier or package name) to print",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
		},
	}

	self.Flags = []api.CommandFlag{}

	self.Handle = func(props *commandprops.CommandProps, input *Input, response *api.CommandResponse) error {
		return Handle(sandbox, props, input, response)
	}

	return self
}
