// Code generated by agnos. DO NOT EDIT.

package project_flags

import (
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/api"
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/internal/commandprops"
)

// NewCommand builds this command's declaration — a 1:1 image of its
// command.yaml — on the empty base of Deps.OpinionatedAgnosCli.NewCommand, and
// closes Handle over the sandbox as the handler behind it. It is
// called once by sandbox/internal/cli/generated.new.go, and what it returns
// is one entry of Cli.Commands: the declaration alone, which the lib's dispatch
// copies before binding a command line onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewCommand(sandbox *api.Sandbox) *api.Command {
	self := sandbox.Deps.OpinionatedAgnosCli.NewCommand(sandbox.Deps.ArgvDeps)

	self.Name = "project_flags"
	self.Identifiers = []string{}
	self.Priority = 10
	self.Segments = 0
	self.Strict = false
	self.Pattern = "*"
	self.Category = "Middleware"
	self.Summary = "Read --path and --quiet in front of every command"
	self.Description = "Runs in front of every command line and answers none of them. It reads\n--path into props.Path, the project every action works on, and --quiet,\nwhich silences the progress channel for the rest of the process. No command\ndeclares either flag itself."
	self.Examples = []string{}
	self.Hidden = false

	self.Args = []api.CommandArg{
		{
			Id:          "Verb",
			Start:       0,
			End:         -1,
			Type:        api.ArgString,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Description: "",
			Trigger:     api.Trigger{Set: true, Type: api.TriggerPrefix, Value: "", Negate: false, IgnoreCase: false},
		},
	}

	self.Flags = []api.CommandFlag{
		{
			Id:          "Path",
			Keys:        []string{"--path"},
			Type:        api.FlagString,
			Required:    false,
			Default:     ".",
			HasDefault:  true,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "the dir holding the project (defaults to the current directory)",
		},
		{
			Id:          "Quiet",
			Keys:        []string{"--quiet", "-q"},
			Type:        api.FlagBoolean,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "Quiets the cli output",
		},
	}

	self.Handle = func(props *commandprops.CommandProps, input *Input, response *api.CommandResponse) error {
		return Handle(sandbox, props, input, response)
	}

	return self
}
