package list_routes

import (
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/api"
)

// NewCommand builds this command's declaration — the whole of what its
// entries.yaml says — and closes CommandHandler over the sandbox as the
// handler behind it. It is called once, by sandbox/internal/generated/cli/new.go, and
// what it returns is one entry of Cli.Commands: the declaration alone, which
// the dispatch copies with api.BindCommand before binding a command line onto
// it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewCommand(sandbox *api.Sandbox) api.Command {
	command := api.NewCommand()

	command.Name = "list_routes"
	command.Identifiers = []string{"list-routes"}
	command.Category = "Server System"
	command.Help = "List every route in the order the chain runs them"
	command.LongDescription = "Prints one line per declared route — the rung, the methods, the pattern and the name — in the order the dispatch runs them: the chain first, lowest priority first, then the routes of the after phase. Writes nothing."
	command.Examples = []string{"list-routes"}
	command.Hidden = false

	command.Flags = []api.CommandFlag{
		{
			Id:          "path",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the dir holding the project (defaults to the current directory)",
			Examples:    []string{"list-routes --path ./my-project"},
			Default:     ".",
			HasDefault:  true,
			Identifiers: []string{"--path"},
		},
		{
			Id:          "quiet",
			Type:        "boolean",
			Required:    false,
			Array:       false,
			Description: "Quiets the cli output",
			Examples:    []string{},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--quiet", "-q"},
		},
	}

	command.Args = []api.CommandArg{}

	command.Handler = func(bound *api.Command) int {
		return CommandHandler(sandbox, bound)
	}

	return *command
}
