package add_flag

// Entries is every value this command reads off a command line, one field per
// entry of its command.yaml: FullCommand, the whole command line, then one per
// entry of `args` and one per entry of `flags`, each tagged with the id the
// generic CommandHandler fills it by. InternalPureHandler is handed one,
// already filled.
// Generated by `agnos build` — do not edit by hand.
type Entries struct {
	FullCommand []string `id:"FullCommand"`
	Command     string   `id:"Command"`
	Name        string   `id:"Name"`
	Identifier  []string `id:"Identifier"`
	Target      string   `id:"Target"`
	Type        string   `id:"Type"`
	Description string   `id:"Description"`
	Example     []string `id:"Example"`
	Default     string   `id:"Default"`
	Required    bool     `id:"Required"`
	Array       bool     `id:"Array"`
	Min         string   `id:"Min"`
	Max         string   `id:"Max"`
	Position    int      `id:"Position"`
}
