package exec_test

import (
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/api"
)

// NewCommand builds this command's declaration — the whole of what its
// entries.yaml says — and closes CommandHandler over the sandbox as the
// handler behind it. It is called once, by sandbox/binds/cli.go, and what it
// returns is one entry of sandbox.Commands.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewCommand(sandbox *api.Sandbox) *api.Command {
	command := api.NewCommand()

	command.Name = "exec_test"
	command.Identifiers = []string{"exec-test"}
	command.Category = "Examples"
	command.Help = "Run the project's examples and check them against their goldens"
	command.LongDescription = "Runs every example of examples/cli/ and examples/lib/ in alphabetical order, cli side first, each with its own directory as the working directory and the project's own cli in front of the PATH. Every run starts from a removed TestDir and a removed AssertDir, and what it produced - the merged output, the exit status and the sha256 of every file the example copied out of TestDir into AssertDir - is compared against the example's result.yaml, or written there when that golden does not exist yet. An example that copied nothing out fails: it asserted nothing. An example declared on both sides must leave the same tree and exit the same way: the cli is only a wrapper over the lib."
	command.Examples = []string{"exec-test", "exec-test --only start", "exec-test --update"}
	command.Hidden = false

	command.Flags = []api.CommandFlag{
		{
			Id:          "only",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "run a single example by name, both sides (defaults to every example)",
			Examples:    []string{"exec-test --only start"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--only"},
		},
		{
			Id:          "update",
			Type:        "boolean",
			Required:    false,
			Array:       false,
			Description: "rewrite every golden result.yaml with what this run produced instead of comparing",
			Examples:    []string{"exec-test --update"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--update"},
		},
		{
			Id:          "path",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the dir holding the project (defaults to the current directory)",
			Examples:    []string{"exec-test --path ./my-project"},
			Default:     ".",
			HasDefault:  true,
			Identifiers: []string{"--path"},
		},
		{
			Id:          "quiet",
			Type:        "boolean",
			Required:    false,
			Array:       false,
			Description: "Quiets the cli output",
			Examples:    []string{"exec-test -q"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--quiet", "-q"},
		},
	}

	command.Args = []api.CommandArg{}

	command.Handler = func() int {
		return CommandHandler(sandbox, command)
	}

	return command
}
