// Code generated by agnos. DO NOT EDIT.

package verify

import (
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/api"
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/internal/commandprops"
)

// NewCommand builds this command's declaration — a 1:1 image of its
// command.yaml — on the empty base of Deps.OpinionatedAgnosCli.NewCommand, and
// closes Handle over the sandbox as the handler behind it. It is
// called once by sandbox/internal/cli/generated.new.go, and what it returns
// is one entry of Cli.Commands: the declaration alone, which the lib's dispatch
// copies before binding a command line onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewCommand(sandbox *api.Sandbox) *api.Command {
	self := sandbox.Deps.OpinionatedAgnosCli.NewCommand(sandbox.Deps.ArgvDeps)

	self.Name = "verify"
	self.Identifiers = []string{"verify"}
	self.Priority = 100
	self.Segments = 0
	self.Strict = true
	self.Pattern = "verify"
	self.Category = "Core"
	self.Summary = "Check the project keeps the sandbox/adapter schema"
	self.Description = "Verifies the structural rules the harness depends on: sandbox/ imports stay inside sandbox/, sandbox/ holds only api, deps, internal and generated.new.go, sandbox/api imports nothing but sandbox/deps and sandbox/deps imports nothing external, every sandbox/api file has the sandbox/internal/<x>/ package whose New<X> builds it, every generated.*.go opens with its Code generated header, and adapters/ holds only bindings and libs. `agnos build` runs this as a gate unless --unsafe is passed."
	self.Examples = []string{"verify"}
	self.Hidden = false

	self.Args = []api.CommandArg{
		{
			Id:          "Verb",
			Start:       0,
			End:         0,
			Type:        api.ArgString,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Description: "",
			Trigger:     api.Trigger{Set: true, Type: api.TriggerEqual, Value: "verify", Negate: false, IgnoreCase: false},
		},
	}

	self.Flags = []api.CommandFlag{
		{
			Id:          "Runtime",
			Keys:        []string{"--runtime"},
			Type:        api.FlagString,
			Required:    false,
			Default:     "go",
			HasDefault:  true,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "the toolchain the project is handed to after the schema check: go (tidy + compile) or none",
		},
	}

	self.Handle = func(props *commandprops.CommandProps, input *Input, response *api.CommandResponse) error {
		return Handle(sandbox, props, input, response)
	}

	return self
}
