package cli

import (
	"strconv"
	"strings"

	"github.com/MateusMoutinhoOrg/Agnos/sandbox/deps"
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/deps/argvdeps"
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/internal/config"
	add_arg "github.com/MateusMoutinhoOrg/Agnos/sandbox/internal/commands/add_arg"
	add_command "github.com/MateusMoutinhoOrg/Agnos/sandbox/internal/commands/add_command"
	add_flag "github.com/MateusMoutinhoOrg/Agnos/sandbox/internal/commands/add_flag"
	build "github.com/MateusMoutinhoOrg/Agnos/sandbox/internal/commands/build"
	cli_init "github.com/MateusMoutinhoOrg/Agnos/sandbox/internal/commands/cli_init"
	cli_purge "github.com/MateusMoutinhoOrg/Agnos/sandbox/internal/commands/cli_purge"
	dep_install "github.com/MateusMoutinhoOrg/Agnos/sandbox/internal/commands/dep_install"
	dep_list "github.com/MateusMoutinhoOrg/Agnos/sandbox/internal/commands/dep_list"
	dep_remove "github.com/MateusMoutinhoOrg/Agnos/sandbox/internal/commands/dep_remove"
	deps_init "github.com/MateusMoutinhoOrg/Agnos/sandbox/internal/commands/deps_init"
	deps_purge "github.com/MateusMoutinhoOrg/Agnos/sandbox/internal/commands/deps_purge"
	help "github.com/MateusMoutinhoOrg/Agnos/sandbox/internal/commands/help"
	remove_arg "github.com/MateusMoutinhoOrg/Agnos/sandbox/internal/commands/remove_arg"
	remove_command "github.com/MateusMoutinhoOrg/Agnos/sandbox/internal/commands/remove_command"
	remove_flag "github.com/MateusMoutinhoOrg/Agnos/sandbox/internal/commands/remove_flag"
	set_command "github.com/MateusMoutinhoOrg/Agnos/sandbox/internal/commands/set_command"
	start "github.com/MateusMoutinhoOrg/Agnos/sandbox/internal/commands/start"
	verify "github.com/MateusMoutinhoOrg/Agnos/sandbox/internal/commands/verify"
	version "github.com/MateusMoutinhoOrg/Agnos/sandbox/internal/commands/version"
)

// Exit codes. Kept here (not in sandbox/api) so the cli layer has no
// dependency on the contract package. They mirror sandbox/api: 0 success,
// 1 a well-formed command that failed, 2 a command line that was wrong.
const (
	ExitOk      = 0
	ExitFailure = 1
	ExitUsage   = 2
)

// CliMain is generated by `agnos build` from every
// sandbox/internal/commands/<name>/entries.yaml. It reads the verb, then hands
// the remaining argv to the matching command's generated dispatch function,
// which fills that command's Entries struct and calls its CommandHandler.
// `help` is dispatched through that same path — it is a declared command whose
// three files agnos happens to write itself — and is reached directly only for
// the empty command line below.
func CliMain(deps *deps.Deps, args []string) int {

	if len(args) == 0 {
		help.PrintGeneralHelp(deps)
		return ExitUsage
	}

	verb := deps.Argvdeps.New(args)

	action, err := verb.GetNextStringArg()
	if err != nil {
		help.PrintGeneralHelp(deps)
		return ExitUsage
	}

	switch {
	case action == "add-arg":
		return dispatchAddArg(deps, verb)
	case action == "add-command":
		return dispatchAddCommand(deps, verb)
	case action == "add-flag":
		return dispatchAddFlag(deps, verb)
	case action == "build":
		return dispatchBuild(deps, verb)
	case action == "cli-init":
		return dispatchCliInit(deps, verb)
	case action == "cli-purge":
		return dispatchCliPurge(deps, verb)
	case action == "dep-install":
		return dispatchDepInstall(deps, verb)
	case action == "dep-list":
		return dispatchDepList(deps, verb)
	case action == "dep-remove":
		return dispatchDepRemove(deps, verb)
	case action == "deps-init":
		return dispatchDepsInit(deps, verb)
	case action == "deps-purge":
		return dispatchDepsPurge(deps, verb)
	case action == "help" || action == "--help":
		return dispatchHelp(deps, verb)
	case action == "remove-arg":
		return dispatchRemoveArg(deps, verb)
	case action == "remove-command":
		return dispatchRemoveCommand(deps, verb)
	case action == "remove-flag":
		return dispatchRemoveFlag(deps, verb)
	case action == "set-command":
		return dispatchSetCommand(deps, verb)
	case action == "start":
		return dispatchStart(deps, verb)
	case action == "verify":
		return dispatchVerify(deps, verb)
	case action == "version" || action == "--version":
		return dispatchVersion(deps, verb)
	}

	deps.Std.Error("unknown command %q — run '%s help' to see the available commands\n", action, binaryName())
	return ExitUsage
}

// ─── argv helpers ───────────────────────────────────────────────────────────
//
// Every dispatch function below reads the command line through these, so one
// spelling of every usage error is emitted for the whole CLI.

// binaryName is the executable's name as a user types it: the configured
// project name, lowercased.
func binaryName() string {
	return strings.ToLower(config.ProjectName)
}

// silenceLogs turns off the progress channel for the rest of the process. It
// backs the --quiet flag: results (Printf) and errors (Error) still go out,
// only the "… started with path …" notices stop.
func silenceLogs(deps *deps.Deps) {
	deps.Std.Log = func(format string, a ...any) (int, error) {
		return 0, nil
	}
}

// optionValue reads the occurrence-th value of a value flag, reporting a
// clean usage error when the flag was given with nothing after it.
func optionValue(deps *deps.Deps, verb argvdeps.Parser, name string, flags []string, occurrence int) (string, bool) {
	raw, err := verb.GetStringOption(flags, occurrence)
	if err != nil {
		deps.Std.Error("flag '%s': expected a value after %s\n", name, flags[0])
		return "", false
	}
	return raw, true
}

// nextArgValue drains the next positional argument, reporting whether one was
// left. It never fails on the value itself: parsing is the parse* helpers' job,
// so an unparsable argument is told apart from an exhausted command line.
func nextArgValue(verb argvdeps.Parser) (string, bool) {
	raw, err := verb.GetNextStringArg()
	if err != nil {
		return "", false
	}
	return raw, true
}

// parseStringValue is the string arm of the parse* family. Every raw value is
// already a string, so it only exists to keep the generated dispatch uniform
// across the four field types.
func parseStringValue(deps *deps.Deps, subject string, name string, raw string) (string, bool) {
	return raw, true
}

// parseIntValue converts a raw command-line value to an int, reporting the
// failure in the CLI's own words rather than the parser library's.
func parseIntValue(deps *deps.Deps, subject string, name string, raw string) (int, bool) {
	value, err := strconv.Atoi(raw)
	if err != nil {
		deps.Std.Error("%s '%s': %q is not a valid integer\n", subject, name, raw)
		return 0, false
	}
	return value, true
}

// parseFloatValue converts a raw command-line value to a float64, reporting
// the failure in the CLI's own words rather than the parser library's.
func parseFloatValue(deps *deps.Deps, subject string, name string, raw string) (float64, bool) {
	value, err := strconv.ParseFloat(raw, 64)
	if err != nil {
		deps.Std.Error("%s '%s': %q is not a valid number\n", subject, name, raw)
		return 0, false
	}
	return value, true
}

// checkUnknownFlags reports the first argument that still looks like a flag
// after every declared flag has been read — a typo such as --pathh, which
// would otherwise be ignored and leave the command running on a default.
func checkUnknownFlags(deps *deps.Deps, verb argvdeps.Parser) bool {
	for i, used := range verb.Used {
		if used || !strings.HasPrefix(verb.Args[i], "-") {
			continue
		}
		deps.Std.Error("unknown flag %q — run '%s help' for the accepted flags\n", verb.Args[i], binaryName())
		return false
	}
	return true
}

// checkUnusedArgs reports the first argument left over once every declared
// flag and positional arg has been read.
func checkUnusedArgs(deps *deps.Deps, verb argvdeps.Parser) bool {
	for i, used := range verb.Used {
		if used {
			continue
		}
		deps.Std.Error("unexpected argument %q\n", verb.Args[i])
		return false
	}
	return true
}

func dispatchAddArg(deps *deps.Deps, verb argvdeps.Parser) int {
	entries := &add_arg.Entries{}
	if verb.GetOptionsSize([]string{ "--command", "-c" }) > 0 {
		raw, rawOk := optionValue(deps, verb, "command", []string{ "--command", "-c" }, 0)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := parseStringValue(deps, "flag", "command", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Command = value
	} else {
		deps.Std.Error("required flag 'command' not provided\n")
		return ExitUsage
	}
	if verb.GetOptionsSize([]string{ "--type", "-t" }) > 0 {
		raw, rawOk := optionValue(deps, verb, "type", []string{ "--type", "-t" }, 0)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := parseStringValue(deps, "flag", "type", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Type = value
	} else {
		entries.Type = "string"
	}
	if verb.GetOptionsSize([]string{ "--description", "-d" }) > 0 {
		raw, rawOk := optionValue(deps, verb, "description", []string{ "--description", "-d" }, 0)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := parseStringValue(deps, "flag", "description", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Description = value
	}
	for occurrence := 0; occurrence < verb.GetOptionsSize([]string{ "--example", "-e" }); occurrence++ {
		raw, rawOk := optionValue(deps, verb, "example", []string{ "--example", "-e" }, occurrence)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := parseStringValue(deps, "flag", "example", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Example = append(entries.Example, value)
	}
	if verb.GetOptionsSize([]string{ "--default" }) > 0 {
		raw, rawOk := optionValue(deps, verb, "default", []string{ "--default" }, 0)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := parseStringValue(deps, "flag", "default", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Default = value
	}
	entries.Required = verb.IsPresent([]string{ "--required", "-r" })
	entries.Array = verb.IsPresent([]string{ "--array" })
	if verb.GetOptionsSize([]string{ "--min" }) > 0 {
		raw, rawOk := optionValue(deps, verb, "min", []string{ "--min" }, 0)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := parseStringValue(deps, "flag", "min", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Min = value
	}
	if verb.GetOptionsSize([]string{ "--max" }) > 0 {
		raw, rawOk := optionValue(deps, verb, "max", []string{ "--max" }, 0)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := parseStringValue(deps, "flag", "max", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Max = value
	}
	if verb.GetOptionsSize([]string{ "--position" }) > 0 {
		raw, rawOk := optionValue(deps, verb, "position", []string{ "--position" }, 0)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := parseIntValue(deps, "flag", "position", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Position = value
	} else {
		entries.Position = -1
	}
	if verb.GetOptionsSize([]string{ "--path" }) > 0 {
		raw, rawOk := optionValue(deps, verb, "path", []string{ "--path" }, 0)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := parseStringValue(deps, "flag", "path", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Path = value
	} else {
		entries.Path = "."
	}
	entries.Quiet = verb.IsPresent([]string{ "--quiet", "-q" })
	if entries.Quiet {
		silenceLogs(deps)
	}
	if !checkUnknownFlags(deps, verb) {
		return ExitUsage
	}
	if raw, rawOk := nextArgValue(verb); rawOk {
		value, valueOk := parseStringValue(deps, "arg", "name", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Name = value
	} else {
		deps.Std.Error("required arg 'name' not provided\n")
		return ExitUsage
	}
	if !checkUnusedArgs(deps, verb) {
		return ExitUsage
	}
	return add_arg.CommandHandler(deps, entries)
}

func dispatchAddCommand(deps *deps.Deps, verb argvdeps.Parser) int {
	entries := &add_command.Entries{}
	if verb.GetOptionsSize([]string{ "--help" }) > 0 {
		raw, rawOk := optionValue(deps, verb, "help", []string{ "--help" }, 0)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := parseStringValue(deps, "flag", "help", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Help = value
	} else {
		deps.Std.Error("required flag 'help' not provided\n")
		return ExitUsage
	}
	if verb.GetOptionsSize([]string{ "--category" }) > 0 {
		raw, rawOk := optionValue(deps, verb, "category", []string{ "--category" }, 0)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := parseStringValue(deps, "flag", "category", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Category = value
	} else {
		deps.Std.Error("required flag 'category' not provided\n")
		return ExitUsage
	}
	if verb.GetOptionsSize([]string{ "--path" }) > 0 {
		raw, rawOk := optionValue(deps, verb, "path", []string{ "--path" }, 0)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := parseStringValue(deps, "flag", "path", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Path = value
	} else {
		entries.Path = "."
	}
	entries.Quiet = verb.IsPresent([]string{ "--quiet", "-q" })
	if entries.Quiet {
		silenceLogs(deps)
	}
	if !checkUnknownFlags(deps, verb) {
		return ExitUsage
	}
	if raw, rawOk := nextArgValue(verb); rawOk {
		value, valueOk := parseStringValue(deps, "arg", "name", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Name = value
	} else {
		deps.Std.Error("required arg 'name' not provided\n")
		return ExitUsage
	}
	if !checkUnusedArgs(deps, verb) {
		return ExitUsage
	}
	return add_command.CommandHandler(deps, entries)
}

func dispatchAddFlag(deps *deps.Deps, verb argvdeps.Parser) int {
	entries := &add_flag.Entries{}
	for occurrence := 0; occurrence < verb.GetOptionsSize([]string{ "--identifier", "-i" }); occurrence++ {
		raw, rawOk := optionValue(deps, verb, "identifier", []string{ "--identifier", "-i" }, occurrence)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := parseStringValue(deps, "flag", "identifier", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Identifier = append(entries.Identifier, value)
	}
	if verb.GetOptionsSize([]string{ "--command", "-c" }) > 0 {
		raw, rawOk := optionValue(deps, verb, "command", []string{ "--command", "-c" }, 0)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := parseStringValue(deps, "flag", "command", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Command = value
	} else {
		deps.Std.Error("required flag 'command' not provided\n")
		return ExitUsage
	}
	if verb.GetOptionsSize([]string{ "--type", "-t" }) > 0 {
		raw, rawOk := optionValue(deps, verb, "type", []string{ "--type", "-t" }, 0)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := parseStringValue(deps, "flag", "type", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Type = value
	} else {
		entries.Type = "string"
	}
	if verb.GetOptionsSize([]string{ "--description", "-d" }) > 0 {
		raw, rawOk := optionValue(deps, verb, "description", []string{ "--description", "-d" }, 0)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := parseStringValue(deps, "flag", "description", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Description = value
	}
	for occurrence := 0; occurrence < verb.GetOptionsSize([]string{ "--example", "-e" }); occurrence++ {
		raw, rawOk := optionValue(deps, verb, "example", []string{ "--example", "-e" }, occurrence)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := parseStringValue(deps, "flag", "example", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Example = append(entries.Example, value)
	}
	if verb.GetOptionsSize([]string{ "--default" }) > 0 {
		raw, rawOk := optionValue(deps, verb, "default", []string{ "--default" }, 0)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := parseStringValue(deps, "flag", "default", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Default = value
	}
	entries.Required = verb.IsPresent([]string{ "--required", "-r" })
	entries.Array = verb.IsPresent([]string{ "--array" })
	if verb.GetOptionsSize([]string{ "--min" }) > 0 {
		raw, rawOk := optionValue(deps, verb, "min", []string{ "--min" }, 0)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := parseStringValue(deps, "flag", "min", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Min = value
	}
	if verb.GetOptionsSize([]string{ "--max" }) > 0 {
		raw, rawOk := optionValue(deps, verb, "max", []string{ "--max" }, 0)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := parseStringValue(deps, "flag", "max", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Max = value
	}
	if verb.GetOptionsSize([]string{ "--position" }) > 0 {
		raw, rawOk := optionValue(deps, verb, "position", []string{ "--position" }, 0)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := parseIntValue(deps, "flag", "position", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Position = value
	} else {
		entries.Position = -1
	}
	if verb.GetOptionsSize([]string{ "--path" }) > 0 {
		raw, rawOk := optionValue(deps, verb, "path", []string{ "--path" }, 0)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := parseStringValue(deps, "flag", "path", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Path = value
	} else {
		entries.Path = "."
	}
	entries.Quiet = verb.IsPresent([]string{ "--quiet", "-q" })
	if entries.Quiet {
		silenceLogs(deps)
	}
	if !checkUnknownFlags(deps, verb) {
		return ExitUsage
	}
	if raw, rawOk := nextArgValue(verb); rawOk {
		value, valueOk := parseStringValue(deps, "arg", "name", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Name = value
	} else {
		deps.Std.Error("required arg 'name' not provided\n")
		return ExitUsage
	}
	if !checkUnusedArgs(deps, verb) {
		return ExitUsage
	}
	return add_flag.CommandHandler(deps, entries)
}

func dispatchBuild(deps *deps.Deps, verb argvdeps.Parser) int {
	entries := &build.Entries{}
	if verb.GetOptionsSize([]string{ "--path" }) > 0 {
		raw, rawOk := optionValue(deps, verb, "path", []string{ "--path" }, 0)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := parseStringValue(deps, "flag", "path", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Path = value
	} else {
		entries.Path = "."
	}
	entries.Quiet = verb.IsPresent([]string{ "--quiet", "-q" })
	if verb.GetOptionsSize([]string{ "--runtime" }) > 0 {
		raw, rawOk := optionValue(deps, verb, "runtime", []string{ "--runtime" }, 0)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := parseStringValue(deps, "flag", "runtime", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Runtime = value
	} else {
		entries.Runtime = "go"
	}
	entries.Unsafe = verb.IsPresent([]string{ "--unsafe" })
	if entries.Quiet {
		silenceLogs(deps)
	}
	if !checkUnknownFlags(deps, verb) {
		return ExitUsage
	}
	if !checkUnusedArgs(deps, verb) {
		return ExitUsage
	}
	return build.CommandHandler(deps, entries)
}

func dispatchCliInit(deps *deps.Deps, verb argvdeps.Parser) int {
	entries := &cli_init.Entries{}
	if verb.GetOptionsSize([]string{ "--path" }) > 0 {
		raw, rawOk := optionValue(deps, verb, "path", []string{ "--path" }, 0)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := parseStringValue(deps, "flag", "path", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Path = value
	} else {
		entries.Path = "."
	}
	entries.Quiet = verb.IsPresent([]string{ "--quiet", "-q" })
	if entries.Quiet {
		silenceLogs(deps)
	}
	if !checkUnknownFlags(deps, verb) {
		return ExitUsage
	}
	if !checkUnusedArgs(deps, verb) {
		return ExitUsage
	}
	return cli_init.CommandHandler(deps, entries)
}

func dispatchCliPurge(deps *deps.Deps, verb argvdeps.Parser) int {
	entries := &cli_purge.Entries{}
	if verb.GetOptionsSize([]string{ "--path" }) > 0 {
		raw, rawOk := optionValue(deps, verb, "path", []string{ "--path" }, 0)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := parseStringValue(deps, "flag", "path", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Path = value
	} else {
		entries.Path = "."
	}
	entries.Quiet = verb.IsPresent([]string{ "--quiet", "-q" })
	if entries.Quiet {
		silenceLogs(deps)
	}
	if !checkUnknownFlags(deps, verb) {
		return ExitUsage
	}
	if !checkUnusedArgs(deps, verb) {
		return ExitUsage
	}
	return cli_purge.CommandHandler(deps, entries)
}

func dispatchDepInstall(deps *deps.Deps, verb argvdeps.Parser) int {
	entries := &dep_install.Entries{}
	if verb.GetOptionsSize([]string{ "--path" }) > 0 {
		raw, rawOk := optionValue(deps, verb, "path", []string{ "--path" }, 0)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := parseStringValue(deps, "flag", "path", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Path = value
	} else {
		entries.Path = "."
	}
	entries.Quiet = verb.IsPresent([]string{ "--quiet", "-q" })
	if entries.Quiet {
		silenceLogs(deps)
	}
	if !checkUnknownFlags(deps, verb) {
		return ExitUsage
	}
	if raw, rawOk := nextArgValue(verb); rawOk {
		value, valueOk := parseStringValue(deps, "arg", "dep", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Dep = value
	} else {
		deps.Std.Error("required arg 'dep' not provided\n")
		return ExitUsage
	}
	if !checkUnusedArgs(deps, verb) {
		return ExitUsage
	}
	return dep_install.CommandHandler(deps, entries)
}

func dispatchDepList(deps *deps.Deps, verb argvdeps.Parser) int {
	entries := &dep_list.Entries{}
	if verb.GetOptionsSize([]string{ "--path" }) > 0 {
		raw, rawOk := optionValue(deps, verb, "path", []string{ "--path" }, 0)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := parseStringValue(deps, "flag", "path", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Path = value
	} else {
		entries.Path = "."
	}
	entries.Quiet = verb.IsPresent([]string{ "--quiet", "-q" })
	if entries.Quiet {
		silenceLogs(deps)
	}
	if !checkUnknownFlags(deps, verb) {
		return ExitUsage
	}
	if !checkUnusedArgs(deps, verb) {
		return ExitUsage
	}
	return dep_list.CommandHandler(deps, entries)
}

func dispatchDepRemove(deps *deps.Deps, verb argvdeps.Parser) int {
	entries := &dep_remove.Entries{}
	if verb.GetOptionsSize([]string{ "--path" }) > 0 {
		raw, rawOk := optionValue(deps, verb, "path", []string{ "--path" }, 0)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := parseStringValue(deps, "flag", "path", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Path = value
	} else {
		entries.Path = "."
	}
	entries.Quiet = verb.IsPresent([]string{ "--quiet", "-q" })
	if entries.Quiet {
		silenceLogs(deps)
	}
	if !checkUnknownFlags(deps, verb) {
		return ExitUsage
	}
	if raw, rawOk := nextArgValue(verb); rawOk {
		value, valueOk := parseStringValue(deps, "arg", "dep", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Dep = value
	} else {
		deps.Std.Error("required arg 'dep' not provided\n")
		return ExitUsage
	}
	if !checkUnusedArgs(deps, verb) {
		return ExitUsage
	}
	return dep_remove.CommandHandler(deps, entries)
}

func dispatchDepsInit(deps *deps.Deps, verb argvdeps.Parser) int {
	entries := &deps_init.Entries{}
	if verb.GetOptionsSize([]string{ "--path" }) > 0 {
		raw, rawOk := optionValue(deps, verb, "path", []string{ "--path" }, 0)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := parseStringValue(deps, "flag", "path", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Path = value
	} else {
		entries.Path = "."
	}
	entries.Quiet = verb.IsPresent([]string{ "--quiet", "-q" })
	if entries.Quiet {
		silenceLogs(deps)
	}
	if !checkUnknownFlags(deps, verb) {
		return ExitUsage
	}
	if !checkUnusedArgs(deps, verb) {
		return ExitUsage
	}
	return deps_init.CommandHandler(deps, entries)
}

func dispatchDepsPurge(deps *deps.Deps, verb argvdeps.Parser) int {
	entries := &deps_purge.Entries{}
	if verb.GetOptionsSize([]string{ "--path" }) > 0 {
		raw, rawOk := optionValue(deps, verb, "path", []string{ "--path" }, 0)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := parseStringValue(deps, "flag", "path", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Path = value
	} else {
		entries.Path = "."
	}
	entries.Quiet = verb.IsPresent([]string{ "--quiet", "-q" })
	if entries.Quiet {
		silenceLogs(deps)
	}
	if !checkUnknownFlags(deps, verb) {
		return ExitUsage
	}
	if !checkUnusedArgs(deps, verb) {
		return ExitUsage
	}
	return deps_purge.CommandHandler(deps, entries)
}

func dispatchHelp(deps *deps.Deps, verb argvdeps.Parser) int {
	entries := &help.Entries{}
	if !checkUnknownFlags(deps, verb) {
		return ExitUsage
	}
	if raw, rawOk := nextArgValue(verb); rawOk {
		value, valueOk := parseStringValue(deps, "arg", "command", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Command = value
	}
	if !checkUnusedArgs(deps, verb) {
		return ExitUsage
	}
	return help.CommandHandler(deps, entries)
}

func dispatchRemoveArg(deps *deps.Deps, verb argvdeps.Parser) int {
	entries := &remove_arg.Entries{}
	if verb.GetOptionsSize([]string{ "--command", "-c" }) > 0 {
		raw, rawOk := optionValue(deps, verb, "command", []string{ "--command", "-c" }, 0)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := parseStringValue(deps, "flag", "command", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Command = value
	} else {
		deps.Std.Error("required flag 'command' not provided\n")
		return ExitUsage
	}
	if verb.GetOptionsSize([]string{ "--path" }) > 0 {
		raw, rawOk := optionValue(deps, verb, "path", []string{ "--path" }, 0)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := parseStringValue(deps, "flag", "path", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Path = value
	} else {
		entries.Path = "."
	}
	entries.Quiet = verb.IsPresent([]string{ "--quiet", "-q" })
	if entries.Quiet {
		silenceLogs(deps)
	}
	if !checkUnknownFlags(deps, verb) {
		return ExitUsage
	}
	if raw, rawOk := nextArgValue(verb); rawOk {
		value, valueOk := parseStringValue(deps, "arg", "name", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Name = value
	} else {
		deps.Std.Error("required arg 'name' not provided\n")
		return ExitUsage
	}
	if !checkUnusedArgs(deps, verb) {
		return ExitUsage
	}
	return remove_arg.CommandHandler(deps, entries)
}

func dispatchRemoveCommand(deps *deps.Deps, verb argvdeps.Parser) int {
	entries := &remove_command.Entries{}
	if verb.GetOptionsSize([]string{ "--path" }) > 0 {
		raw, rawOk := optionValue(deps, verb, "path", []string{ "--path" }, 0)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := parseStringValue(deps, "flag", "path", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Path = value
	} else {
		entries.Path = "."
	}
	entries.Quiet = verb.IsPresent([]string{ "--quiet", "-q" })
	if entries.Quiet {
		silenceLogs(deps)
	}
	if !checkUnknownFlags(deps, verb) {
		return ExitUsage
	}
	if raw, rawOk := nextArgValue(verb); rawOk {
		value, valueOk := parseStringValue(deps, "arg", "name", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Name = value
	} else {
		deps.Std.Error("required arg 'name' not provided\n")
		return ExitUsage
	}
	if !checkUnusedArgs(deps, verb) {
		return ExitUsage
	}
	return remove_command.CommandHandler(deps, entries)
}

func dispatchRemoveFlag(deps *deps.Deps, verb argvdeps.Parser) int {
	entries := &remove_flag.Entries{}
	if verb.GetOptionsSize([]string{ "--command", "-c" }) > 0 {
		raw, rawOk := optionValue(deps, verb, "command", []string{ "--command", "-c" }, 0)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := parseStringValue(deps, "flag", "command", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Command = value
	} else {
		deps.Std.Error("required flag 'command' not provided\n")
		return ExitUsage
	}
	if verb.GetOptionsSize([]string{ "--path" }) > 0 {
		raw, rawOk := optionValue(deps, verb, "path", []string{ "--path" }, 0)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := parseStringValue(deps, "flag", "path", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Path = value
	} else {
		entries.Path = "."
	}
	entries.Quiet = verb.IsPresent([]string{ "--quiet", "-q" })
	if entries.Quiet {
		silenceLogs(deps)
	}
	if !checkUnknownFlags(deps, verb) {
		return ExitUsage
	}
	if raw, rawOk := nextArgValue(verb); rawOk {
		value, valueOk := parseStringValue(deps, "arg", "name", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Name = value
	} else {
		deps.Std.Error("required arg 'name' not provided\n")
		return ExitUsage
	}
	if !checkUnusedArgs(deps, verb) {
		return ExitUsage
	}
	return remove_flag.CommandHandler(deps, entries)
}

func dispatchSetCommand(deps *deps.Deps, verb argvdeps.Parser) int {
	entries := &set_command.Entries{}
	if verb.GetOptionsSize([]string{ "--help" }) > 0 {
		raw, rawOk := optionValue(deps, verb, "help", []string{ "--help" }, 0)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := parseStringValue(deps, "flag", "help", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Help = value
	}
	if verb.GetOptionsSize([]string{ "--category" }) > 0 {
		raw, rawOk := optionValue(deps, verb, "category", []string{ "--category" }, 0)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := parseStringValue(deps, "flag", "category", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Category = value
	}
	if verb.GetOptionsSize([]string{ "--long-description" }) > 0 {
		raw, rawOk := optionValue(deps, verb, "long-description", []string{ "--long-description" }, 0)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := parseStringValue(deps, "flag", "long-description", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.LongDescription = value
	}
	for occurrence := 0; occurrence < verb.GetOptionsSize([]string{ "--identifier", "-i" }); occurrence++ {
		raw, rawOk := optionValue(deps, verb, "identifier", []string{ "--identifier", "-i" }, occurrence)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := parseStringValue(deps, "flag", "identifier", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Identifier = append(entries.Identifier, value)
	}
	for occurrence := 0; occurrence < verb.GetOptionsSize([]string{ "--example", "-e" }); occurrence++ {
		raw, rawOk := optionValue(deps, verb, "example", []string{ "--example", "-e" }, occurrence)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := parseStringValue(deps, "flag", "example", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Example = append(entries.Example, value)
	}
	entries.Hidden = verb.IsPresent([]string{ "--hidden" })
	entries.Visible = verb.IsPresent([]string{ "--visible" })
	if verb.GetOptionsSize([]string{ "--path" }) > 0 {
		raw, rawOk := optionValue(deps, verb, "path", []string{ "--path" }, 0)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := parseStringValue(deps, "flag", "path", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Path = value
	} else {
		entries.Path = "."
	}
	entries.Quiet = verb.IsPresent([]string{ "--quiet", "-q" })
	if entries.Quiet {
		silenceLogs(deps)
	}
	if !checkUnknownFlags(deps, verb) {
		return ExitUsage
	}
	if raw, rawOk := nextArgValue(verb); rawOk {
		value, valueOk := parseStringValue(deps, "arg", "name", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Name = value
	} else {
		deps.Std.Error("required arg 'name' not provided\n")
		return ExitUsage
	}
	if !checkUnusedArgs(deps, verb) {
		return ExitUsage
	}
	return set_command.CommandHandler(deps, entries)
}

func dispatchStart(deps *deps.Deps, verb argvdeps.Parser) int {
	entries := &start.Entries{}
	if verb.GetOptionsSize([]string{ "--path" }) > 0 {
		raw, rawOk := optionValue(deps, verb, "path", []string{ "--path" }, 0)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := parseStringValue(deps, "flag", "path", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Path = value
	} else {
		entries.Path = "."
	}
	if verb.GetOptionsSize([]string{ "--project-name", "-p" }) > 0 {
		raw, rawOk := optionValue(deps, verb, "project-name", []string{ "--project-name", "-p" }, 0)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := parseStringValue(deps, "flag", "project-name", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.ProjectName = value
	} else {
		deps.Std.Error("required flag 'project-name' not provided\n")
		return ExitUsage
	}
	entries.Quiet = verb.IsPresent([]string{ "--quiet", "-q" })
	entries.Force = verb.IsPresent([]string{ "--force", "-f" })
	if verb.GetOptionsSize([]string{ "--module", "-m" }) > 0 {
		raw, rawOk := optionValue(deps, verb, "module", []string{ "--module", "-m" }, 0)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := parseStringValue(deps, "flag", "module", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Module = value
	}
	if entries.Quiet {
		silenceLogs(deps)
	}
	if !checkUnknownFlags(deps, verb) {
		return ExitUsage
	}
	if !checkUnusedArgs(deps, verb) {
		return ExitUsage
	}
	return start.CommandHandler(deps, entries)
}

func dispatchVerify(deps *deps.Deps, verb argvdeps.Parser) int {
	entries := &verify.Entries{}
	if verb.GetOptionsSize([]string{ "--path" }) > 0 {
		raw, rawOk := optionValue(deps, verb, "path", []string{ "--path" }, 0)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := parseStringValue(deps, "flag", "path", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Path = value
	} else {
		entries.Path = "."
	}
	if verb.GetOptionsSize([]string{ "--runtime" }) > 0 {
		raw, rawOk := optionValue(deps, verb, "runtime", []string{ "--runtime" }, 0)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := parseStringValue(deps, "flag", "runtime", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.Runtime = value
	} else {
		entries.Runtime = "go"
	}
	entries.Quiet = verb.IsPresent([]string{ "--quiet", "-q" })
	if entries.Quiet {
		silenceLogs(deps)
	}
	if !checkUnknownFlags(deps, verb) {
		return ExitUsage
	}
	if !checkUnusedArgs(deps, verb) {
		return ExitUsage
	}
	return verify.CommandHandler(deps, entries)
}

func dispatchVersion(deps *deps.Deps, verb argvdeps.Parser) int {
	entries := &version.Entries{}
	if !checkUnknownFlags(deps, verb) {
		return ExitUsage
	}
	if !checkUnusedArgs(deps, verb) {
		return ExitUsage
	}
	return version.CommandHandler(deps, entries)
}

