package cli

import (
	"github.com/MateusMoutinhoOrg/Agnos-Cli/sandbox/deps"
	"github.com/MateusMoutinhoOrg/Agnos-Cli/sandbox/deps/argvdeps"
	help "github.com/MateusMoutinhoOrg/Agnos-Cli/sandbox/internal/commands/help"
	build "github.com/MateusMoutinhoOrg/Agnos-Cli/sandbox/internal/commands/build"
	cli_init "github.com/MateusMoutinhoOrg/Agnos-Cli/sandbox/internal/commands/cli_init"
	cli_purge "github.com/MateusMoutinhoOrg/Agnos-Cli/sandbox/internal/commands/cli_purge"
	dep_install "github.com/MateusMoutinhoOrg/Agnos-Cli/sandbox/internal/commands/dep_install"
	dep_list "github.com/MateusMoutinhoOrg/Agnos-Cli/sandbox/internal/commands/dep_list"
	dep_remove "github.com/MateusMoutinhoOrg/Agnos-Cli/sandbox/internal/commands/dep_remove"
	deps_init "github.com/MateusMoutinhoOrg/Agnos-Cli/sandbox/internal/commands/deps_init"
	deps_purge "github.com/MateusMoutinhoOrg/Agnos-Cli/sandbox/internal/commands/deps_purge"
	start "github.com/MateusMoutinhoOrg/Agnos-Cli/sandbox/internal/commands/start"
	verify "github.com/MateusMoutinhoOrg/Agnos-Cli/sandbox/internal/commands/verify"
	version "github.com/MateusMoutinhoOrg/Agnos-Cli/sandbox/internal/commands/version"
)

// Exit codes. Kept here (not in sandbox/api) so the cli layer has no
// dependency on the contract package.
const (
	ExitOk      = 0
	ExitUsage   = 1
	ExitFailure = 2
)

// CliMain is generated by `agnos build` from every
// sandbox/internal/commands/<name>/entries.yaml. It reads the verb, then hands
// the remaining argv to the matching command's generated dispatch function,
// which fills that command's Entries struct and calls its CommandHander.
func CliMain(deps *deps.Deps, args []string) int {

	if len(args) == 0 {
		help.PrintGeneralHelp(deps)
		return ExitUsage
	}

	verb := deps.Argvdeps.New(args)

	action, err := verb.GetNextStringArg()
	if err != nil {
		help.PrintGeneralHelp(deps)
		return ExitUsage
	}

	switch {
	case action == "help" || action == "--help":
		return help.Run(deps, verb)
	case action == "build":
		return dispatchBuild(deps, verb)
	case action == "cli-init":
		return dispatchCliInit(deps, verb)
	case action == "cli-purge":
		return dispatchCliPurge(deps, verb)
	case action == "dep-install":
		return dispatchDepInstall(deps, verb)
	case action == "dep-list":
		return dispatchDepList(deps, verb)
	case action == "dep-remove":
		return dispatchDepRemove(deps, verb)
	case action == "deps-init":
		return dispatchDepsInit(deps, verb)
	case action == "deps-purge":
		return dispatchDepsPurge(deps, verb)
	case action == "start":
		return dispatchStart(deps, verb)
	case action == "verify":
		return dispatchVerify(deps, verb)
	case action == "version" || action == "--version":
		return dispatchVersion(deps, verb)
	}

	deps.Std.Printf("Unknown Command!\n")
	return ExitUsage
}

func dispatchBuild(deps *deps.Deps, verb argvdeps.Parser) int {
	entries := &build.Entries{}
	if verb.GetOptionsSize([]string{ "--path" }) > 0 {
		value, valueErr := verb.GetStringOption([]string{ "--path" }, 0)
		if valueErr != nil {
			deps.Std.Printf("flag 'path': %s\n", valueErr.Error())
			return ExitUsage
		}
		entries.Path = value
	} else {
		entries.Path = "."
	}
	entries.Quiet = verb.IsPresent([]string{ "--quiet", "-q" })
	entries.Unsafe = verb.IsPresent([]string{ "--unsafe" })
	return build.CommandHander(deps, entries)
}

func dispatchCliInit(deps *deps.Deps, verb argvdeps.Parser) int {
	entries := &cli_init.Entries{}
	if verb.GetOptionsSize([]string{ "--path" }) > 0 {
		value, valueErr := verb.GetStringOption([]string{ "--path" }, 0)
		if valueErr != nil {
			deps.Std.Printf("flag 'path': %s\n", valueErr.Error())
			return ExitUsage
		}
		entries.Path = value
	} else {
		entries.Path = "."
	}
	entries.Quiet = verb.IsPresent([]string{ "--quiet", "-q" })
	return cli_init.CommandHander(deps, entries)
}

func dispatchCliPurge(deps *deps.Deps, verb argvdeps.Parser) int {
	entries := &cli_purge.Entries{}
	entries.Quiet = verb.IsPresent([]string{ "--quiet", "-q" })
	if verb.GetOptionsSize([]string{ "--path" }) > 0 {
		value, valueErr := verb.GetStringOption([]string{ "--path" }, 0)
		if valueErr != nil {
			deps.Std.Printf("flag 'path': %s\n", valueErr.Error())
			return ExitUsage
		}
		entries.Path = value
	} else {
		entries.Path = "."
	}
	return cli_purge.CommandHander(deps, entries)
}

func dispatchDepInstall(deps *deps.Deps, verb argvdeps.Parser) int {
	entries := &dep_install.Entries{}
	if verb.GetOptionsSize([]string{ "--path" }) > 0 {
		value, valueErr := verb.GetStringOption([]string{ "--path" }, 0)
		if valueErr != nil {
			deps.Std.Printf("flag 'path': %s\n", valueErr.Error())
			return ExitUsage
		}
		entries.Path = value
	} else {
		entries.Path = "."
	}
	entries.Quiet = verb.IsPresent([]string{ "--quiet", "-q" })
	if value, valueErr := verb.GetNextStringArg(); valueErr == nil {
		entries.Dep = value
	} else {
		deps.Std.Printf("required arg 'dep' not provided\n")
		return ExitUsage
	}
	return dep_install.CommandHander(deps, entries)
}

func dispatchDepList(deps *deps.Deps, verb argvdeps.Parser) int {
	entries := &dep_list.Entries{}
	if verb.GetOptionsSize([]string{ "--path" }) > 0 {
		value, valueErr := verb.GetStringOption([]string{ "--path" }, 0)
		if valueErr != nil {
			deps.Std.Printf("flag 'path': %s\n", valueErr.Error())
			return ExitUsage
		}
		entries.Path = value
	} else {
		entries.Path = "."
	}
	entries.Quiet = verb.IsPresent([]string{ "--quiet", "-q" })
	return dep_list.CommandHander(deps, entries)
}

func dispatchDepRemove(deps *deps.Deps, verb argvdeps.Parser) int {
	entries := &dep_remove.Entries{}
	if verb.GetOptionsSize([]string{ "--path" }) > 0 {
		value, valueErr := verb.GetStringOption([]string{ "--path" }, 0)
		if valueErr != nil {
			deps.Std.Printf("flag 'path': %s\n", valueErr.Error())
			return ExitUsage
		}
		entries.Path = value
	} else {
		entries.Path = "."
	}
	entries.Quiet = verb.IsPresent([]string{ "--quiet", "-q" })
	if value, valueErr := verb.GetNextStringArg(); valueErr == nil {
		entries.Dep = value
	} else {
		deps.Std.Printf("required arg 'dep' not provided\n")
		return ExitUsage
	}
	return dep_remove.CommandHander(deps, entries)
}

func dispatchDepsInit(deps *deps.Deps, verb argvdeps.Parser) int {
	entries := &deps_init.Entries{}
	if verb.GetOptionsSize([]string{ "--path" }) > 0 {
		value, valueErr := verb.GetStringOption([]string{ "--path" }, 0)
		if valueErr != nil {
			deps.Std.Printf("flag 'path': %s\n", valueErr.Error())
			return ExitUsage
		}
		entries.Path = value
	} else {
		entries.Path = "."
	}
	entries.Quiet = verb.IsPresent([]string{ "--quiet", "-q" })
	return deps_init.CommandHander(deps, entries)
}

func dispatchDepsPurge(deps *deps.Deps, verb argvdeps.Parser) int {
	entries := &deps_purge.Entries{}
	if verb.GetOptionsSize([]string{ "--path" }) > 0 {
		value, valueErr := verb.GetStringOption([]string{ "--path" }, 0)
		if valueErr != nil {
			deps.Std.Printf("flag 'path': %s\n", valueErr.Error())
			return ExitUsage
		}
		entries.Path = value
	} else {
		entries.Path = "."
	}
	entries.Quiet = verb.IsPresent([]string{ "--quiet", "-q" })
	return deps_purge.CommandHander(deps, entries)
}

func dispatchStart(deps *deps.Deps, verb argvdeps.Parser) int {
	entries := &start.Entries{}
	if verb.GetOptionsSize([]string{ "--module", "-m" }) > 0 {
		value, valueErr := verb.GetStringOption([]string{ "--module", "-m" }, 0)
		if valueErr != nil {
			deps.Std.Printf("flag 'module': %s\n", valueErr.Error())
			return ExitUsage
		}
		entries.Module = value
	}
	if verb.GetOptionsSize([]string{ "--path" }) > 0 {
		value, valueErr := verb.GetStringOption([]string{ "--path" }, 0)
		if valueErr != nil {
			deps.Std.Printf("flag 'path': %s\n", valueErr.Error())
			return ExitUsage
		}
		entries.Path = value
	} else {
		entries.Path = "."
	}
	if verb.GetOptionsSize([]string{ "--project-name", "-p" }) > 0 {
		value, valueErr := verb.GetStringOption([]string{ "--project-name", "-p" }, 0)
		if valueErr != nil {
			deps.Std.Printf("flag 'project-name': %s\n", valueErr.Error())
			return ExitUsage
		}
		entries.ProjectName = value
	} else {
		deps.Std.Printf("required flag 'project-name' not provided\n")
		return ExitUsage
	}
	entries.Quiet = verb.IsPresent([]string{ "--quiet", "-q" })
	entries.Force = verb.IsPresent([]string{ "--force", "-f" })
	return start.CommandHander(deps, entries)
}

func dispatchVerify(deps *deps.Deps, verb argvdeps.Parser) int {
	entries := &verify.Entries{}
	entries.Quiet = verb.IsPresent([]string{ "--quiet", "-q" })
	if verb.GetOptionsSize([]string{ "--path" }) > 0 {
		value, valueErr := verb.GetStringOption([]string{ "--path" }, 0)
		if valueErr != nil {
			deps.Std.Printf("flag 'path': %s\n", valueErr.Error())
			return ExitUsage
		}
		entries.Path = value
	} else {
		entries.Path = "."
	}
	return verify.CommandHander(deps, entries)
}

func dispatchVersion(deps *deps.Deps, verb argvdeps.Parser) int {
	entries := &version.Entries{}
	return version.CommandHander(deps, entries)
}

