package cli

import (
	api "github.com/MateusMoutinhoOrg/Agnos/sandbox/api"
)

// NewCli builds the cli surface of the sandbox: Commands, one entry per
// sandbox/internal/commands/<name>/ built by that package's generated
// NewCommand, and CliMain, the dispatch that reads a command line against
// them. Generated by `agnos build` — do not edit by hand.
func NewCli(sandbox *api.Sandbox) api.Cli {
	cli := api.Cli{}

	cli.CliMain = func(args []string) int {
		return CliMain(sandbox, args)
	}

	return cli
}
