package add_route

import (
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/api"
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/internal/commandprops"
)

// NewCommand builds this command's declaration — a 1:1 image of its
// command.yaml — on the empty base of Deps.OpinatedAgnosCli.NewCommand, and
// closes InternalPureHandler over the sandbox as the handler behind it. It is
// called once by sandbox/internal/generated/cli/cli/new.go, and what it returns
// is one entry of Cli.Commands: the declaration alone, which the lib's dispatch
// copies before binding a command line onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in InternalPureHandler.go.
func NewCommand(sandbox *api.Sandbox) *api.Command {
	self := sandbox.Deps.OpinatedAgnosCli.NewCommand(sandbox.Deps.Argvdeps)

	self.Name = "add_route"
	self.Identifiers = []string{"add-route"}
	self.Priority = 100
	self.Segments = 0
	self.Strict = true
	self.Pattern = "add-route <Name>"
	self.Category = "Server System"
	self.Help = "Declare a new http route"
	self.LongDescription = "Writes <name>/route.yaml and a stub InternalPureHandler.go under sandbox/internal/routeslist — or under the folder --dir names there, e.g. routeslist/admin/<name> — then runs build so the route's new.go (the api.Route that lands in Server.Routes) and entries.go (the Entries its handler is handed) are generated. A directory is a route by holding a route.yaml, at any depth; a name is unique across every folder. The paths come from --pattern, or from one path, Route, reading the whole request path against --trigger. A --middleware declines by default and sits in front of the routes on the default rung; --before and --after place a route next to another one. priority and response-type are always written."
	self.Examples = []string{"add-route create-user --trigger /users --method POST --help \"Create a user\" --category Users", "add-route get-article --pattern '/articles/{article:integer}'", "add-route admin-guard --middleware --trigger /admin"}
	self.Hidden = false

	self.Args = []api.CommandArg{
		{
			Id:          "Command",
			Start:       0,
			End:         0,
			Type:        api.StringArg,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Description: "",
			Trigger:     api.Trigger{Exist: true, Type: api.EqualTrigger, Value: "add-route", Negate: false, IgnoreCase: false},
		},
		{
			Id:          "Name",
			Start:       1,
			End:         1,
			Type:        api.StringArg,
			Required:    true,
			Default:     "",
			HasDefault:  false,
			Description: "the route name (becomes the directory sandbox/internal/routeslist/<name> and its Go package)",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
		},
	}

	self.Flags = []api.CommandFlag{
		{
			Id:          "Trigger",
			Keys:        []string{"--trigger"},
			Type:        api.StringFlag,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "what the whole request path is compared against; an equal, prefix or text-prefix trigger is normalized to start with / (defaults to /<name>, or / for a --middleware)",
		},
		{
			Id:          "TriggerType",
			Keys:        []string{"--trigger-type"},
			Type:        api.StringFlag,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "how the trigger is compared: equal, prefix (the value or anything under it, segment by segment), text-prefix, suffix or regex — or starts-with, ends-with, exact, matches (defaults to equal, or prefix for a --middleware)",
		},
		{
			Id:          "TriggerNegate",
			Keys:        []string{"--trigger-negate"},
			Type:        api.BooleanFlag,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "invert the trigger: the route runs for every path that does not match it",
		},
		{
			Id:          "TriggerIgnoreCase",
			Keys:        []string{"--trigger-ignore-case"},
			Type:        api.BooleanFlag,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "compare the trigger without regard to case",
		},
		{
			Id:          "Pattern",
			Keys:        []string{"--pattern"},
			Type:        api.StringFlag,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "the url shape the route answers, compiled into its paths: literal segments, {name}, {name:integer|number|uuid} and a last {*rest}; without {*rest} the segment count is fixed (excludes --trigger and --trigger-type)",
		},
		{
			Id:          "Method",
			Keys:        []string{"--method", "-m"},
			Type:        api.StringArrayFlag,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "an http method the route answers: GET, POST, PUT, PATCH, DELETE, HEAD, OPTIONS, or ANY for every one (repeatable; defaults to GET, or ANY for a --middleware)",
		},
		{
			Id:          "Middleware",
			Keys:        []string{"--middleware"},
			Type:        api.BooleanFlag,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "declare a middleware: ANY method, a prefix trigger on / unless --trigger says otherwise, priority 10, and a stub handler that hands the request on",
		},
		{
			Id:          "Priority",
			Keys:        []string{"--priority"},
			Type:        api.IntegerFlag,
			Required:    false,
			Default:     "-1",
			HasDefault:  true,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "the rung this route runs on when several match one request, lowest first; a route that answers nothing hands the request on (defaults to 100, or 10 for a --middleware)",
		},
		{
			Id:          "Before",
			Keys:        []string{"--before"},
			Type:        api.StringFlag,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "land one rung below the route named, so it runs first (excludes --priority)",
		},
		{
			Id:          "After",
			Keys:        []string{"--after"},
			Type:        api.StringFlag,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "land one rung above the route named, so it runs next (excludes --priority)",
		},
		{
			Id:          "ResponseType",
			Keys:        []string{"--response-type"},
			Type:        api.StringFlag,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "the Content-Type every response of the route carries (defaults to application/json, or text/plain for a --middleware)",
		},
		{
			Id:          "Help",
			Keys:        []string{"--help"},
			Type:        api.StringFlag,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "one-line description of the route",
		},
		{
			Id:          "Category",
			Keys:        []string{"--category"},
			Type:        api.StringFlag,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "the heading the route is listed under in docs/Routes (defaults to Routes, or Middleware for a --middleware)",
		},
		{
			Id:          "Dir",
			Keys:        []string{"--dir"},
			Type:        api.StringFlag,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "the folder under sandbox/internal/routeslist the route lands in, e.g. admin puts it in routeslist/admin/<name> (defaults to the top); a directory holding a route.yaml is a route, whatever folder holds it",
		},
	}

	self.InternalPureHandler = func(props *commandprops.CommandProps, entries *Entries, response *api.CommandResponse) error {
		return InternalPureHandler(sandbox, props, entries, response)
	}

	return self
}
