package remove_path

import (
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/api"
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/internal/generated/cli/command"
)

// NewCommand builds this command's declaration — a 1:1 image of its
// command.yaml — on the generic base of sandbox/internal/generated/cli/command,
// and closes InternalPureHandler over the sandbox as the handler behind it. It
// is called once by sandbox/internal/generated/cli/cli/new.go, and what it
// returns is one entry of Cli.Commands: the declaration alone, which the
// dispatch copies with api.BindCommand before binding a command line onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in InternalPureHandler.go.
func NewCommand(sandbox *api.Sandbox) *api.Command {
	self := command.NewCommand(sandbox)

	self.Name = "remove_path"
	self.Identifiers = []string{"remove-path"}
	self.Priority = 100
	self.Segments = 0
	self.Strict = true
	self.Pattern = "remove-path <Id>"
	self.Category = "Server System"
	self.Help = "Delete one entry of a route's paths"
	self.LongDescription = "Drops one entry of the route's paths, the exact inverse of add-path, refusing the last one. The build renders only: dropping a path may leave hand-written code reading an Entries field that is gone."
	self.Examples = []string{"remove-path tenant --route create-user"}
	self.Hidden = false

	self.Args = []api.CommandArg{
		{
			Id:          "Command",
			Start:       0,
			End:         0,
			Type:        api.StringArg,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Description: "",
			Trigger:     api.Trigger{Exist: true, Type: api.EqualTrigger, Value: "remove-path", Negate: false, IgnoreCase: false},
		},
		{
			Id:          "Id",
			Start:       1,
			End:         1,
			Type:        api.StringArg,
			Required:    true,
			Default:     "",
			HasDefault:  false,
			Description: "the id of the path to drop (its Entries field)",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
		},
	}

	self.Flags = []api.CommandFlag{
		{
			Id:          "Route",
			Keys:        []string{"--route"},
			Type:        api.StringFlag,
			Required:    true,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "the route (identifier or package name) that declares the path",
		},
	}

	self.InternalPurehandler = func(props *api.CommandProps, entries *Entries, response *api.CommandResponse) error {
		return InternalPureHandler(sandbox, props, entries, response)
	}

	return self
}
