package remove_path

import (
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/api"
)

// NewCommand builds this command's declaration — the whole of what its
// entries.yaml says — and closes CommandHandler over the sandbox as the
// handler behind it. It is called once, by sandbox/internal/cli/new.go, and
// what it returns is one entry of Cli.Commands: the declaration alone, which
// the dispatch copies with api.BindCommand before binding a command line onto
// it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewCommand(sandbox *api.Sandbox) api.Command {
	command := api.NewCommand()

	command.Name = "remove_path"
	command.Identifiers = []string{"remove-path"}
	command.Category = "Server System"
	command.Help = "Delete one entry of a route's paths"
	command.LongDescription = "Drops one entry of the route's paths, the exact inverse of add-path, refusing the last one. The build renders only: dropping a path may leave hand-written code reading an Entries field that is gone."
	command.Examples = []string{"remove-path tenant --route create-user"}
	command.Hidden = false

	command.Flags = []api.CommandFlag{
		{
			Id:          "route",
			Type:        "string",
			Required:    true,
			Array:       false,
			Description: "the route (identifier or package name) that declares the path",
			Examples:    []string{"remove-path tenant --route create-user"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--route"},
		},
		{
			Id:          "path",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the dir holding the project (defaults to the current directory)",
			Examples:    []string{"remove-path tenant --route create-user --path ./my-project"},
			Default:     ".",
			HasDefault:  true,
			Identifiers: []string{"--path"},
		},
		{
			Id:          "quiet",
			Type:        "boolean",
			Required:    false,
			Array:       false,
			Description: "Quiets the cli output",
			Examples:    []string{},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--quiet", "-q"},
		},
	}

	command.Args = []api.CommandArg{
		{
			Id:          "id",
			Type:        "string",
			Required:    true,
			Array:       false,
			Description: "the id of the path to drop (its Entries field)",
			Examples:    []string{"remove-path tenant --route create-user"},
			Default:     "",
			HasDefault:  false,
		},
	}

	command.Handler = func(bound *api.Command) int {
		return CommandHandler(sandbox, bound)
	}

	return *command
}
