package cli

import (
	"{{.Module}}/sandbox/deps"
	"{{.Module}}/sandbox/deps/argvdeps"
	help "{{.Module}}/sandbox/internal/commands/help"
{{- range .Commands}}
	{{.Name}} "{{$.Module}}/sandbox/internal/commands/{{.Name}}"
{{- end}}
)

// Exit codes. Kept here (not in sandbox/api) so the cli layer has no
// dependency on the contract package.
const (
	ExitOk      = 0
	ExitUsage   = 1
	ExitFailure = 2
)

// CliMain is generated by `agnos build` from every
// sandbox/internal/commands/<name>/entries.yaml. It reads the verb, then hands
// the remaining argv to the matching command's generated dispatch function,
// which fills that command's Entries struct and calls its CommandHander.
func CliMain(deps *deps.Deps, args []string) int {

	if len(args) == 0 {
		help.PrintGeneralHelp(deps)
		return ExitUsage
	}

	verb := deps.Argvdeps.New(args)

	action, err := verb.GetNextStringArg()
	if err != nil {
		help.PrintGeneralHelp(deps)
		return ExitUsage
	}

	switch {
	case action == "help" || action == "--help":
		return help.Run(deps, verb)
{{- range .Commands}}
	case {{.MatchExpr}}:
		return dispatch{{.GoName}}(deps, verb)
{{- end}}
	}

	deps.Std.Printf("Unknown Command!\n")
	return ExitUsage
}
{{range .Commands}}
func dispatch{{.GoName}}(deps *deps.Deps, verb argvdeps.Parser) int {
	entries := &{{.Name}}.Entries{}
{{- range .Flags}}
{{- if .IsBool}}
	entries.{{.GoField}} = verb.IsPresent([]string{ {{.IdentifiersGo}} })
{{- else if .IsArray}}
	for occurrence := 0; occurrence < verb.GetOptionsSize([]string{ {{.IdentifiersGo}} }); occurrence++ {
		value, valueErr := verb.Get{{.OptionGetter}}([]string{ {{.IdentifiersGo}} }, occurrence)
		if valueErr != nil {
			deps.Std.Printf("flag '{{.Key}}': %s\n", valueErr.Error())
			return ExitUsage
		}
		entries.{{.GoField}} = append(entries.{{.GoField}}, value)
	}
{{- if .Required}}
	if len(entries.{{.GoField}}) == 0 {
		deps.Std.Printf("required flag '{{.Key}}' not provided\n")
		return ExitUsage
	}
{{- end}}
{{- else}}
	if verb.GetOptionsSize([]string{ {{.IdentifiersGo}} }) > 0 {
		value, valueErr := verb.Get{{.OptionGetter}}([]string{ {{.IdentifiersGo}} }, 0)
		if valueErr != nil {
			deps.Std.Printf("flag '{{.Key}}': %s\n", valueErr.Error())
			return ExitUsage
		}
		entries.{{.GoField}} = value
{{- if .Required}}
	} else {
		deps.Std.Printf("required flag '{{.Key}}' not provided\n")
		return ExitUsage
	}
{{- else if .HasDefault}}
	} else {
		entries.{{.GoField}} = {{.DefaultLiteral}}
	}
{{- else}}
	}
{{- end}}
{{- end}}
{{- end}}
{{- range .Args}}
{{- if .IsArray}}
	for {
		value, valueErr := verb.GetNext{{.ArgGetter}}Arg()
		if valueErr != nil {
			break
		}
		entries.{{.GoField}} = append(entries.{{.GoField}}, value)
	}
{{- if .Required}}
	if len(entries.{{.GoField}}) == 0 {
		deps.Std.Printf("required arg '{{.Key}}' not provided\n")
		return ExitUsage
	}
{{- end}}
{{- else}}
	if value, valueErr := verb.GetNext{{.ArgGetter}}Arg(); valueErr == nil {
		entries.{{.GoField}} = value
{{- if .Required}}
	} else {
		deps.Std.Printf("required arg '{{.Key}}' not provided\n")
		return ExitUsage
	}
{{- else if .HasDefault}}
	} else {
		entries.{{.GoField}} = {{.DefaultLiteral}}
	}
{{- else}}
	}
{{- end}}
{{- end}}
{{- end}}
	return {{.Name}}.CommandHander(deps, entries)
}
{{end}}
