package cli

import (
	"{{.Module}}/sandbox/api"
	"{{.Module}}/sandbox/deps/argvdeps"
	"{{.Module}}/sandbox/internal/config"
{{- range .Commands}}
	{{.Name}} "{{$.Module}}/sandbox/internal/commands/{{.Name}}"
{{- end}}
)

// Exit codes. Kept here (not in sandbox/api) so the cli layer has no
// dependency on the contract package. They mirror sandbox/api: 0 success,
// 1 a well-formed command that failed, 2 a command line that was wrong.
const (
	ExitOk      = 0
	ExitFailure = 1
	ExitUsage   = 2
)

// CliMain is generated by `agnos build` from every
// sandbox/internal/commands/<name>/entries.yaml. It reads the verb, then hands
// the remaining argv to the matching command's generated dispatch function,
// which fills that command's Entries struct and calls its CommandHandler.
// `help` is dispatched through that same path — it is a declared command whose
// three files agnos happens to write itself — and is reached directly only for
// the empty command line below.
func CliMain(sandbox *api.Sandbox, args []string) int {

	if len(args) == 0 {
		help.PrintGeneralHelp(sandbox)
		return ExitUsage
	}

	verb := sandbox.Deps.Argvdeps.New(args)

	action, err := verb.GetNextStringArg()
	if err != nil {
		help.PrintGeneralHelp(sandbox)
		return ExitUsage
	}

	switch {
{{- range .Commands}}
	case {{.MatchExpr}}:
		return dispatch{{.GoName}}(sandbox, verb)
{{- end}}
	}

	sandbox.Deps.Std.Error("unknown command %q — run '%s help' to see the available commands\n", action, binaryName(sandbox))
	return ExitUsage
}

// ─── argv helpers ───────────────────────────────────────────────────────────
//
// Every dispatch function below reads the command line through these, so one
// spelling of every usage error is emitted for the whole CLI.

// binaryName is the executable's name as a user types it: the configured
// project name, lowercased.
func binaryName(sandbox *api.Sandbox) string {
	return sandbox.Deps.Stringsdeps.ToLower(config.ProjectName)
}

// silenceLogs turns off the progress channel for the rest of the process. It
// backs the --quiet flag: results (Printf) and errors (Error) still go out,
// only the "… started with path …" notices stop.
func silenceLogs(sandbox *api.Sandbox) {
	sandbox.Deps.Std.Log = func(format string, a ...any) (int, error) {
		return 0, nil
	}
}

// optionValue reads the occurrence-th value of a value flag, reporting a
// clean usage error when the flag was given with nothing after it.
func optionValue(sandbox *api.Sandbox, verb argvdeps.Parser, name string, flags []string, occurrence int) (string, bool) {
	raw, err := verb.GetStringOption(flags, occurrence)
	if err != nil {
		sandbox.Deps.Std.Error("flag '%s': expected a value after %s\n", name, flags[0])
		return "", false
	}
	return raw, true
}

// nextArgValue drains the next positional argument, reporting whether one was
// left. It never fails on the value itself: parsing is the parse* helpers' job,
// so an unparsable argument is told apart from an exhausted command line.
func nextArgValue(verb argvdeps.Parser) (string, bool) {
	raw, err := verb.GetNextStringArg()
	if err != nil {
		return "", false
	}
	return raw, true
}

// parseStringValue is the string arm of the parse* family. Every raw value is
// already a string, so it only exists to keep the generated dispatch uniform
// across the four field types.
func parseStringValue(sandbox *api.Sandbox, subject string, name string, raw string) (string, bool) {
	return raw, true
}

// parseIntValue converts a raw command-line value to an int, reporting the
// failure in the CLI's own words rather than the parser library's.
func parseIntValue(sandbox *api.Sandbox, subject string, name string, raw string) (int, bool) {
	value, err := sandbox.Deps.Stringsdeps.Atoi(raw)
	if err != nil {
		sandbox.Deps.Std.Error("%s '%s': %q is not a valid integer\n", subject, name, raw)
		return 0, false
	}
	return value, true
}

// parseFloatValue converts a raw command-line value to a float64, reporting
// the failure in the CLI's own words rather than the parser library's.
func parseFloatValue(sandbox *api.Sandbox, subject string, name string, raw string) (float64, bool) {
	value, err := sandbox.Deps.Stringsdeps.ParseFloat(raw, 64)
	if err != nil {
		sandbox.Deps.Std.Error("%s '%s': %q is not a valid number\n", subject, name, raw)
		return 0, false
	}
	return value, true
}

// checkUnknownFlags reports the first argument that still looks like a flag
// after every declared flag has been read — a typo such as --pathh, which
// would otherwise be ignored and leave the command running on a default.
func checkUnknownFlags(sandbox *api.Sandbox, verb argvdeps.Parser) bool {
	for i, used := range verb.Used {
		if used || !sandbox.Deps.Stringsdeps.HasPrefix(verb.Args[i], "-") {
			continue
		}
		sandbox.Deps.Std.Error("unknown flag %q — run '%s help' for the accepted flags\n", verb.Args[i], binaryName(sandbox))
		return false
	}
	return true
}

// checkUnusedArgs reports the first argument left over once every declared
// flag and positional arg has been read.
func checkUnusedArgs(sandbox *api.Sandbox, verb argvdeps.Parser) bool {
	for i, used := range verb.Used {
		if used {
			continue
		}
		sandbox.Deps.Std.Error("unexpected argument %q\n", verb.Args[i])
		return false
	}
	return true
}
{{range .Commands}}
func dispatch{{.GoName}}(sandbox *api.Sandbox, verb argvdeps.Parser) int {
	entries := &{{.Name}}.Entries{}
{{- range .Flags}}
{{- if .IsBool}}
	entries.{{.GoField}} = verb.IsPresent([]string{ {{.IdentifiersGo}} })
{{- else if .IsArray}}
	for occurrence := 0; occurrence < verb.GetOptionsSize([]string{ {{.IdentifiersGo}} }); occurrence++ {
		raw, rawOk := optionValue(sandbox, verb, "{{.Key}}", []string{ {{.IdentifiersGo}} }, occurrence)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := {{.ParseFunc}}(sandbox, "flag", "{{.Key}}", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.{{.GoField}} = append(entries.{{.GoField}}, value)
	}
{{- if .Required}}
	if len(entries.{{.GoField}}) == 0 {
		sandbox.Deps.Std.Error("required flag '{{.Key}}' not provided\n")
		return ExitUsage
	}
{{- end}}
{{- else}}
	if verb.GetOptionsSize([]string{ {{.IdentifiersGo}} }) > 0 {
		raw, rawOk := optionValue(sandbox, verb, "{{.Key}}", []string{ {{.IdentifiersGo}} }, 0)
		if !rawOk {
			return ExitUsage
		}
		value, valueOk := {{.ParseFunc}}(sandbox, "flag", "{{.Key}}", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.{{.GoField}} = value
{{- if .RangeCheck}}
{{.RangeCheck}}
{{- end}}
{{- if .Required}}
	} else {
		sandbox.Deps.Std.Error("required flag '{{.Key}}' not provided\n")
		return ExitUsage
	}
{{- else if .HasDefault}}
	} else {
		entries.{{.GoField}} = {{.DefaultLiteral}}
	}
{{- else}}
	}
{{- end}}
{{- end}}
{{- end}}
{{- if .QuietField}}
	if entries.{{.QuietField}} {
		silenceLogs(sandbox)
	}
{{- end}}
	if !checkUnknownFlags(sandbox, verb) {
		return ExitUsage
	}
{{- range .Args}}
{{- if .IsArray}}
	for {
		raw, rawOk := nextArgValue(verb)
		if !rawOk {
			break
		}
		value, valueOk := {{.ParseFunc}}(sandbox, "arg", "{{.Key}}", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.{{.GoField}} = append(entries.{{.GoField}}, value)
	}
{{- if .Required}}
	if len(entries.{{.GoField}}) == 0 {
		sandbox.Deps.Std.Error("required arg '{{.Key}}' not provided\n")
		return ExitUsage
	}
{{- end}}
{{- else}}
	if raw, rawOk := nextArgValue(verb); rawOk {
		value, valueOk := {{.ParseFunc}}(sandbox, "arg", "{{.Key}}", raw)
		if !valueOk {
			return ExitUsage
		}
		entries.{{.GoField}} = value
{{- if .RangeCheck}}
{{.RangeCheck}}
{{- end}}
{{- if .Required}}
	} else {
		sandbox.Deps.Std.Error("required arg '{{.Key}}' not provided\n")
		return ExitUsage
	}
{{- else if .HasDefault}}
	} else {
		entries.{{.GoField}} = {{.DefaultLiteral}}
	}
{{- else}}
	}
{{- end}}
{{- end}}
{{- end}}
	if !checkUnusedArgs(sandbox, verb) {
		return ExitUsage
	}
	return {{.Name}}.CommandHandler(sandbox, entries)
}
{{end}}
