package set_table_field

import (
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/api"
)

// NewCommand builds this command's declaration — the whole of what its
// entries.yaml says — and closes CommandHandler over the sandbox as the
// handler behind it. It is called once, by sandbox/internal/generated/cli/new.go, and
// what it returns is one entry of Cli.Commands: the declaration alone, which
// the dispatch copies with api.BindCommand before binding a command line onto
// it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewCommand(sandbox *api.Sandbox) api.Command {
	command := api.NewCommand()

	command.Name = "set_table_field"
	command.Identifiers = []string{"set-table-field"}
	command.Category = "Database System"
	command.Help = "Rewrite one declared field of a table"
	command.LongDescription = "Rewrites one declared field in place and runs build. It is add-table-field applied to a declaration that already exists: the keys given are written over the ones there, --clear takes one off, and the result goes through the same constructor — so changing a type never means removing the field and declaring it again."
	command.Examples = []string{"set-table-field link --database app-database --table url --required"}
	command.Hidden = false

	command.Flags = []api.CommandFlag{
		{
			Id:          "database",
			Type:        "string",
			Required:    true,
			Array:       false,
			Description: "the database (identifier or package name) the field is declared on",
			Examples:    []string{"set-table-field alias --database app-database --table url"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--database"},
		},
		{
			Id:          "table",
			Type:        "string",
			Required:    true,
			Array:       false,
			Description: "the table the field is declared on",
			Examples:    []string{"set-table-field alias --database app-database --table url"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--table"},
		},
		{
			Id:          "parent",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the nested database field the field sits inside, instead of the table itself",
			Examples:    []string{"set-table-field agent --database app-database --table url --parent visits"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--parent"},
		},
		{
			Id:          "rename",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the name the field is stored under from now on",
			Examples:    []string{"set-table-field alias --database app-database --table url --rename slug"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--rename"},
		},
		{
			Id:          "type",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the field type it takes on: key, string, int, float, link or database",
			Examples:    []string{"set-table-field redirects --database app-database --table url --type int"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--type"},
		},
		{
			Id:          "required",
			Type:        "boolean",
			Required:    false,
			Array:       false,
			Description: "an insert must carry this field",
			Examples:    []string{"set-table-field link --database app-database --table url --required"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--required"},
		},
		{
			Id:          "target",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the table a link points at (only with --type link)",
			Examples:    []string{"set-table-field owner --database app-database --table url --target user"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--target"},
		},
		{
			Id:          "clear",
			Type:        "string",
			Required:    false,
			Array:       true,
			Description: "a key to take off again: required or target (repeatable)",
			Examples:    []string{"set-table-field link --database app-database --table url --clear required"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--clear"},
		},
		{
			Id:          "path",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the dir holding the project (defaults to the current directory)",
			Examples:    []string{},
			Default:     ".",
			HasDefault:  true,
			Identifiers: []string{"--path"},
		},
		{
			Id:          "quiet",
			Type:        "boolean",
			Required:    false,
			Array:       false,
			Description: "Quiets the cli output",
			Examples:    []string{},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--quiet", "-q"},
		},
	}

	command.Args = []api.CommandArg{
		{
			Id:          "name",
			Type:        "string",
			Required:    true,
			Array:       false,
			Description: "the field to edit, by the name it is declared under",
			Examples:    []string{"set-table-field alias --database app-database --table url --type key"},
			Default:     "",
			HasDefault:  false,
		},
	}

	command.Handler = func(bound *api.Command) int {
		return CommandHandler(sandbox, bound)
	}

	return *command
}
