// Code generated by agnos. DO NOT EDIT.

package set_parameter

// Input is every value this command reads off a command line, one field per
// entry of its command.yaml: FullCommand, the whole command line, then one per
// entry of `args` and one per entry of `flags`, each tagged with the id the
// generic Run fills it by. Handle is handed one,
// already filled.
// Generated by `agnos build` — do not edit by hand.
type Input struct {
	FullCommand       []string `id:"FullCommand"`
	Verb              string   `id:"Verb"`
	Name              string   `id:"Name"`
	Route             string   `id:"Route"`
	Rename            string   `id:"Rename"`
	Type              string   `id:"Type"`
	Source            []string `id:"Source"`
	Required          bool     `id:"Required"`
	Default           string   `id:"Default"`
	Trigger           string   `id:"Trigger"`
	TriggerType       string   `id:"TriggerType"`
	TriggerNegate     bool     `id:"TriggerNegate"`
	TriggerIgnoreCase bool     `id:"TriggerIgnoreCase"`
	Description       string   `id:"Description"`
	Example           []string `id:"Example"`
	Clear             []string `id:"Clear"`
}
