package set_command

import (
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/api"
)

// NewCommand builds this command's declaration — the whole of what its
// entries.yaml says — and closes CommandHandler over the sandbox as the
// handler behind it. It is called once, by sandbox/internal/cli/new.go, and
// what it returns is one entry of Cli.Commands: the declaration alone, which
// the dispatch copies with api.BindCommand before binding a command line onto
// it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewCommand(sandbox *api.Sandbox) api.Command {
	command := api.NewCommand()

	command.Name = "set_command"
	command.Identifiers = []string{"set-command"}
	command.Category = "Cli System"
	command.Help = "Update the command-level keys of a command's entries.yaml"
	command.LongDescription = "Rewrites help, category, long-description and hidden in\nsandbox/internal/commands/<name>/entries.yaml, and appends extra\nidentifiers / examples, then runs build so help output is regenerated.\nKeys not passed are left untouched.\n"
	command.Examples = []string{"set-command exec --help \"run the thing\" --category Core", "set-command exec --identifier run --example \"exec file.txt\"", "set-command exec --hidden"}
	command.Hidden = false

	command.Flags = []api.CommandFlag{
		{
			Id:          "help",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "new one-line help text",
			Examples:    []string{"--help \"run the thing\""},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--help"},
		},
		{
			Id:          "category",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "new category the command is grouped under in help output",
			Examples:    []string{"--category Core"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--category"},
		},
		{
			Id:          "long-description",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "new long description shown by help <command>",
			Examples:    []string{"--long-description \"Runs the thing end to end.\""},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--long-description"},
		},
		{
			Id:          "identifier",
			Type:        "string",
			Required:    false,
			Array:       true,
			Description: "an extra verb the command answers to (repeatable)",
			Examples:    []string{"--identifier run"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--identifier", "-i"},
		},
		{
			Id:          "example",
			Type:        "string",
			Required:    false,
			Array:       true,
			Description: "an extra usage example (repeatable)",
			Examples:    []string{"--example \"exec file.txt\""},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--example", "-e"},
		},
		{
			Id:          "hidden",
			Type:        "boolean",
			Required:    false,
			Array:       false,
			Description: "hide the command from help listings",
			Examples:    []string{},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--hidden"},
		},
		{
			Id:          "visible",
			Type:        "boolean",
			Required:    false,
			Array:       false,
			Description: "show the command in help listings again",
			Examples:    []string{},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--visible"},
		},
		{
			Id:          "path",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the dir holding the project (defaults to the current directory)",
			Examples:    []string{"set-command exec --hidden --path ./my-project"},
			Default:     ".",
			HasDefault:  true,
			Identifiers: []string{"--path"},
		},
		{
			Id:          "quiet",
			Type:        "boolean",
			Required:    false,
			Array:       false,
			Description: "Quiets the cli output",
			Examples:    []string{},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--quiet", "-q"},
		},
	}

	command.Args = []api.CommandArg{
		{
			Id:          "name",
			Type:        "string",
			Required:    true,
			Array:       false,
			Description: "the command to update (identifier or package name)",
			Examples:    []string{"set-command exec --help \"run the thing\""},
			Default:     "",
			HasDefault:  false,
		},
	}

	command.Handler = func(bound *api.Command) int {
		return CommandHandler(sandbox, bound)
	}

	return *command
}
