package compile

import (
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/api"
)

// NewCommand builds this command's declaration — the whole of what its
// entries.yaml says — and closes CommandHandler over the sandbox as the
// handler behind it. It is called once, by sandbox/binds/cli.go, and what it
// returns is one entry of sandbox.Commands.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewCommand(sandbox *api.Sandbox) *api.Command {
	command := api.NewCommand()

	command.Name = "compile"
	command.Identifiers = []string{"compile"}
	command.Category = "Core Commands"
	command.Help = "Cross-compile the project's binaries into release/"
	command.LongDescription = "Runs build over the project and then cross-compiles its ./cmd/main entrypoint once per --target into release/, with CGO disabled. Repeat --target for several targets, or pass --target all to build every one. Targets and their outputs: linux86 -> linux86.out, linuxarm64 -> linuxarm64.out, linuxi32 -> linuxi32.out, mac86 -> mac86.bin, macarm64 -> macarm64.bin, windows86 -> windows86.exe, windowsi32 -> windowsi32.exe."
	command.Examples = []string{"compile --target linux86", "compile --target linux86 --target macarm64", "compile --target all"}
	command.Hidden = false

	command.Flags = []api.CommandFlag{
		{
			Id:          "target",
			Type:        "string",
			Required:    true,
			Array:       true,
			Description: "a target to cross-compile (repeatable); one of linux86, linuxarm64, linuxi32, mac86, macarm64, windows86, windowsi32, or all",
			Examples:    []string{"compile --target linux86 --target windows86"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--target", "-t"},
		},
		{
			Id:          "path",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the dir holding the project (defaults to the current directory)",
			Examples:    []string{"compile --target all --path ./my-project"},
			Default:     ".",
			HasDefault:  true,
			Identifiers: []string{"--path"},
		},
		{
			Id:          "quiet",
			Type:        "boolean",
			Required:    false,
			Array:       false,
			Description: "Quiets the cli output",
			Examples:    []string{"compile --target all -q"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--quiet", "-q"},
		},
	}

	command.Args = []api.CommandArg{}

	command.Handler = func() int {
		return CommandHandler(sandbox, command)
	}

	return command
}
