package {{.Name}}

import (
	"{{.Module}}/sandbox/api"
	"{{.Module}}/sandbox/internal/commandprops"
)

// NewCommand builds this command's declaration — a 1:1 image of its
// command.yaml — on the empty base of Deps.OpinatedAgnosCli.NewCommand, and
// closes InternalPureHandler over the sandbox as the handler behind it. It is
// called once by sandbox/internal/generated/cli/cli/new.go, and what it returns
// is one entry of Cli.Commands: the declaration alone, which the lib's dispatch
// copies before binding a command line onto it.
// Generated by `{{.GeneratorName}} build` — do not edit by hand; the logic
// lives in InternalPureHandler.go.
func NewCommand(sandbox *api.Sandbox) *api.Command {
	self := sandbox.Deps.OpinatedAgnosCli.NewCommand(sandbox.Deps.Argvdeps)

	self.Name = {{printf "%q" .Name}}
	self.Identifiers = []string{ {{range .Identifiers}}{{printf "%q" .}}, {{end}} }
	self.Priority = {{.Priority}}
	self.Segments = {{.Segments}}
	self.Strict = {{.Strict}}
	self.Pattern = {{printf "%q" .Pattern}}
	self.Category = {{printf "%q" .Category}}
	self.Help = {{printf "%q" .Help}}
	self.LongDescription = {{printf "%q" .LongDescription}}
	self.Examples = []string{ {{range .Examples}}{{printf "%q" .}}, {{end}} }
	self.Hidden = {{.Hidden}}

	self.Args = []api.CommandArg{
{{- range .Args}}
		{
			Id:          {{printf "%q" .Id}},
			Start:       {{.Start}},
			End:         {{.End}},
			Type:        {{.Type}},
			Required:    {{.Required}},
			Default:     {{printf "%q" .Default}},
			HasDefault:  {{.HasDefault}},
			Description: {{printf "%q" .Description}},
			Trigger:     {{template "trigger" .Trigger}},
		},
{{- end}}
	}

	self.Flags = []api.CommandFlag{
{{- range .Flags}}
		{
			Id:          {{printf "%q" .Id}},
			Keys:        []string{ {{range .Keys}}{{printf "%q" .}}, {{end}} },
			Type:        {{.Type}},
			Required:    {{.Required}},
			Default:     {{printf "%q" .Default}},
			HasDefault:  {{.HasDefault}},
{{- if .HasMin}}
			Min:         {{.Min}},
			HasMin:      true,
{{- end}}
{{- if .HasMax}}
			Max:         {{.Max}},
			HasMax:      true,
{{- end}}
{{- if .Enum}}
			Enum:        []string{ {{range .Enum}}{{printf "%q" .}}, {{end}} },
{{- end}}
			Pattern:     {{printf "%q" .Pattern}},
			Trigger:     {{template "trigger" .Trigger}},
			Description: {{printf "%q" .Description}},
		},
{{- end}}
	}

	self.InternalPureHandler = func(props *commandprops.CommandProps, entries *Entries, response *api.CommandResponse) error {
		return InternalPureHandler(sandbox, props, entries, response)
	}

	return self
}
{{- define "trigger" -}}
api.Trigger{Exist: {{.Exist}}, Type: {{.Type}}, Value: {{printf "%q" .Value}}{{if .Values}}, Values: []string{ {{range .Values}}{{printf "%q" .}}, {{end}} }{{end}}, Negate: {{.Negate}}, IgnoreCase: {{.IgnoreCase}}}
{{- end -}}
