package {{.Package}}
{{ if .Tables }}
import (
	api "{{.Module}}/sandbox/api"
	databasedeps "{{.Module}}/sandbox/deps/databasedeps"
)
{{ end }}
// This file is generated by `{{.GeneratorName}} build` from database.yaml — do not edit by hand.
//
// Every function takes the sandbox first, the way every function of
// sandbox/internal/ does. A search answers (record, false) when there is
// nothing to find and a write answers an error when something went wrong; no
// stored value is ever asserted into a type without checking, so a malformed
// record is an error rather than a panic.
{{ range .Methods }}
// {{.Name}} {{.Help}}.
func {{.Name}}(sandbox *api.Sandbox, self *{{$.Type}}{{ with .Params }}, {{ . }}{{ end }}) {{.Results}} {
{{- if eq .Kind "add" }}
	schema, err := sandbox.Deps.OpinionatedAgnosDatabase.Schema(self.handle, "{{.Table}}")
	if err != nil {
		return {{.Record}}Record{}, err
	}
	item, failure := schema.NewItem(new{{.Record}}Fields(props))
	if failure != nil {
		return {{.Record}}Record{}, sandbox.Deps.OpinionatedAgnosDatabase.Fail(failure)
	}
	return build{{.Record}}Record(sandbox, item)
{{- else if eq .Kind "findById" }}
	schema, err := sandbox.Deps.OpinionatedAgnosDatabase.Schema(self.handle, "{{.Table}}")
	if err != nil {
		sandbox.Deps.StdDeps.Logf("{{.Name}}: %s \n", err.Error())
		return {{.Record}}Record{}, false
	}
	item, ok := schema.FindById(id)
	if !ok {
		return {{.Record}}Record{}, false
	}
	built, err := build{{.Record}}Record(sandbox, item)
	if err != nil {
		sandbox.Deps.StdDeps.Logf("{{.Name}}: %s \n", err.Error())
		return {{.Record}}Record{}, false
	}
	return built, true
{{- else if eq .Kind "findByKey" }}
	schema, err := sandbox.Deps.OpinionatedAgnosDatabase.Schema(self.handle, "{{.Table}}")
	if err != nil {
		sandbox.Deps.StdDeps.Logf("{{.Name}}: %s \n", err.Error())
		return {{.Record}}Record{}, false
	}
	item, ok := schema.FindByKey("{{.Field}}", value)
	if !ok {
		return {{.Record}}Record{}, false
	}
	built, err := build{{.Record}}Record(sandbox, item)
	if err != nil {
		sandbox.Deps.StdDeps.Logf("{{.Name}}: %s \n", err.Error())
		return {{.Record}}Record{}, false
	}
	return built, true
{{- else if eq .Kind "list" }}
	schema, err := sandbox.Deps.OpinionatedAgnosDatabase.Schema(self.handle, "{{.Table}}")
	if err != nil {
		return nil, err
	}
	items, failure := schema.ListAll()
	if failure != nil {
		return nil, sandbox.Deps.OpinionatedAgnosDatabase.Fail(failure)
	}
	kept := []{{.Record}}Record{}
	for _, item := range items {
		built, err := build{{.Record}}Record(sandbox, item)
		if err != nil {
			return nil, err
		}
		if !match{{.Record}}(sandbox, built, filter) {
			continue
		}
		kept = append(kept, built)
	}
	return kept, nil
{{- else if eq .Kind "page" }}
	schema, err := sandbox.Deps.OpinionatedAgnosDatabase.Schema(self.handle, "{{.Table}}")
	if err != nil {
		return nil, err
	}
	items, failure := schema.List(offset+1, limit)
	if failure != nil {
		return nil, sandbox.Deps.OpinionatedAgnosDatabase.Fail(failure)
	}
	page := []{{.Record}}Record{}
	for _, item := range items {
		built, err := build{{.Record}}Record(sandbox, item)
		if err != nil {
			return nil, err
		}
		page = append(page, built)
	}
	return page, nil
{{- else if eq .Kind "count" }}
	schema, err := sandbox.Deps.OpinionatedAgnosDatabase.Schema(self.handle, "{{.Table}}")
	if err != nil {
		return 0, err
	}
	items, failure := schema.ListAll()
	if failure != nil {
		return 0, sandbox.Deps.OpinionatedAgnosDatabase.Fail(failure)
	}
	return len(items), nil
{{- else if eq .Kind "update" }}
	schema, err := sandbox.Deps.OpinionatedAgnosDatabase.Schema(self.handle, "{{.Table}}")
	if err != nil {
		return err
	}
	item, ok := schema.FindById(id)
	if !ok {
		return sandbox.Deps.StdDeps.Errorf("{{.Table}} %d not found", id)
	}
	return sandbox.Deps.OpinionatedAgnosDatabase.Fail(item.Update("{{.Field}}", value))
{{- else if eq .Kind "remove" }}
	schema, err := sandbox.Deps.OpinionatedAgnosDatabase.Schema(self.handle, "{{.Table}}")
	if err != nil {
		return err
	}
	item, ok := schema.FindById(id)
	if !ok {
		return sandbox.Deps.StdDeps.Errorf("{{.Table}} %d not found", id)
	}
	return sandbox.Deps.OpinionatedAgnosDatabase.Fail(item.Remove())
{{- else if eq .Kind "getLink" }}
	schema, err := sandbox.Deps.OpinionatedAgnosDatabase.Schema(self.handle, "{{.Table}}")
	if err != nil {
		sandbox.Deps.StdDeps.Logf("{{.Name}}: %s \n", err.Error())
		return {{.Record}}Record{}, false
	}
	item, ok := schema.FindById(id)
	if !ok {
		return {{.Record}}Record{}, false
	}
	linked, ok := item.GetLink("{{.Field}}")
	if !ok {
		return {{.Record}}Record{}, false
	}
	built, err := build{{.Record}}Record(sandbox, linked)
	if err != nil {
		sandbox.Deps.StdDeps.Logf("{{.Name}}: %s \n", err.Error())
		return {{.Record}}Record{}, false
	}
	return built, true
{{- else if eq .Kind "addSub" }}
	schema, err := sandbox.Deps.OpinionatedAgnosDatabase.Schema(self.handle, "{{.Table}}")
	if err != nil {
		return {{.Record}}Record{}, err
	}
	parent, ok := schema.FindById(parentId)
	if !ok {
		return {{.Record}}Record{}, sandbox.Deps.StdDeps.Errorf("{{.Table}} %d not found", parentId)
	}
	item, failure := parent.NewSubItem("{{.Field}}", new{{.Record}}Fields(props))
	if failure != nil {
		return {{.Record}}Record{}, sandbox.Deps.OpinionatedAgnosDatabase.Fail(failure)
	}
	return build{{.Record}}Record(sandbox, item)
{{- else if eq .Kind "listSub" }}
	schema, err := sandbox.Deps.OpinionatedAgnosDatabase.Schema(self.handle, "{{.Table}}")
	if err != nil {
		return nil, err
	}
	parent, ok := schema.FindById(parentId)
	if !ok {
		return nil, sandbox.Deps.StdDeps.Errorf("{{.Table}} %d not found", parentId)
	}
	nested := []{{.Record}}Record{}
	for _, item := range parent.ListAll("{{.Field}}") {
		built, err := build{{.Record}}Record(sandbox, item)
		if err != nil {
			return nil, err
		}
		nested = append(nested, built)
	}
	return nested, nil
{{- end }}
}
{{ end }}
{{- range .Records }}
// new{{.Type}}Fields is one insert into {{.Name}} as the stored field map.
func new{{.Type}}Fields(props {{.Type}}Input) map[string]any {
	return map[string]any{
{{- range .Fields }}
		"{{.Name}}": props.{{.Go}},
{{- end }}
	}
}

// build{{.Type}}Record reads one stored {{.Name}} record back into its Go form.
// Every conversion is checked, so a value of the wrong type is an error rather
// than a panic.
func build{{.Type}}Record(sandbox *api.Sandbox, item databasedeps.SchemaItem) ({{.Type}}Record, error) {
	built := {{.Type}}Record{Id: item.Id}
{{- range .Fields }}

	value{{.Go}}, err := sandbox.Deps.OpinionatedAgnosDatabase.{{.Reader}}(item, "{{.Name}}")
	if err != nil {
		return built, err
	}
	built.{{.Go}} = value{{.Go}}
{{- end }}

	return built, nil
}
{{ if .HasFilter }}
// match{{.Type}} is one {{.Type}}Filter applied to one record. A zero value
// never filters, so an empty filter keeps everything.
func match{{.Type}}(sandbox *api.Sandbox, item {{.Type}}Record, filter {{.Type}}Filter) bool {
{{- range .Fields }}
{{- if .IsText }}
	if !sandbox.Deps.OpinionatedAgnosDatabase.TextMatches(item.{{.Go}}, filter.{{.Go}}StartsWith, filter.{{.Go}}Equals) {
		return false
	}
{{- else if .IsInt }}
	if !sandbox.Deps.OpinionatedAgnosDatabase.IntInRange(item.{{.Go}}, filter.{{.Go}}Min, filter.{{.Go}}Max) {
		return false
	}
{{- else }}
	if !sandbox.Deps.OpinionatedAgnosDatabase.FloatInRange(item.{{.Go}}, filter.{{.Go}}Min, filter.{{.Go}}Max) {
		return false
	}
{{- end }}
{{- end }}
	return true
}
{{ end }}
{{- end }}
