{{- define "items" }}
{{- range . }}
{Name: "{{.Name}}", Type: {{.Const}}{{ if .Required }}, Required: true{{ end }}{{ if .Target }}, Target: "{{.Target}}"{{ end }}{{ if .Nested }}, Itens: []databasedeps.Item{ {{- template "items" .Nested -}} }{{ end }}},
{{- end }}
{{- end -}}
package {{.Package}}

import (
	api "{{.Module}}/sandbox/api"
	databasedeps "{{.Module}}/sandbox/deps/databasedeps"
)

// New builds the {{.DatabaseName}} database from the Props its database.yaml declares and
// closes every method of methods.go over it. It touches no key: a database is
// a handle over a prefix, so building one creates nothing until the first
// record is written.
//
// Generated by `{{.GeneratorName}} build` — do not edit by hand.
func New(sandbox *api.Sandbox) *{{.Type}} {
	props := databasedeps.Props{
		Path: "{{.KeyPrefix}}",
		Schemas: []databasedeps.Schema{
{{- range .Tables }}
			{
				Name: "{{.Name}}",
				Itens: []databasedeps.Item{
					{{- template "items" .Items }}
				},
			},
{{- end }}
		},
	}

	self := {{.Type}}{sandbox: sandbox}
	self.handle = sandbox.Deps.DatabaseDeps.Databases.New(props)
{{ range .Methods }}
	self.{{.Name}} = func({{.Params}}) {{.Results}} {
		return {{.Name}}(self.sandbox, &self{{ with .Args }}, {{ . }}{{ end }})
	}
{{- end }}

	return &self
}
