package {{.Package}}

import (
	api "{{.Module}}/sandbox/api"
	database "{{.Module}}/sandbox/deps/database"
)

// This file is generated by `{{.GeneratorName}} build` from specs.yaml — do not edit by hand.
// A query specs.yaml cannot describe goes in {{.CustomFile}}, which no build
// reads and no build rewrites.
{{ range .Records }}
// {{.Type}}Item is one stored {{.Name}} record: its permanent id and every
// plain field the declaration gives it.
type {{.Type}}Item struct {
	Id int64
{{- range .Fields }}
	{{.Go}} {{.GoType}}
{{- end }}
}

// {{.Type}}New is one insert into {{.Name}}: the fields a new record carries.
type {{.Type}}New struct {
{{- range .Fields }}
	{{.Go}} {{.GoType}}
{{- end }}
}
{{ if .HasFiltrage }}
// {{.Type}}Filtrage narrows a List{{.Type}}. Every plain field is here, because
// only a `key` field is indexed and this is the one way to reach the rest. A
// zero value turns its own filter off.
type {{.Type}}Filtrage struct {
{{- range .Fields }}
{{- if .IsText }}
	{{.Go}}StartsWith string
	{{.Go}}Equals     string
{{- else }}
	{{.Go}}Min {{.GoType}}
	{{.Go}}Max {{.GoType}}
{{- end }}
{{- end }}
}
{{ end }}
{{- end }}
// {{.Type}} is the {{.Name}} database: the handle it was built over and one
// function field per generated method. Building one is free — it touches no
// key and creates nothing until the first record is written — so whoever needs
// it calls New on the spot instead of reading it off the Sandbox.
type {{.Type}} struct {
	sandbox *api.Sandbox
	handle  database.DatabaseHandle
{{ range .Methods }}
	// {{.Name}} {{.Help}}.
	{{.Name}} func({{.Params}}) {{.Results}}
{{- end }}
}
