package {{.Name}}

import (
{{- if .HasBody}}
	"{{.Module}}/sandbox/api"
	"{{.Module}}/sandbox/deps"
{{- end}}
{{- if .Body.IsJson}}
	serializables "{{.Module}}/sandbox/deps/serializables"
{{- end}}
	"{{.Module}}/sandbox/deps/serverdeps"
{{- if .HasBody}}
	"{{.Module}}/sandbox/internal/routeio"
{{- end}}
)

// Entries is generated by `agnos build` from this route's route.yaml.
// It is the typed view of the bound request handed to RouteHandler.
// Do not edit by hand — put your logic in handler.go.
// Fields follow route.yaml: the captured path segments first, then the
// headers, then the query parameters, each in the order it is declared there.
// Request is the raw request the dispatch bound them from{{ if .HasBody }}, and what ReadBody
// reads the body through{{ end }}.
type Entries struct {
{{- range .Bindings}}
	{{.GoField}} {{.GoType}}
{{- end}}
	Request serverdeps.Request
{{- if .HasBody}}

	body_read   bool
	body_status int
	body_value  {{.Body.GoType}}
{{- end}}
}
{{- range .BodyStructs}}

// {{.Name}} is one object of this route's declared json-schema, as the
// generated ReadBody hands it over.
type {{.Name}} struct {
{{- range .Fields}}
	{{.GoField}} {{.GoType}}
{{- end}}
}
{{- end}}
{{- if .HasBody}}

// MaxBodyBytes is the largest request body this route reads, from the
// `max-bytes` of its declaration. A longer one is answered 413.
const MaxBodyBytes = {{.Body.MaxBytes}}
{{- end}}
{{- if .SchemaJson}}

// EntriesSchema is this route's declared json-schema in canonical form — the
// text routeio.ValidateSchema checks a request body against.
const EntriesSchema = {{printf "%q" .SchemaJson}}
{{- end}}
{{- if .HasBody}}

// ReadBody reads, validates and converts the request body on the first call
// and caches the outcome for the ones after it. The body is the one part of a
// request the dispatch does not touch, so a handler may refuse a request
// before a byte of it is read.
//
// It returns api.StatusOk when the body passed; on any other status the error
// response has already been written, and the handler only has to return it.
func (entries *Entries) ReadBody(deps *deps.Deps, response serverdeps.Response) ({{.Body.GoType}}, int) {
	if entries.body_read {
		return entries.body_value, entries.body_status
	}
	entries.body_read = true
	entries.body_status = api.StatusOk

	raw, err := entries.Request.ReadBody(MaxBodyBytes)
	if err != nil {
		entries.body_status = routeio.WriteError(deps, response, api.StatusPayloadTooLarge, "",
			"the request body is larger than {{.Body.MaxBytesText}} bytes")
		return entries.body_value, entries.body_status
	}

	if len(raw) == 0 {
{{- if .Body.Required}}
		entries.body_status = routeio.WriteError(deps, response, api.StatusBadRequest, "",
			"this route requires a request body")
{{- end}}
		return entries.body_value, entries.body_status
	}
{{- if .Body.IsRaw}}

	entries.body_value = raw
{{- else if .Body.IsText}}

	entries.body_value = string(raw)
{{- else}}

	parsed, field, message, ok := routeio.ValidateSchema(deps, {{if .SchemaJson}}EntriesSchema{{else}}""{{end}}, raw)
	if !ok {
		entries.body_status = routeio.WriteError(deps, response, api.StatusBadRequest, field, message)
		return entries.body_value, entries.body_status
	}
{{- if .Body.IsObject}}

	entries.body_value = bindBody(parsed)
{{- else}}

	entries.body_value = parsed
{{- end}}
{{- end}}

	return entries.body_value, entries.body_status
}
{{- end}}
{{- range .BodyStructs}}

// bind{{.Name}} converts one already-validated document into {{.Name}}. The
// schema has been enforced by then, so a property that will not read was
// optional and comes back as its zero value.
func bind{{.Name}}(document *serializables.SerializibleObject) {{.Name}} {
	value := {{.Name}}{}
{{- range .Fields}}
{{- if eq .Kind "object"}}
	value.{{.GoField}} = bind{{.StructName}}(routeio.ReadObject(document, "{{.Key}}"))
{{- else if eq .Kind "array"}}
	for _, item := range routeio.ReadItems(document, "{{.Key}}") {
{{- if eq .ItemKind "object"}}
		value.{{.GoField}} = append(value.{{.GoField}}, bind{{.StructName}}(item))
{{- else}}
		value.{{.GoField}} = append(value.{{.GoField}}, routeio.{{.ItemReader}}(item))
{{- end}}
	}
{{- else}}
	value.{{.GoField}} = routeio.{{.Reader}}(document, "{{.Key}}")
{{- end}}
{{- end}}
	return value
}
{{- end}}
