package {{.Name}}
{{- if .HasBody}}

import (
	"{{.Module}}/sandbox/api"
{{- if .Body.IsJson}}
	serializables "{{.Module}}/sandbox/deps/serializables"
{{- end}}
	"{{.Module}}/sandbox/internal/generated/routeio"
)
{{- end}}

// Entries is every value this route reads off a request, one field per entry
// of its route.yaml: FullRoute, the whole request path, then one per entry of
// `paths` and one per entry of `parameters`, then Body when the route declares
// one, each tagged with the id the generic RequestHandler fills it by. InternalPureHandler is handed
// one, already filled.
// Generated by `{{.GeneratorName}} build` — do not edit by hand.
type Entries struct {
	FullRoute string `id:"FullRoute"`
{{- range .Paths}}
	{{.Id}} {{.GoType}} `id:"{{.Id}}"`
{{- end}}
{{- range .Parameters}}
	{{.Id}} {{.GoType}} `id:"{{.Id}}"`
{{- end}}
{{- if .HasBody}}
	Body {{.Body.GoType}} `id:"Body"`
{{- end}}
}
{{- range .BodyStructs}}

// {{.Name}} is one object of this route's declared json-schema, as the
// generated ReadBody hands it over.
type {{.Name}} struct {
{{- range .Fields}}
	{{.GoField}} {{.GoType}}
{{- end}}
}
{{- end}}
{{- if .HasBody}}

// MaxBodyBytes is the largest request body this route reads, from the
// `max-bytes` of its declaration. A longer one is answered 413.
const MaxBodyBytes = {{.Body.MaxBytes}}
{{- end}}
{{- if .SchemaJson}}

// BodySchema is this route's declared json-schema in canonical form — the text
// routeio.ValidateSchema checks a request body against.
const BodySchema = {{printf "%q" .SchemaJson}}
{{- end}}
{{- if .HasBody}}

// ReadBody reads, validates and converts the request body of one bound route.
// The generic RequestHandler calls it — through the ReadBody new.go closes over
// the sandbox — before InternalPureHandler runs, and binds what it returns onto
// Entries.Body; a middleware in front of this route may still refuse a request
// before a byte of it is read.
//
// It returns nil when the body passed. Any other failure has already been
// answered — by this project's own HandleBadRequest or HandleTooLarge, which
// routeio.Raise hands it to — and the handler never runs.
func ReadBody(sandbox *api.Sandbox, route *api.Route) ({{.Body.GoType}}, error) {
	var body {{.Body.GoType}}

	raw, err := routeio.RequestOf(route).ReadBody(MaxBodyBytes)
	if err != nil {
		return body, routeio.RaiseWithCause(sandbox, route, api.StatusPayloadTooLarge, "",
			"the request body is larger than {{.Body.MaxBytesText}} bytes", err.Error())
	}

	if len(raw) == 0 {
{{- if .Body.Required}}
		return body, routeio.Raise(sandbox, route, api.StatusBadRequest, "",
			"this route requires a request body")
{{- else if and .Body.IsObject .SchemaJson}}
		// An absent object is read as an empty one, so a property the
		// schema requires is still reported missing.
		raw = []byte("{}")
{{- else}}
		return body, nil
{{- end}}
	}
{{- if .Body.IsRaw}}

	body = raw
{{- else if .Body.IsText}}

	body = string(raw)
{{- else if .Body.IsForm}}

	form, err := routeio.RequestOf(route).ReadForm(MaxBodyBytes)
	if err != nil {
		return body, routeio.RaiseWithCause(sandbox, route, api.StatusBadRequest, "",
			"the request body is not a valid form", err.Error())
	}
	body = form
{{- else}}

	parsed, field, message, ok := routeio.ValidateSchema(sandbox, {{if .SchemaJson}}BodySchema{{else}}""{{end}}, raw)
	if !ok {
		return body, routeio.Raise(sandbox, route, api.StatusBadRequest, field, message)
	}
{{- if .Body.IsObject}}

	body = bindBody(parsed)
{{- else}}

	body = parsed
{{- end}}
{{- end}}

	return body, nil
}
{{- end}}
{{- range .BodyStructs}}

// bind{{.Name}} converts one already-validated document into {{.Name}}. The
// schema has been enforced by then, so a property that will not read was
// optional and comes back as its zero value.
func bind{{.Name}}(document *serializables.SerializibleObject) {{.Name}} {
	value := {{.Name}}{}
{{- range .Fields}}
{{- if eq .Kind "object"}}
	value.{{.GoField}} = bind{{.StructName}}(routeio.ReadObject(document, "{{.Key}}"))
{{- else if eq .Kind "array"}}
	for _, item := range routeio.ReadItems(document, "{{.Key}}") {
{{- if eq .ItemKind "object"}}
		value.{{.GoField}} = append(value.{{.GoField}}, bind{{.StructName}}(item))
{{- else}}
		value.{{.GoField}} = append(value.{{.GoField}}, routeio.{{.ItemReader}}(item))
{{- end}}
	}
{{- else}}
	value.{{.GoField}} = routeio.{{.Reader}}(document, "{{.Key}}")
{{- end}}
{{- end}}
	return value
}
{{- end}}
