package add_header

import (
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/api"
)

// NewCommand builds this command's declaration — the whole of what its
// entries.yaml says — and closes CommandHandler over the sandbox as the
// handler behind it. It is called once, by sandbox/binds/cli.go, and what it
// returns is one entry of sandbox.Commands.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewCommand(sandbox *api.Sandbox) *api.Command {
	command := api.NewCommand()

	command.Name = "add_header"
	command.Identifiers = []string{"add-header"}
	command.Category = "Server System"
	command.Help = "Declare a request header on a route"
	command.LongDescription = "Declares one request header on a route and runs build so the route's new.go picks it up. The name is the external spelling and is matched without regard to case; the dispatch answers 400 for a missing --required header or one outside --min/--max, before the handler runs."
	command.Examples = []string{"add-header authorization --route create-user --required", "add-header x-retries --route create-user --type int --default 1 --max 5"}
	command.Hidden = false

	command.Flags = []api.CommandFlag{
		{
			Id:          "route",
			Type:        "string",
			Required:    true,
			Array:       false,
			Description: "the route (identifier or package name) that receives the header",
			Examples:    []string{"add-header authorization --route create-user"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--route"},
		},
		{
			Id:          "type",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the value type: string, boolean, int or float (defaults to string)",
			Examples:    []string{"add-header x-retries --route create-user --type int"},
			Default:     "string",
			HasDefault:  true,
			Identifiers: []string{"--type"},
		},
		{
			Id:          "description",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "help text shown for the header",
			Examples:    []string{"add-header authorization --route create-user --description \"the bearer token\""},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--description"},
		},
		{
			Id:          "example",
			Type:        "string",
			Required:    false,
			Array:       true,
			Description: "an usage example for the header (repeatable)",
			Examples:    []string{"add-header authorization --route create-user --example \"Bearer abc\""},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--example"},
		},
		{
			Id:          "default",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the literal assigned when the header is absent (cannot be combined with --required)",
			Examples:    []string{"add-header x-retries --route create-user --type int --default 1"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--default"},
		},
		{
			Id:          "required",
			Type:        "boolean",
			Required:    false,
			Array:       false,
			Description: "answer 400 when the header is not provided (not for booleans or headers with --default)",
			Examples:    []string{"add-header authorization --route create-user --required"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--required"},
		},
		{
			Id:          "min",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "smallest accepted value (int/float only)",
			Examples:    []string{"add-header x-retries --route create-user --type int --min 0"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--min"},
		},
		{
			Id:          "max",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "largest accepted value (int/float only)",
			Examples:    []string{"add-header x-retries --route create-user --type int --max 5"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--max"},
		},
		{
			Id:          "position",
			Type:        "int",
			Required:    false,
			Array:       false,
			Description: "zero-based index to insert the header at (defaults to the end)",
			Examples:    []string{"add-header authorization --route create-user --position 0"},
			Default:     "-1",
			HasDefault:  true,
			Identifiers: []string{"--position"},
		},
		{
			Id:          "path",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the dir holding the project (defaults to the current directory)",
			Examples:    []string{"add-header authorization --route create-user --path ./my-project"},
			Default:     ".",
			HasDefault:  true,
			Identifiers: []string{"--path"},
		},
		{
			Id:          "quiet",
			Type:        "boolean",
			Required:    false,
			Array:       false,
			Description: "Quiets the cli output",
			Examples:    []string{},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--quiet", "-q"},
		},
	}

	command.Args = []api.CommandArg{
		{
			Id:          "name",
			Type:        "string",
			Required:    true,
			Array:       false,
			Description: "the header name, matched without regard to case",
			Examples:    []string{"add-header authorization --route create-user"},
			Default:     "",
			HasDefault:  false,
		},
	}

	command.Handler = func() int {
		return CommandHandler(sandbox, command)
	}

	return command
}
