package server_purge

import (
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/api"
)

// NewCommand builds this command's declaration — the whole of what its
// entries.yaml says — and closes CommandHandler over the sandbox as the
// handler behind it. It is called once, by sandbox/binds/cli.go, and what it
// returns is one entry of sandbox.Commands.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewCommand(sandbox *api.Sandbox) *api.Command {
	command := api.NewCommand()

	command.Name = "server_purge"
	command.Identifiers = []string{"server-purge"}
	command.Category = "Server System"
	command.Help = "Remove the http server layer and every route in it"
	command.LongDescription = "Drops sandbox/internal/{server,routes,routeio} and the start-server command, then re-renders. The cli layer and the installed deps are left in place."
	command.Examples = []string{"server-purge"}
	command.Hidden = false

	command.Flags = []api.CommandFlag{
		{
			Id:          "path",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the dir holding the project (defaults to the current directory)",
			Examples:    []string{"server-purge --path ./my-project"},
			Default:     ".",
			HasDefault:  true,
			Identifiers: []string{"--path"},
		},
		{
			Id:          "quiet",
			Type:        "boolean",
			Required:    false,
			Array:       false,
			Description: "Quiets the cli output",
			Examples:    []string{},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--quiet", "-q"},
		},
	}

	command.Args = []api.CommandArg{}

	command.Handler = func() int {
		return CommandHandler(sandbox, command)
	}

	return command
}
