package add_page

import (
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/api"
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/internal/commandprops"
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/internal/generated/cli/command"
)

// NewCommand builds this command's declaration — a 1:1 image of its
// command.yaml — on the generic base of sandbox/internal/generated/cli/command,
// and closes InternalPureHandler over the sandbox as the handler behind it. It
// is called once by sandbox/internal/generated/cli/cli/new.go, and what it
// returns is one entry of Cli.Commands: the declaration alone, which the
// dispatch copies with api.BindCommand before binding a command line onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in InternalPureHandler.go.
func NewCommand(sandbox *api.Sandbox) *api.Command {
	self := command.NewCommand(sandbox)

	self.Name = "add_page"
	self.Identifiers = []string{"add-page"}
	self.Priority = 100
	self.Segments = 0
	self.Strict = true
	self.Pattern = "add-page <Name>"
	self.Category = "Front System"
	self.Help = "Scaffold a new html page under assets/frontend/"
	self.LongDescription = "Writes assets/frontend/<name>.html, plain html the frontend route serves as soon as it exists: /<name> answers it, and index is the page / answers. A name may carry slashes (blog/post). An existing file is refused. A page is a file and nothing else, so one written by hand or by a bundler is as much a page as one this command scaffolded."
	self.Examples = []string{"add-page about --title About", "add-page blog/post"}
	self.Hidden = false

	self.Args = []api.CommandArg{
		{
			Id:          "Command",
			Start:       0,
			End:         0,
			Type:        api.StringArg,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Description: "",
			Trigger:     api.Trigger{Exist: true, Type: api.EqualTrigger, Value: "add-page", Negate: false, IgnoreCase: false},
		},
		{
			Id:          "Name",
			Start:       1,
			End:         1,
			Type:        api.StringArg,
			Required:    true,
			Default:     "",
			HasDefault:  false,
			Description: "the page, as its path under assets/frontend/ without .html (blog/post; index is the one / answers)",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
		},
	}

	self.Flags = []api.CommandFlag{
		{
			Id:          "Title",
			Keys:        []string{"--title"},
			Type:        api.StringFlag,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "the <title> the scaffolded page carries (defaults to the page name)",
		},
	}

	self.InternalPureHandler = func(props *commandprops.CommandProps, entries *Entries, response *api.CommandResponse) error {
		return InternalPureHandler(sandbox, props, entries, response)
	}

	return self
}
