package set_body_field

import (
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/api"
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/internal/commandprops"
)

// NewCommand builds this command's declaration — a 1:1 image of its
// command.yaml — on the empty base of Deps.OpinionatedAgnosCli.NewCommand, and
// closes Handle over the sandbox as the handler behind it. It is
// called once by sandbox/internal/generated/cli/new.go, and what it returns
// is one entry of Cli.Commands: the declaration alone, which the lib's dispatch
// copies before binding a command line onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewCommand(sandbox *api.Sandbox) *api.Command {
	self := sandbox.Deps.OpinionatedAgnosCli.NewCommand(sandbox.Deps.ArgvDeps)

	self.Name = "set_body_field"
	self.Identifiers = []string{"set-body-field"}
	self.Priority = 100
	self.Segments = 0
	self.Strict = true
	self.Pattern = "set-body-field <Name>"
	self.Category = "Server"
	self.Summary = "Rewrite one property of a route's body json- or form-schema"
	self.Description = "Rewrites one property of the route's body json-schema in place and runs build. The keywords already declared are read back, the ones given are written over them, and the whole is built again by the constructor add-body-field uses — so the property a forgotten --max is added to is the property that was there. --clear takes a keyword off again, and a --type the old keywords cannot survive drops them, naming each one it dropped. A property that is not declared yet is add-body-field's."
	self.Examples = []string{"set-body-field age --route create-user --type int --min 0 --max 130"}
	self.Hidden = false

	self.Args = []api.CommandArg{
		{
			Id:          "Verb",
			Start:       0,
			End:         0,
			Type:        api.ArgString,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Description: "",
			Trigger:     api.Trigger{Set: true, Type: api.TriggerEqual, Value: "set-body-field", Negate: false, IgnoreCase: false},
		},
		{
			Id:          "Name",
			Start:       1,
			End:         1,
			Type:        api.ArgString,
			Required:    true,
			Default:     "",
			HasDefault:  false,
			Description: "the dotted path of the property to edit (address.city)",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
		},
	}

	self.Flags = []api.CommandFlag{
		{
			Id:          "Route",
			Keys:        []string{"--route"},
			Type:        api.FlagString,
			Required:    true,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "the route (identifier or package name) the property is declared on",
		},
		{
			Id:          "Rename",
			Keys:        []string{"--rename"},
			Type:        api.FlagString,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "the key the property answers to from now on (it stays in the object it is declared in)",
		},
		{
			Id:          "Type",
			Keys:        []string{"--type"},
			Type:        api.FlagString,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "the value type: string, boolean, int, float or object",
		},
		{
			Id:          "Required",
			Keys:        []string{"--required"},
			Type:        api.FlagBoolean,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "list the property in its parent object's required set",
		},
		{
			Id:          "Array",
			Keys:        []string{"--array"},
			Type:        api.FlagBoolean,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "declare an array of the type instead of a single value",
		},
		{
			Id:          "Min",
			Keys:        []string{"--min"},
			Type:        api.FlagString,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "minimum for a number, minLength for a string",
		},
		{
			Id:          "Max",
			Keys:        []string{"--max"},
			Type:        api.FlagString,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "maximum for a number, maxLength for a string",
		},
		{
			Id:          "ExclusiveMin",
			Keys:        []string{"--exclusive-min"},
			Type:        api.FlagString,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "exclusiveMinimum for a number property",
		},
		{
			Id:          "ExclusiveMax",
			Keys:        []string{"--exclusive-max"},
			Type:        api.FlagString,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "exclusiveMaximum for a number property",
		},
		{
			Id:          "Format",
			Keys:        []string{"--format"},
			Type:        api.FlagString,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "json-schema format for a string property: email, uuid, date-time or uri",
		},
		{
			Id:          "Pattern",
			Keys:        []string{"--pattern"},
			Type:        api.FlagString,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "regular expression a string property must match",
		},
		{
			Id:          "Enum",
			Keys:        []string{"--enum"},
			Type:        api.FlagStringArray,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "an accepted value of the property (repeatable; replaces the enum set)",
		},
		{
			Id:          "Const",
			Keys:        []string{"--const"},
			Type:        api.FlagString,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "the single value the property must carry",
		},
		{
			Id:          "Nullable",
			Keys:        []string{"--nullable"},
			Type:        api.FlagBoolean,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "accept null as well as the declared type",
		},
		{
			Id:          "MinItems",
			Keys:        []string{"--min-items"},
			Type:        api.FlagString,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "shortest accepted array (an array property only)",
		},
		{
			Id:          "MaxItems",
			Keys:        []string{"--max-items"},
			Type:        api.FlagString,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "longest accepted array (an array property only)",
		},
		{
			Id:          "UniqueItems",
			Keys:        []string{"--unique-items"},
			Type:        api.FlagBoolean,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "refuse an array holding the same value twice (an array property only)",
		},
		{
			Id:          "AdditionalProperties",
			Keys:        []string{"--additional-properties"},
			Type:        api.FlagBoolean,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "accept undeclared keys inside an object property",
		},
		{
			Id:          "NoAdditionalProperties",
			Keys:        []string{"--no-additional-properties"},
			Type:        api.FlagBoolean,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "refuse undeclared keys inside an object property",
		},
		{
			Id:          "Clear",
			Keys:        []string{"--clear"},
			Type:        api.FlagStringArray,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "a keyword to take off again: required, array, min, max, format, pattern, enum, const, nullable and the rest (repeatable)",
		},
	}

	self.Handle = func(props *commandprops.CommandProps, input *Input, response *api.CommandResponse) error {
		return Handle(sandbox, props, input, response)
	}

	return self
}
