package add_parameter

import (
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/api"
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/internal/commandprops"
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/internal/generated/cli/command"
)

// NewCommand builds this command's declaration — a 1:1 image of its
// command.yaml — on the generic base of sandbox/internal/generated/cli/command,
// and closes InternalPureHandler over the sandbox as the handler behind it. It
// is called once by sandbox/internal/generated/cli/cli/new.go, and what it
// returns is one entry of Cli.Commands: the declaration alone, which the
// dispatch copies with api.BindCommand before binding a command line onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in InternalPureHandler.go.
func NewCommand(sandbox *api.Sandbox) *api.Command {
	self := command.NewCommand(sandbox)

	self.Name = "add_parameter"
	self.Identifiers = []string{"add-parameter"}
	self.Priority = 100
	self.Segments = 0
	self.Strict = true
	self.Pattern = "add-parameter <Name>"
	self.Category = "Server System"
	self.Help = "Declare one value a route reads from the query string or the headers"
	self.LongDescription = "Declares one value a route reads and runs build so the route's new.go and entries.go pick it up. It is read under its name from the first of its --font that brings it, converted to its --type and bound to Entries.<Name>; a missing --required one is answered 400 before the handler runs, and one with a --trigger only lets the route run when it matches."
	self.Examples = []string{"add-parameter page --route list-users --type number --default 1", "add-parameter authorization --route admin --font header --trigger Bearer --trigger-type prefix"}
	self.Hidden = false

	self.Args = []api.CommandArg{
		{
			Id:          "Command",
			Start:       0,
			End:         0,
			Type:        api.StringArg,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Description: "",
			Trigger:     api.Trigger{Exist: true, Type: api.EqualTrigger, Value: "add-parameter", Negate: false, IgnoreCase: false},
		},
		{
			Id:          "Name",
			Start:       1,
			End:         1,
			Type:        api.StringArg,
			Required:    true,
			Default:     "",
			HasDefault:  false,
			Description: "the query key or header name it is read under; its Entries field is the exported spelling of it",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
		},
	}

	self.Flags = []api.CommandFlag{
		{
			Id:          "Route",
			Keys:        []string{"--route"},
			Type:        api.StringFlag,
			Required:    true,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "the route (identifier or package name) that receives the parameter",
		},
		{
			Id:          "Type",
			Keys:        []string{"--type"},
			Type:        api.StringFlag,
			Required:    false,
			Default:     "string",
			HasDefault:  true,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "the value type: string, integer, number, boolean, datetime, string-array or integer-array (defaults to string)",
		},
		{
			Id:          "Font",
			Keys:        []string{"--font"},
			Type:        api.StringArrayFlag,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "where the value is read from, in order: query, header or cookie (repeatable; defaults to query)",
		},
		{
			Id:          "Required",
			Keys:        []string{"--required"},
			Type:        api.BooleanFlag,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "answer 400 when no font brings the value (not for booleans or parameters with --default)",
		},
		{
			Id:          "Default",
			Keys:        []string{"--default"},
			Type:        api.StringFlag,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "the literal bound when no font brings the value (cannot be combined with --required)",
		},
		{
			Id:          "Trigger",
			Keys:        []string{"--trigger"},
			Type:        api.StringFlag,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "what the value has to match for the route to run at all, putting the parameter into what the route matches on",
		},
		{
			Id:          "TriggerType",
			Keys:        []string{"--trigger-type"},
			Type:        api.StringFlag,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "how the trigger is compared: equal, prefix, text-prefix, suffix or regex — or starts-with, ends-with, exact, matches (defaults to equal; on a value, prefix and text-prefix are the same)",
		},
		{
			Id:          "TriggerNegate",
			Keys:        []string{"--trigger-negate"},
			Type:        api.BooleanFlag,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "invert the trigger: the route runs when the value does not match it",
		},
		{
			Id:          "TriggerIgnoreCase",
			Keys:        []string{"--trigger-ignore-case"},
			Type:        api.BooleanFlag,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "compare the trigger without regard to case",
		},
		{
			Id:          "Description",
			Keys:        []string{"--description"},
			Type:        api.StringFlag,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "help text shown for the parameter",
		},
		{
			Id:          "Example",
			Keys:        []string{"--example"},
			Type:        api.StringArrayFlag,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "an usage example for the parameter (repeatable)",
		},
		{
			Id:          "Position",
			Keys:        []string{"--position"},
			Type:        api.IntegerFlag,
			Required:    false,
			Default:     "-1",
			HasDefault:  true,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "zero-based index to insert the parameter at (defaults to the end)",
		},
	}

	self.InternalPureHandler = func(props *commandprops.CommandProps, entries *Entries, response *api.CommandResponse) error {
		return InternalPureHandler(sandbox, props, entries, response)
	}

	return self
}
