package add_dep

import (
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/api"
)

// NewCommand builds this command's declaration — the whole of what its
// entries.yaml says — and closes CommandHandler over the sandbox as the
// handler behind it. It is called once, by sandbox/internal/generated/cli/new.go, and
// what it returns is one entry of Cli.Commands: the declaration alone, which
// the dispatch copies with api.BindCommand before binding a command line onto
// it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewCommand(sandbox *api.Sandbox) api.Command {
	command := api.NewCommand()

	command.Name = "add_dep"
	command.Identifiers = []string{"add-dep"}
	command.Category = "Deps System"
	command.Help = "Installs one dep of the embedded catalog into the project"
	command.LongDescription = "Renders the contract of assets/deplist/<dep> and the adapter that fills it, then calls build. The adapter is the dep's default-adapter unless --adapter names another; it is enrolled in every available."
	command.Examples = []string{"add-dep embeddeps", "add-dep embeddeps --path ./my-project"}
	command.Hidden = false

	command.Flags = []api.CommandFlag{
		{
			Id:          "adapter",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the adapter to fill the dep's contract with (defaults to the dep's default-adapter)",
			Examples:    []string{"add-dep sortdeps --adapter reflectsort"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--adapter"},
		},
		{
			Id:          "path",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the dir holding the project (defaults to the current directory)",
			Examples:    []string{"add-dep --path ./my-project"},
			Default:     ".",
			HasDefault:  true,
			Identifiers: []string{"--path"},
		},
		{
			Id:          "quiet",
			Type:        "boolean",
			Required:    false,
			Array:       false,
			Description: "Quiets the cli output",
			Examples:    []string{"add-dep embeddeps -q"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--quiet", "-q"},
		},
		{
			Id:          "as",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the name the copied contract takes under sandbox/deps/ (remote deps only; defaults to the last segment of the module path)",
			Examples:    []string{"add-dep github.com/user/MathLib@v1.2.0 --as mathlib"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--as"},
		},
		{
			Id:          "remote-available",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the available of the remote repo the generated shim builds its sandbox from",
			Examples:    []string{"add-dep github.com/user/MathLib@v1.2.0 --remote-available standard"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--remote-available"},
		},
	}

	command.Args = []api.CommandArg{
		{
			Id:          "dep",
			Type:        "string",
			Required:    true,
			Array:       false,
			Description: "the dep to install from assets/deplist",
			Examples:    []string{"add-dep embeddeps"},
			Default:     "",
			HasDefault:  false,
		},
	}

	command.Handler = func(bound *api.Command) int {
		return CommandHandler(sandbox, bound)
	}

	return *command
}
