package add_param

import (
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/api"
)

// NewCommand builds this command's declaration — the whole of what its
// entries.yaml says — and closes CommandHandler over the sandbox as the
// handler behind it. It is called once, by sandbox/internal/cli/new.go, and
// what it returns is one entry of Cli.Commands: the declaration alone, which
// the dispatch copies with api.BindCommand before binding a command line onto
// it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewCommand(sandbox *api.Sandbox) api.Command {
	command := api.NewCommand()

	command.Name = "add_param"
	command.Identifiers = []string{"add-param"}
	command.Category = "Server System"
	command.Help = "Declare a query parameter on a route"
	command.LongDescription = "Declares one query-string parameter on a route and runs build so the route's new.go picks it up. --array collects every occurrence of the key, read back with GetStrings; the only other place it is accepted is the last segment of a route's paths, which takes the rest of the path."
	command.Examples = []string{"add-param page --route list-users --type int --default 1 --min 1", "add-param tag --route list-users --array"}
	command.Hidden = false

	command.Flags = []api.CommandFlag{
		{
			Id:          "route",
			Type:        "string",
			Required:    true,
			Array:       false,
			Description: "the route (identifier or package name) that receives the parameter",
			Examples:    []string{"add-param page --route list-users"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--route"},
		},
		{
			Id:          "type",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the value type: string, boolean, int or float (defaults to string)",
			Examples:    []string{"add-param page --route list-users --type int"},
			Default:     "string",
			HasDefault:  true,
			Identifiers: []string{"--type"},
		},
		{
			Id:          "description",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "help text shown for the parameter",
			Examples:    []string{"add-param page --route list-users --description \"the page to read\""},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--description"},
		},
		{
			Id:          "example",
			Type:        "string",
			Required:    false,
			Array:       true,
			Description: "an usage example for the parameter (repeatable)",
			Examples:    []string{"add-param page --route list-users --example \"?page=2\""},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--example"},
		},
		{
			Id:          "default",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the literal assigned when the parameter is absent (cannot be combined with --required)",
			Examples:    []string{"add-param page --route list-users --type int --default 1"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--default"},
		},
		{
			Id:          "required",
			Type:        "boolean",
			Required:    false,
			Array:       false,
			Description: "answer 400 when the parameter is not provided (not for booleans or parameters with --default)",
			Examples:    []string{"add-param query --route list-users --required"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--required"},
		},
		{
			Id:          "array",
			Type:        "boolean",
			Required:    false,
			Array:       false,
			Description: "collect every occurrence into a []T field instead of a single value",
			Examples:    []string{"add-param tag --route list-users --array"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--array"},
		},
		{
			Id:          "min",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "smallest accepted value (int/float only)",
			Examples:    []string{"add-param page --route list-users --type int --min 1"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--min"},
		},
		{
			Id:          "max",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "largest accepted value (int/float only)",
			Examples:    []string{"add-param page --route list-users --type int --max 100"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--max"},
		},
		{
			Id:          "position",
			Type:        "int",
			Required:    false,
			Array:       false,
			Description: "zero-based index to insert the parameter at (defaults to the end)",
			Examples:    []string{"add-param page --route list-users --position 0"},
			Default:     "-1",
			HasDefault:  true,
			Identifiers: []string{"--position"},
		},
		{
			Id:          "path",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the dir holding the project (defaults to the current directory)",
			Examples:    []string{"add-param page --route list-users --path ./my-project"},
			Default:     ".",
			HasDefault:  true,
			Identifiers: []string{"--path"},
		},
		{
			Id:          "quiet",
			Type:        "boolean",
			Required:    false,
			Array:       false,
			Description: "Quiets the cli output",
			Examples:    []string{},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--quiet", "-q"},
		},
		{
			Id:          "identifier",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "match only when the request brings exactly this value, putting the field into what the route matches on",
			Examples:    []string{"add-param mode --route debug --identifier verbose"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--identifier"},
		},
		{
			Id:          "starts-with",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "match only when the value the request brings begins with this, putting the field into what the route matches on",
			Examples:    []string{"add-param mode --route debug --starts-with verb"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--starts-with"},
		},
	}

	command.Args = []api.CommandArg{
		{
			Id:          "name",
			Type:        "string",
			Required:    true,
			Array:       false,
			Description: "the query key",
			Examples:    []string{"add-param page --route list-users"},
			Default:     "",
			HasDefault:  false,
		},
	}

	command.Handler = func(bound *api.Command) int {
		return CommandHandler(sandbox, bound)
	}

	return *command
}
