package backoffice_init

import (
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/api"
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/internal/commandprops"
)

// NewCommand builds this command's declaration — a 1:1 image of its
// command.yaml — on the empty base of Deps.OpinatedAgnosCli.NewCommand, and
// closes InternalPureHandler over the sandbox as the handler behind it. It is
// called once by sandbox/internal/generated/cli/cli/new.go, and what it returns
// is one entry of Cli.Commands: the declaration alone, which the lib's dispatch
// copies before binding a command line onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in InternalPureHandler.go.
func NewCommand(sandbox *api.Sandbox) *api.Command {
	self := sandbox.Deps.OpinatedAgnosCli.NewCommand(sandbox.Deps.Argvdeps)

	self.Name = "backoffice_init"
	self.Identifiers = []string{"backoffice-init"}
	self.Priority = 100
	self.Segments = 0
	self.Strict = true
	self.Pattern = "backoffice-init"
	self.Category = "Backoffice System"
	self.Help = "Add the admin backoffice to the project"
	self.LongDescription = "Writes the admin backoffice into the project: the /admin pages (login, home, backoffice users, API tokens), the /api/admin JSON api, the client-ip, security-headers and same-origin middlewares, the backofficedb database, the add-backoffice-user command and the backoffice-server middleware in front of start-server. The server, front and database layers are installed first when any is missing, and so are the catalog deps the backoffice calls into (envdeps, jwtdeps, passworddeps, randdeps, ratelimitdeps, timedeps). Every file it writes is the project's from then on: a second backoffice-init keeps each one already there. Nothing the project wrote is edited: the backoffice's part of RouteProps and of api.Config are files of their own. start-server then reads the session secret from <NAME>_SECRET, the project's name upper-cased (MEUSITE_SECRET for meusite), and generates one for the run when it is unset."
	self.Examples = []string{"backoffice-init", "backoffice-init --path ./my-project"}
	self.Hidden = false

	self.Args = []api.CommandArg{
		{
			Id:          "Command",
			Start:       0,
			End:         0,
			Type:        api.StringArg,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Description: "",
			Trigger:     api.Trigger{Exist: true, Type: api.EqualTrigger, Value: "backoffice-init", Negate: false, IgnoreCase: false},
		},
	}

	self.Flags = []api.CommandFlag{}

	self.InternalPureHandler = func(props *commandprops.CommandProps, entries *Entries, response *api.CommandResponse) error {
		return InternalPureHandler(sandbox, props, entries, response)
	}

	return self
}
