package set_arg

// Entries is every value this command reads off a command line, one field per
// entry of its command.yaml: FullCommand, the whole command line, then one per
// entry of `args` and one per entry of `flags`, each tagged with the id the
// generic CommandHandler fills it by. InternalPureHandler is handed one,
// already filled.
// Generated by `agnos build` — do not edit by hand.
type Entries struct {
	FullCommand       []string `id:"FullCommand"`
	Command           string   `id:"Command"`
	Name              string   `id:"Name"`
	Target            string   `id:"Target"`
	Rename            string   `id:"Rename"`
	Start             string   `id:"Start"`
	End               string   `id:"End"`
	Type              string   `id:"Type"`
	Required          bool     `id:"Required"`
	Default           string   `id:"Default"`
	Trigger           string   `id:"Trigger"`
	TriggerType       string   `id:"TriggerType"`
	TriggerNegate     bool     `id:"TriggerNegate"`
	TriggerIgnoreCase bool     `id:"TriggerIgnoreCase"`
	Description       string   `id:"Description"`
	Clear             []string `id:"Clear"`
}
