package add_body_field

// Entries is every value this command reads off a command line, one field per
// entry of its command.yaml: FullCommand, the whole command line, then one per
// entry of `args` and one per entry of `flags`, each tagged with the id the
// generic CommandHandler fills it by. InternalPureHandler is handed one,
// already filled.
// Generated by `agnos build` — do not edit by hand.
type Entries struct {
	FullCommand            []string `id:"FullCommand"`
	Command                string   `id:"Command"`
	Name                   string   `id:"Name"`
	Route                  string   `id:"Route"`
	Type                   string   `id:"Type"`
	Required               bool     `id:"Required"`
	Array                  bool     `id:"Array"`
	Min                    string   `id:"Min"`
	Max                    string   `id:"Max"`
	ExclusiveMin           string   `id:"ExclusiveMin"`
	ExclusiveMax           string   `id:"ExclusiveMax"`
	Format                 string   `id:"Format"`
	Pattern                string   `id:"Pattern"`
	Enum                   []string `id:"Enum"`
	Const                  string   `id:"Const"`
	Nullable               bool     `id:"Nullable"`
	MinItems               string   `id:"MinItems"`
	MaxItems               string   `id:"MaxItems"`
	UniqueItems            bool     `id:"UniqueItems"`
	AdditionalProperties   bool     `id:"AdditionalProperties"`
	NoAdditionalProperties bool     `id:"NoAdditionalProperties"`
}
