package remove_table_field

import (
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/api"
)

// NewCommand builds this command's declaration — the whole of what its
// entries.yaml says — and closes CommandHandler over the sandbox as the
// handler behind it. It is called once, by sandbox/internal/cli/new.go, and
// what it returns is one entry of Cli.Commands: the declaration alone, which
// the dispatch copies with api.BindCommand before binding a command line onto
// it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewCommand(sandbox *api.Sandbox) api.Command {
	command := api.NewCommand()

	command.Name = "remove_table_field"
	command.Identifiers = []string{"remove-table-field"}
	command.Category = "Database System"
	command.Help = "Delete one declared field from a table"
	command.LongDescription = "Drops one field from a table of the database's specs.yaml and runs build without compiling: the methods that field generated go with it, and hand-written code may still be calling one."
	command.Examples = []string{"remove-table-field redirects --database app-database --table url"}
	command.Hidden = false

	command.Flags = []api.CommandFlag{
		{
			Id:          "database",
			Type:        "string",
			Required:    true,
			Array:       false,
			Description: "the database (identifier or package name) the field is declared on",
			Examples:    []string{"remove-table-field redirects --database app-database --table url"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--database"},
		},
		{
			Id:          "table",
			Type:        "string",
			Required:    true,
			Array:       false,
			Description: "the table the field is declared on",
			Examples:    []string{"remove-table-field redirects --database app-database --table url"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--table"},
		},
		{
			Id:          "parent",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the nested database field the field sits inside, instead of the table itself",
			Examples:    []string{"remove-table-field agent --database app-database --table url --parent visits"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--parent"},
		},
		{
			Id:          "path",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the dir holding the project (defaults to the current directory)",
			Examples:    []string{},
			Default:     ".",
			HasDefault:  true,
			Identifiers: []string{"--path"},
		},
		{
			Id:          "quiet",
			Type:        "boolean",
			Required:    false,
			Array:       false,
			Description: "Quiets the cli output",
			Examples:    []string{},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--quiet", "-q"},
		},
	}

	command.Args = []api.CommandArg{
		{
			Id:          "name",
			Type:        "string",
			Required:    true,
			Array:       false,
			Description: "the field to delete, by the name it is declared under",
			Examples:    []string{"remove-table-field redirects --database app-database --table url"},
			Default:     "",
			HasDefault:  false,
		},
	}

	command.Handler = func(bound *api.Command) int {
		return CommandHandler(sandbox, bound)
	}

	return *command
}
