package verify

import (
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/api"
)

// NewCommand builds this command's declaration — the whole of what its
// entries.yaml says — and closes CommandHandler over the sandbox as the
// handler behind it. It is called once, by sandbox/binds/cli.go, and what it
// returns is one entry of sandbox.Commands.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewCommand(sandbox *api.Sandbox) *api.Command {
	command := api.NewCommand()

	command.Name = "verify"
	command.Identifiers = []string{"verify"}
	command.Category = "Core Commands"
	command.Help = "Checks the project keeps the sandbox/adapter schema"
	command.LongDescription = "Verifies the structural rules the harness depends on: sandbox/ imports\nstay inside sandbox/, sandbox/ holds only api, binds, deps, internal and\nnew.go, sandbox/api imports nothing but sandbox/deps and sandbox/deps\nimports nothing external, every sandbox/binds file mirrors a sandbox/api\nfile and declares only functions, and adapters/ holds only availables and\nlibs. `agnos build` runs this as a gate unless --unsafe is passed."
	command.Examples = []string{"verify"}
	command.Hidden = false

	command.Flags = []api.CommandFlag{
		{
			Id:          "path",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the dir holding the project (defaults to the current directory)",
			Examples:    []string{"verify --path ./my-project"},
			Default:     ".",
			HasDefault:  true,
			Identifiers: []string{"--path"},
		},
		{
			Id:          "runtime",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the toolchain the project is handed to after the schema check: go (tidy + compile) or none",
			Examples:    []string{"verify --runtime none"},
			Default:     "go",
			HasDefault:  true,
			Identifiers: []string{"--runtime"},
		},
		{
			Id:          "quiet",
			Type:        "boolean",
			Required:    false,
			Array:       false,
			Description: "Quiets the cli output",
			Examples:    []string{"verify -q"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--quiet", "-q"},
		},
	}

	command.Args = []api.CommandArg{}

	command.Handler = func() int {
		return CommandHandler(sandbox, command)
	}

	return command
}
