package add_page

import (
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/api"
)

// NewCommand builds this command's declaration — the whole of what its
// entries.yaml says — and closes CommandHandler over the sandbox as the
// handler behind it. It is called once, by sandbox/binds/cli.go, and what it
// returns is one entry of sandbox.Commands.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewCommand(sandbox *api.Sandbox) *api.Command {
	command := api.NewCommand()

	command.Name = "add_page"
	command.Identifiers = []string{"add-page"}
	command.Category = "Front System"
	command.Help = "Declare a new html page"
	command.LongDescription = "Declares the route that answers the page and writes the html template it renders under assets/frontend/pages/. The trigger defaults to /<name>; --trigger / declares the home page. An html file already there is kept, which is the way back from a front-purge."
	command.Examples = []string{"add-page home --trigger / --title Home", "add-page about --title About"}
	command.Hidden = false

	command.Flags = []api.CommandFlag{
		{
			Id:          "path",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the dir holding the project (defaults to the current directory)",
			Examples:    []string{},
			Default:     ".",
			HasDefault:  true,
			Identifiers: []string{"--path"},
		},
		{
			Id:          "quiet",
			Type:        "boolean",
			Required:    false,
			Array:       false,
			Description: "Quiets the cli output",
			Examples:    []string{},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--quiet", "-q"},
		},
		{
			Id:          "trigger",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the literal segment the page answers on, / included (defaults to /<name>)",
			Examples:    []string{},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--trigger"},
		},
		{
			Id:          "title",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the <title> the scaffolded page carries (defaults to the page name)",
			Examples:    []string{},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--title"},
		},
		{
			Id:          "help",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "one-line description of the page, for docs/Routes (defaults to one derived from the name)",
			Examples:    []string{},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--help"},
		},
	}

	command.Args = []api.CommandArg{
		{
			Id:          "name",
			Type:        "string",
			Required:    true,
			Array:       false,
			Description: "the page name (becomes the route, its Go package and the html file)",
			Examples:    []string{},
			Default:     "",
			HasDefault:  false,
		},
	}

	command.Handler = func() int {
		return CommandHandler(sandbox, command)
	}

	return command
}
