// Code generated by agnos. DO NOT EDIT.

package set_route

// Input is every value this command reads off a command line, one field per
// entry of its command.yaml: FullCommand, the whole command line, then one per
// entry of `args` and one per entry of `flags`, each tagged with the id the
// generic Run fills it by. Handle is handed one,
// already filled.
// Generated by `agnos build` — do not edit by hand.
type Input struct {
	FullCommand  []string `id:"FullCommand"`
	Verb         string   `id:"Verb"`
	Name         string   `id:"Name"`
	Method       []string `id:"Method"`
	ResponseType string   `id:"ResponseType"`
	Summary      string   `id:"Summary"`
	Category     string   `id:"Category"`
	Description  string   `id:"Description"`
	Hidden       bool     `id:"Hidden"`
	Visible      bool     `id:"Visible"`
	Priority     int      `id:"Priority"`
	Before       string   `id:"Before"`
	After        string   `id:"After"`
	Segments     int      `id:"Segments"`
	Clear        []string `id:"Clear"`
	Example      []string `id:"Example"`
	Private      bool     `id:"Private"`
	Public       bool     `id:"Public"`
}
