package start

import (
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/api"
)

// NewCommand builds this command's declaration — the whole of what its
// entries.yaml says — and closes CommandHandler over the sandbox as the
// handler behind it. It is called once, by sandbox/binds/cli.go, and what it
// returns is one entry of sandbox.Commands.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewCommand(sandbox *api.Sandbox) *api.Command {
	command := api.NewCommand()

	command.Name = "start"
	command.Identifiers = []string{"start"}
	command.Category = "Core Commands"
	command.Help = "Initialize a new project in a directory"
	command.LongDescription = "Scaffolds a new Agnos project in the given directory, creating\nthe required configuration files and folder structure. If no\npath is provided, the current directory is used.\n"
	command.Examples = []string{"start -p my-project", "start -p my-project --path ./my-project-dir", "start -p my-project -q"}
	command.Hidden = false

	command.Flags = []api.CommandFlag{
		{
			Id:          "path",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the dir holding the project (defaults to the current directory)",
			Examples:    []string{"start --path ./my-project"},
			Default:     ".",
			HasDefault:  true,
			Identifiers: []string{"--path"},
		},
		{
			Id:          "project-name",
			Type:        "string",
			Required:    true,
			Array:       false,
			Description: "the name of the project",
			Examples:    []string{"start -p my-project"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--project-name", "-p"},
		},
		{
			Id:          "quiet",
			Type:        "boolean",
			Required:    false,
			Array:       false,
			Description: "Quiets the cli output",
			Examples:    []string{"start -q"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--quiet", "-q"},
		},
		{
			Id:          "force",
			Type:        "boolean",
			Required:    false,
			Array:       false,
			Description: "Forces the creation of the project, overwriting existing files",
			Examples:    []string{"start -f"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--force", "-f"},
		},
		{
			Id:          "module",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the go module path written into go.mod (required when the target dir has no go.mod yet)",
			Examples:    []string{"start -m github.com/user/project"},
			Default:     "",
			HasDefault:  false,
			Identifiers: []string{"--module", "-m"},
		},
	}

	command.Args = []api.CommandArg{}

	command.Handler = func() int {
		return CommandHandler(sandbox, command)
	}

	return command
}
