package set_flag

import (
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/api"
	"github.com/MateusMoutinhoOrg/Agnos/sandbox/internal/generated/cli/command"
)

// NewCommand builds this command's declaration — a 1:1 image of its
// command.yaml — on the generic base of sandbox/internal/generated/cli/command,
// and closes InternalPureHandler over the sandbox as the handler behind it. It
// is called once by sandbox/internal/generated/cli/cli/new.go, and what it
// returns is one entry of Cli.Commands: the declaration alone, which the
// dispatch copies with api.BindCommand before binding a command line onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in InternalPureHandler.go.
func NewCommand(sandbox *api.Sandbox) *api.Command {
	self := command.NewCommand(sandbox)

	self.Name = "set_flag"
	self.Identifiers = []string{"set-flag"}
	self.Priority = 100
	self.Segments = 0
	self.Strict = true
	self.Pattern = "set-flag <Name>"
	self.Category = "Cli System"
	self.Help = "Rewrite one flag of a command's command.yaml"
	self.LongDescription = ""
	self.Examples = []string{}
	self.Hidden = false

	self.Args = []api.CommandArg{
		{
			Id:          "Command",
			Start:       0,
			End:         0,
			Type:        api.StringArg,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Description: "",
			Trigger:     api.Trigger{Exist: true, Type: api.EqualTrigger, Value: "set-flag", Negate: false, IgnoreCase: false},
		},
		{
			Id:          "Name",
			Start:       1,
			End:         1,
			Type:        api.StringArg,
			Required:    true,
			Default:     "",
			HasDefault:  false,
			Description: "the flag to rewrite (its name, its id or one of its keys)",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
		},
	}

	self.Flags = []api.CommandFlag{
		{
			Id:          "Target",
			Keys:        []string{"--command", "-c"},
			Type:        api.StringFlag,
			Required:    true,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "the command (a verb or its package name) that declares the flag",
		},
		{
			Id:          "Rename",
			Keys:        []string{"--rename"},
			Type:        api.StringFlag,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "the name the flag takes on",
		},
		{
			Id:          "Key",
			Keys:        []string{"--key"},
			Type:        api.StringArrayFlag,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "a spelling the flag answers to; the ones given replace the declared ones (repeatable)",
		},
		{
			Id:          "Type",
			Keys:        []string{"--type"},
			Type:        api.StringFlag,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "string, integer, number, boolean, string-array or integer-array",
		},
		{
			Id:          "Required",
			Keys:        []string{"--required"},
			Type:        api.BooleanFlag,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "a command line without the flag is a usage error",
		},
		{
			Id:          "Default",
			Keys:        []string{"--default"},
			Type:        api.StringFlag,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "the literal bound when the flag is absent",
		},
		{
			Id:          "Min",
			Keys:        []string{"--min"},
			Type:        api.StringFlag,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "smallest accepted value (integer/number only)",
		},
		{
			Id:          "Max",
			Keys:        []string{"--max"},
			Type:        api.StringFlag,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "largest accepted value (integer/number only)",
		},
		{
			Id:          "Enum",
			Keys:        []string{"--enum"},
			Type:        api.StringArrayFlag,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "a value the flag accepts; the ones given replace the declared ones (repeatable)",
		},
		{
			Id:          "Pattern",
			Keys:        []string{"--pattern"},
			Type:        api.StringFlag,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "a regular expression every value has to match",
		},
		{
			Id:          "Trigger",
			Keys:        []string{"--trigger"},
			Type:        api.StringFlag,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "what the value has to read as for the command to run",
		},
		{
			Id:          "TriggerType",
			Keys:        []string{"--trigger-type"},
			Type:        api.StringFlag,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "how the trigger is compared: equal, prefix, text-prefix, suffix, regex or one-of",
		},
		{
			Id:          "TriggerNegate",
			Keys:        []string{"--trigger-negate"},
			Type:        api.BooleanFlag,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "invert the trigger",
		},
		{
			Id:          "TriggerIgnoreCase",
			Keys:        []string{"--trigger-ignore-case"},
			Type:        api.BooleanFlag,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "compare the trigger without regard to case",
		},
		{
			Id:          "Description",
			Keys:        []string{"--description"},
			Type:        api.StringFlag,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "the one-line help text",
		},
		{
			Id:          "Clear",
			Keys:        []string{"--clear"},
			Type:        api.StringArrayFlag,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "a key to take off: keys, type, required, default, min, max, enum, pattern, trigger, trigger-negate, trigger-ignore-case or description (repeatable)",
		},
	}

	self.InternalPureHandler = func(props *api.CommandProps, entries *Entries, response *api.CommandResponse) error {
		return InternalPureHandler(sandbox, props, entries, response)
	}

	return self
}
